/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 8 --dst3 --isa avx512 --su --emit-c
 * Env overrides: (none)
 * Family: t1
 * ISA: 512-bit vectors, 32 vector regs
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: false (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: MONOLITHIC (below blocking threshold, or prime/Direct: no CT pass boundary)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: no
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx512f")))
void radix8_dst3_avx512(
    const double * __restrict__ in,
    double       * __restrict__ out,
    size_t K)
{
    const __m512d t0 = _mm512_set1_pd(0.98078528040322999);
    const __m512d t2 = _mm512_set1_pd(0.19509032201613);
    const __m512d t13 = _mm512_set1_pd(0.83146961230255001);
    const __m512d t15 = _mm512_set1_pd(0.55557023301959996);
    const __m512d t31 = _mm512_set1_pd(0.92387953251128996);
    const __m512d t33 = _mm512_set1_pd(0.38268343236509);
    const __m512d t44 = _mm512_set1_pd(1.4142135623731);
    const __m512d t62 = _mm512_set1_pd(0.70710678118655002);
    for (size_t k = 0; k < K; k += 8) {








        const __m512d t1 = _mm512_loadu_pd(&in[6*K + k]);
        const __m512d t3 = _mm512_loadu_pd(&in[0*K + k]);
        const __m512d t118 = _mm512_fmadd_pd(t2, t3, _mm512_mul_pd(t0, t1));
        const __m512d t127 = _mm512_fmsub_pd(t1, t2, _mm512_mul_pd(t0, t3));
        const __m512d t14 = _mm512_loadu_pd(&in[4*K + k]);
        const __m512d t16 = _mm512_loadu_pd(&in[2*K + k]);
        const __m512d t119 = _mm512_fmadd_pd(t15, t16, _mm512_mul_pd(t13, t14));
        const __m512d t128 = _mm512_fmsub_pd(t14, t15, _mm512_mul_pd(t13, t16));
        const __m512d t130 = _mm512_sub_pd(t119, t118);
        const __m512d t129 = _mm512_add_pd(t127, t128);
        const __m512d t144 = _mm512_sub_pd(t128, t127);
        const __m512d t120 = _mm512_add_pd(t118, t119);
        const __m512d t131 = _mm512_sub_pd(t129, t130);
        const __m512d t121 = _mm512_add_pd(t120, t120);
        const __m512d t146 = _mm512_sub_pd(_mm512_xor_pd(t144, _mm512_set1_pd(-0.0)), t144);
        const __m512d t132 = _mm512_add_pd(t131, t131);
        const __m512d t139 = _mm512_sub_pd(_mm512_sub_pd(_mm512_xor_pd(t130, _mm512_set1_pd(-0.0)), t129), _mm512_add_pd(t129, t130));
        const __m512d t32 = _mm512_loadu_pd(&in[5*K + k]);
        const __m512d t34 = _mm512_loadu_pd(&in[1*K + k]);
        const __m512d t115 = _mm512_fmadd_pd(t33, t34, _mm512_mul_pd(t31, t32));
        const __m512d t124 = _mm512_fmsub_pd(t32, t33, _mm512_mul_pd(t31, t34));
        const __m512d t116 = _mm512_add_pd(t115, t115);
        const __m512d t125 = _mm512_add_pd(t124, t124);
        const __m512d t43 = _mm512_loadu_pd(&in[3*K + k]);
        const __m512d t46 = _mm512_loadu_pd(&in[7*K + k]);
        const __m512d t154 = _mm512_fmadd_pd(t43, t44, t46);
        const __m512d t158 = _mm512_fnmadd_pd(t43, t44, t46);
        const __m512d t155 = _mm512_add_pd(t116, t154);
        const __m512d t171 = _mm512_add_pd(t121, t155);
        const __m512d t159 = _mm512_add_pd(t125, t158);
        const __m512d t160 = _mm512_fnmadd_pd(t62, t132, t159);
        const __m512d t161 = _mm512_sub_pd(t158, t125);
        const __m512d t168 = _mm512_fmadd_pd(t62, t139, t161);
        const __m512d t164 = _mm512_sub_pd(t154, t116);
        const __m512d t165 = _mm512_sub_pd(t164, t146);
        const __m512d t157 = _mm512_xor_pd(_mm512_sub_pd(t155, t121), _mm512_set1_pd(-0.0));
        const __m512d t167 = _mm512_xor_pd(_mm512_add_pd(t146, t164), _mm512_set1_pd(-0.0));
        const __m512d t163 = _mm512_xor_pd(_mm512_fnmadd_pd(t62, t139, t161), _mm512_set1_pd(-0.0));
        const __m512d t170 = _mm512_xor_pd(_mm512_fmadd_pd(t62, t132, t159), _mm512_set1_pd(-0.0));

        _mm512_storeu_pd(&out[7*K + k], t157);
        _mm512_storeu_pd(&out[6*K + k], t160);
        _mm512_storeu_pd(&out[5*K + k], t163);
        _mm512_storeu_pd(&out[4*K + k], t165);
        _mm512_storeu_pd(&out[3*K + k], t167);
        _mm512_storeu_pd(&out[2*K + k], t168);
        _mm512_storeu_pd(&out[1*K + k], t170);
        _mm512_storeu_pd(&out[0*K + k], t171);
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=45  flops=57  (add=11 sub=10 mul=6 fma=12 cmul=0 neg=6)
 *   essential_io=16 ops (vec_loads=8 + stores=8)  [+0 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=0 slots => +0 mem ops, 0 vectors live across pass boundary
 *   memory_floor=16 mem ops   peak_live(max-per-pass)=21   budget=28 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: fits (peak_live <= budget)
 */
