/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 16 --dct3 --isa avx2 --su --emit-c
 * Env overrides: (none)
 * Family: t1
 * ISA: 256-bit vectors, 16 vector regs (16-reg pressure rules apply)
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: false (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: MONOLITHIC (below blocking threshold, or prime/Direct: no CT pass boundary)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: no
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix16_dct3_avx2(
    const double * __restrict__ in,
    double       * __restrict__ out,
    size_t K)
{
    const __m256d t0 = _mm256_set1_pd(0.99518472667219693);
    const __m256d t2 = _mm256_set1_pd(0.098017140329560604);
    const __m256d t13 = _mm256_set1_pd(0.77301045336273699);
    const __m256d t15 = _mm256_set1_pd(0.63439328416364549);
    const __m256d t25 = _mm256_set1_pd(0.88192126434835505);
    const __m256d t27 = _mm256_set1_pd(0.47139673682599764);
    const __m256d t36 = _mm256_set1_pd(0.95694033573220882);
    const __m256d t38 = _mm256_set1_pd(0.29028467725446233);
    const __m256d t59 = _mm256_set1_pd(0.98078528040323043);
    const __m256d t61 = _mm256_set1_pd(0.19509032201612825);
    const __m256d t70 = _mm256_set1_pd(0.83146961230254524);
    const __m256d t72 = _mm256_set1_pd(0.55557023301960218);
    const __m256d t86 = _mm256_set1_pd(0.92387953251128674);
    const __m256d t88 = _mm256_set1_pd(0.38268343236508978);
    const __m256d t99 = _mm256_set1_pd(1.4142135623730949);
    const __m256d t115 = _mm256_set1_pd(0.41421356237309492);
    const __m256d t134 = _mm256_set1_pd(0.41421356237309515);
    const __m256d t155 = _mm256_set1_pd(0.70710678118654757);
    size_t k = 0;
    for (; k + 4 <= K; k += 4) {


















        const __m256d t1 = _mm256_loadu_pd(&in[1*K + k]);
        const __m256d t3 = _mm256_loadu_pd(&in[15*K + k]);
        const __m256d t340 = _mm256_fmadd_pd(t2, t3, _mm256_mul_pd(t0, t1));
        const __m256d t366 = _mm256_fmsub_pd(t1, t2, _mm256_mul_pd(t0, t3));
        const __m256d t14 = _mm256_loadu_pd(&in[7*K + k]);
        const __m256d t16 = _mm256_loadu_pd(&in[9*K + k]);
        const __m256d t341 = _mm256_fmadd_pd(t15, t16, _mm256_mul_pd(t13, t14));
        const __m256d t367 = _mm256_fmsub_pd(t14, t15, _mm256_mul_pd(t13, t16));
        const __m256d t342 = _mm256_add_pd(t340, t341);
        const __m256d t364 = _mm256_sub_pd(t341, t340);
        const __m256d t368 = _mm256_add_pd(t366, t367);
        const __m256d t404 = _mm256_sub_pd(t367, t366);
        const __m256d t26 = _mm256_loadu_pd(&in[5*K + k]);
        const __m256d t28 = _mm256_loadu_pd(&in[11*K + k]);
        const __m256d t343 = _mm256_fmadd_pd(t27, t28, _mm256_mul_pd(t25, t26));
        const __m256d t361 = _mm256_fmsub_pd(t26, t27, _mm256_mul_pd(t25, t28));
        const __m256d t37 = _mm256_loadu_pd(&in[3*K + k]);
        const __m256d t39 = _mm256_loadu_pd(&in[13*K + k]);
        const __m256d t344 = _mm256_fmadd_pd(t38, t39, _mm256_mul_pd(t36, t37));
        const __m256d t362 = _mm256_fmsub_pd(t37, t38, _mm256_mul_pd(t36, t39));
        const __m256d t345 = _mm256_add_pd(t343, t344);
        const __m256d t363 = _mm256_add_pd(t361, t362);
        const __m256d t369 = _mm256_sub_pd(t344, t343);
        const __m256d t403 = _mm256_sub_pd(t362, t361);
        const __m256d t402 = _mm256_sub_pd(t345, t342);
        const __m256d t365 = _mm256_sub_pd(t363, t364);
        const __m256d t370 = _mm256_add_pd(t368, t369);
        const __m256d t386 = _mm256_sub_pd(t369, t368);
        const __m256d t388 = _mm256_add_pd(t363, t364);
        const __m256d t392 = _mm256_sub_pd(_mm256_xor_pd(t364, _mm256_set1_pd(-0.0)), t363);
        const __m256d t405 = _mm256_sub_pd(t403, t404);
        const __m256d t346 = _mm256_add_pd(t342, t345);
        const __m256d t406 = _mm256_sub_pd(t402, t405);
        const __m256d t412 = _mm256_sub_pd(_mm256_xor_pd(t402, _mm256_set1_pd(-0.0)), t405);
        const __m256d t347 = _mm256_add_pd(t346, t346);
        const __m256d t438 = _mm256_sub_pd(_mm256_sub_pd(_mm256_xor_pd(t403, _mm256_set1_pd(-0.0)), t404), _mm256_add_pd(t403, t404));
        const __m256d t454 = _mm256_add_pd(t412, t412);
        const __m256d t477 = _mm256_add_pd(_mm256_fmadd_pd(t115, t370, t365), _mm256_fmadd_pd(t134, t370, t365));
        const __m256d t484 = _mm256_add_pd(_mm256_fmsub_pd(t134, t386, t388), _mm256_fmadd_pd(t134, t386, t392));
        const __m256d t495 = _mm256_sub_pd(_mm256_fmsub_pd(t134, t392, t386), _mm256_fmadd_pd(t134, t388, t386));
        const __m256d t501 = _mm256_sub_pd(_mm256_fmsub_pd(t134, t365, t370), _mm256_fnmadd_pd(t115, t365, t370));
        const __m256d t514 = _mm256_add_pd(t406, t406);
        const __m256d t60 = _mm256_loadu_pd(&in[2*K + k]);
        const __m256d t62 = _mm256_loadu_pd(&in[14*K + k]);
        const __m256d t332 = _mm256_fmadd_pd(t61, t62, _mm256_mul_pd(t59, t60));
        const __m256d t352 = _mm256_fmsub_pd(t60, t61, _mm256_mul_pd(t59, t62));
        const __m256d t71 = _mm256_loadu_pd(&in[6*K + k]);
        const __m256d t73 = _mm256_loadu_pd(&in[10*K + k]);
        const __m256d t333 = _mm256_fmadd_pd(t72, t73, _mm256_mul_pd(t70, t71));
        const __m256d t353 = _mm256_fmsub_pd(t71, t72, _mm256_mul_pd(t70, t73));
        const __m256d t354 = _mm256_add_pd(t352, t353);
        const __m256d t355 = _mm256_sub_pd(t333, t332);
        const __m256d t398 = _mm256_sub_pd(t353, t352);
        const __m256d t356 = _mm256_sub_pd(t354, t355);
        const __m256d t334 = _mm256_add_pd(t332, t333);
        const __m256d t335 = _mm256_add_pd(t334, t334);
        const __m256d t400 = _mm256_sub_pd(_mm256_xor_pd(t398, _mm256_set1_pd(-0.0)), t398);
        const __m256d t358 = _mm256_sub_pd(_mm256_xor_pd(t356, _mm256_set1_pd(-0.0)), t356);
        const __m256d t383 = _mm256_sub_pd(_mm256_sub_pd(_mm256_xor_pd(t355, _mm256_set1_pd(-0.0)), t354), _mm256_add_pd(t354, t355));
        const __m256d t87 = _mm256_loadu_pd(&in[4*K + k]);
        const __m256d t89 = _mm256_loadu_pd(&in[12*K + k]);
        const __m256d t336 = _mm256_fmadd_pd(t88, t89, _mm256_mul_pd(t86, t87));
        const __m256d t349 = _mm256_fmsub_pd(t87, t88, _mm256_mul_pd(t86, t89));
        const __m256d t337 = _mm256_add_pd(t336, t336);
        const __m256d t350 = _mm256_add_pd(t349, t349);
        const __m256d t98 = _mm256_loadu_pd(&in[8*K + k]);
        const __m256d t101 = _mm256_loadu_pd(&in[0*K + k]);
        const __m256d t468 = _mm256_fmadd_pd(t98, t99, t101);
        const __m256d t472 = _mm256_fnmadd_pd(t98, t99, t101);
        const __m256d t469 = _mm256_add_pd(t337, t468);
        const __m256d t473 = _mm256_add_pd(t350, t472);
        const __m256d t480 = _mm256_sub_pd(t472, t350);
        const __m256d t487 = _mm256_sub_pd(t468, t337);
        const __m256d t470 = _mm256_add_pd(t335, t469);
        const __m256d t471 = _mm256_sub_pd(t470, t347);
        const __m256d t513 = _mm256_add_pd(t347, t470);
        const __m256d t488 = _mm256_add_pd(t400, t487);
        const __m256d t521 = _mm256_fmadd_pd(t155, t514, t488);
        const __m256d t526 = _mm256_fnmadd_pd(t155, t514, t488);
        const __m256d t490 = _mm256_sub_pd(t487, t400);
        const __m256d t491 = _mm256_fnmadd_pd(t155, t454, t490);
        const __m256d t509 = _mm256_fmadd_pd(t155, t454, t490);
        const __m256d t504 = _mm256_sub_pd(t469, t335);
        const __m256d t505 = _mm256_sub_pd(t504, t438);
        const __m256d t506 = _mm256_add_pd(t438, t504);
        const __m256d t474 = _mm256_fnmadd_pd(t155, t358, t473);
        const __m256d t519 = _mm256_fnmadd_pd(t86, t477, t474);
        const __m256d t528 = _mm256_fmadd_pd(t86, t477, t474);
        const __m256d t481 = _mm256_fmadd_pd(t155, t383, t480);
        const __m256d t520 = _mm256_fnmadd_pd(t86, t484, t481);
        const __m256d t527 = _mm256_fmadd_pd(t86, t484, t481);
        const __m256d t492 = _mm256_fnmadd_pd(t155, t383, t480);
        const __m256d t522 = _mm256_fnmadd_pd(t86, t495, t492);
        const __m256d t525 = _mm256_fmadd_pd(t86, t495, t492);
        const __m256d t498 = _mm256_fmadd_pd(t155, t358, t473);
        const __m256d t523 = _mm256_fnmadd_pd(t86, t501, t498);
        const __m256d t524 = _mm256_fmadd_pd(t86, t501, t498);

        _mm256_storeu_pd(&out[15*K + k], t471);
        _mm256_storeu_pd(&out[14*K + k], t519);
        _mm256_storeu_pd(&out[13*K + k], t520);
        _mm256_storeu_pd(&out[12*K + k], t521);
        _mm256_storeu_pd(&out[11*K + k], t491);
        _mm256_storeu_pd(&out[10*K + k], t522);
        _mm256_storeu_pd(&out[9*K + k], t523);
        _mm256_storeu_pd(&out[8*K + k], t505);
        _mm256_storeu_pd(&out[7*K + k], t506);
        _mm256_storeu_pd(&out[6*K + k], t524);
        _mm256_storeu_pd(&out[5*K + k], t525);
        _mm256_storeu_pd(&out[4*K + k], t509);
        _mm256_storeu_pd(&out[3*K + k], t526);
        _mm256_storeu_pd(&out[2*K + k], t527);
        _mm256_storeu_pd(&out[1*K + k], t528);
        _mm256_storeu_pd(&out[0*K + k], t513);
    }
    if (k < K) {
        const size_t rem = K - k;
        if (rem == 1) {
        const double t0 = (0.99518472667219693);
        const double t13 = (0.77301045336273699);
        const double t25 = (0.88192126434835505);
        const double t36 = (0.95694033573220882);
        const double t59 = (0.98078528040323043);
        const double t70 = (0.83146961230254524);
        const double t2 = (0.098017140329560604);
        const double t15 = (0.63439328416364549);
        const double t27 = (0.47139673682599764);
        const double t38 = (0.29028467725446233);
        const double t61 = (0.19509032201612825);
        const double t72 = (0.55557023301960218);
        const double t86 = (0.92387953251128674);
        const double t88 = (0.38268343236508978);
        const double t99 = (1.4142135623730949);
        const double t115 = (0.41421356237309492);
        const double t134 = (0.41421356237309515);
        const double t155 = (0.70710678118654757);
        const double t1 = in[1*K + k];
        const double t3 = in[15*K + k];
        const double t340 = __builtin_fma(t2, t3, (t0 * t1));
        const double t366 = __builtin_fma(t1, t2, -((t0 * t3)));
        const double t14 = in[7*K + k];
        const double t16 = in[9*K + k];
        const double t341 = __builtin_fma(t15, t16, (t13 * t14));
        const double t367 = __builtin_fma(t14, t15, -((t13 * t16)));
        const double t342 = (t340 + t341);
        const double t364 = (t341 - t340);
        const double t368 = (t366 + t367);
        const double t404 = (t367 - t366);
        const double t26 = in[5*K + k];
        const double t28 = in[11*K + k];
        const double t343 = __builtin_fma(t27, t28, (t25 * t26));
        const double t361 = __builtin_fma(t26, t27, -((t25 * t28)));
        const double t37 = in[3*K + k];
        const double t39 = in[13*K + k];
        const double t344 = __builtin_fma(t38, t39, (t36 * t37));
        const double t362 = __builtin_fma(t37, t38, -((t36 * t39)));
        const double t345 = (t343 + t344);
        const double t363 = (t361 + t362);
        const double t369 = (t344 - t343);
        const double t403 = (t362 - t361);
        const double t402 = (t345 - t342);
        const double t365 = (t363 - t364);
        const double t370 = (t368 + t369);
        const double t386 = (t369 - t368);
        const double t388 = (t363 + t364);
        const double t392 = ((-(t364)) - t363);
        const double t405 = (t403 - t404);
        const double t346 = (t342 + t345);
        const double t406 = (t402 - t405);
        const double t412 = ((-(t402)) - t405);
        const double t347 = (t346 + t346);
        const double t438 = (((-(t403)) - t404) - (t403 + t404));
        const double t454 = (t412 + t412);
        const double t477 = (__builtin_fma(t115, t370, t365) + __builtin_fma(t134, t370, t365));
        const double t484 = (__builtin_fma(t134, t386, -(t388)) + __builtin_fma(t134, t386, t392));
        const double t495 = (__builtin_fma(t134, t392, -(t386)) - __builtin_fma(t134, t388, t386));
        const double t501 = (__builtin_fma(t134, t365, -(t370)) - __builtin_fma(-(t115), t365, t370));
        const double t514 = (t406 + t406);
        const double t60 = in[2*K + k];
        const double t62 = in[14*K + k];
        const double t332 = __builtin_fma(t61, t62, (t59 * t60));
        const double t352 = __builtin_fma(t60, t61, -((t59 * t62)));
        const double t71 = in[6*K + k];
        const double t73 = in[10*K + k];
        const double t333 = __builtin_fma(t72, t73, (t70 * t71));
        const double t353 = __builtin_fma(t71, t72, -((t70 * t73)));
        const double t354 = (t352 + t353);
        const double t355 = (t333 - t332);
        const double t398 = (t353 - t352);
        const double t356 = (t354 - t355);
        const double t334 = (t332 + t333);
        const double t335 = (t334 + t334);
        const double t400 = ((-(t398)) - t398);
        const double t358 = ((-(t356)) - t356);
        const double t383 = (((-(t355)) - t354) - (t354 + t355));
        const double t87 = in[4*K + k];
        const double t89 = in[12*K + k];
        const double t336 = __builtin_fma(t88, t89, (t86 * t87));
        const double t349 = __builtin_fma(t87, t88, -((t86 * t89)));
        const double t337 = (t336 + t336);
        const double t350 = (t349 + t349);
        const double t98 = in[8*K + k];
        const double t101 = in[0*K + k];
        const double t468 = __builtin_fma(t98, t99, t101);
        const double t472 = __builtin_fma(-(t98), t99, t101);
        const double t469 = (t337 + t468);
        const double t473 = (t350 + t472);
        const double t480 = (t472 - t350);
        const double t487 = (t468 - t337);
        const double t470 = (t335 + t469);
        const double t471 = (t470 - t347);
        const double t513 = (t347 + t470);
        const double t488 = (t400 + t487);
        const double t521 = __builtin_fma(t155, t514, t488);
        const double t526 = __builtin_fma(-(t155), t514, t488);
        const double t490 = (t487 - t400);
        const double t491 = __builtin_fma(-(t155), t454, t490);
        const double t509 = __builtin_fma(t155, t454, t490);
        const double t504 = (t469 - t335);
        const double t505 = (t504 - t438);
        const double t506 = (t438 + t504);
        const double t474 = __builtin_fma(-(t155), t358, t473);
        const double t519 = __builtin_fma(-(t86), t477, t474);
        const double t528 = __builtin_fma(t86, t477, t474);
        const double t481 = __builtin_fma(t155, t383, t480);
        const double t520 = __builtin_fma(-(t86), t484, t481);
        const double t527 = __builtin_fma(t86, t484, t481);
        const double t492 = __builtin_fma(-(t155), t383, t480);
        const double t522 = __builtin_fma(-(t86), t495, t492);
        const double t525 = __builtin_fma(t86, t495, t492);
        const double t498 = __builtin_fma(t155, t358, t473);
        const double t523 = __builtin_fma(-(t86), t501, t498);
        const double t524 = __builtin_fma(t86, t501, t498);

        out[15*K + k] = t471;
        out[14*K + k] = t519;
        out[13*K + k] = t520;
        out[12*K + k] = t521;
        out[11*K + k] = t491;
        out[10*K + k] = t522;
        out[9*K + k] = t523;
        out[8*K + k] = t505;
        out[7*K + k] = t506;
        out[6*K + k] = t524;
        out[5*K + k] = t525;
        out[4*K + k] = t509;
        out[3*K + k] = t526;
        out[2*K + k] = t527;
        out[1*K + k] = t528;
        out[0*K + k] = t513;
        } else {
            for (; k + 2 <= K; k += 2) {
        const __m128d t0 = _mm_set1_pd(0.99518472667219693);
        const __m128d t13 = _mm_set1_pd(0.77301045336273699);
        const __m128d t25 = _mm_set1_pd(0.88192126434835505);
        const __m128d t36 = _mm_set1_pd(0.95694033573220882);
        const __m128d t59 = _mm_set1_pd(0.98078528040323043);
        const __m128d t70 = _mm_set1_pd(0.83146961230254524);
        const __m128d t2 = _mm_set1_pd(0.098017140329560604);
        const __m128d t15 = _mm_set1_pd(0.63439328416364549);
        const __m128d t27 = _mm_set1_pd(0.47139673682599764);
        const __m128d t38 = _mm_set1_pd(0.29028467725446233);
        const __m128d t61 = _mm_set1_pd(0.19509032201612825);
        const __m128d t72 = _mm_set1_pd(0.55557023301960218);
        const __m128d t86 = _mm_set1_pd(0.92387953251128674);
        const __m128d t88 = _mm_set1_pd(0.38268343236508978);
        const __m128d t99 = _mm_set1_pd(1.4142135623730949);
        const __m128d t115 = _mm_set1_pd(0.41421356237309492);
        const __m128d t134 = _mm_set1_pd(0.41421356237309515);
        const __m128d t155 = _mm_set1_pd(0.70710678118654757);
        const __m128d t1 = _mm_loadu_pd(&in[1*K + k]);
        const __m128d t3 = _mm_loadu_pd(&in[15*K + k]);
        const __m128d t340 = _mm_fmadd_pd(t2, t3, _mm_mul_pd(t0, t1));
        const __m128d t366 = _mm_fmsub_pd(t1, t2, _mm_mul_pd(t0, t3));
        const __m128d t14 = _mm_loadu_pd(&in[7*K + k]);
        const __m128d t16 = _mm_loadu_pd(&in[9*K + k]);
        const __m128d t341 = _mm_fmadd_pd(t15, t16, _mm_mul_pd(t13, t14));
        const __m128d t367 = _mm_fmsub_pd(t14, t15, _mm_mul_pd(t13, t16));
        const __m128d t342 = _mm_add_pd(t340, t341);
        const __m128d t364 = _mm_sub_pd(t341, t340);
        const __m128d t368 = _mm_add_pd(t366, t367);
        const __m128d t404 = _mm_sub_pd(t367, t366);
        const __m128d t26 = _mm_loadu_pd(&in[5*K + k]);
        const __m128d t28 = _mm_loadu_pd(&in[11*K + k]);
        const __m128d t343 = _mm_fmadd_pd(t27, t28, _mm_mul_pd(t25, t26));
        const __m128d t361 = _mm_fmsub_pd(t26, t27, _mm_mul_pd(t25, t28));
        const __m128d t37 = _mm_loadu_pd(&in[3*K + k]);
        const __m128d t39 = _mm_loadu_pd(&in[13*K + k]);
        const __m128d t344 = _mm_fmadd_pd(t38, t39, _mm_mul_pd(t36, t37));
        const __m128d t362 = _mm_fmsub_pd(t37, t38, _mm_mul_pd(t36, t39));
        const __m128d t345 = _mm_add_pd(t343, t344);
        const __m128d t363 = _mm_add_pd(t361, t362);
        const __m128d t369 = _mm_sub_pd(t344, t343);
        const __m128d t403 = _mm_sub_pd(t362, t361);
        const __m128d t402 = _mm_sub_pd(t345, t342);
        const __m128d t365 = _mm_sub_pd(t363, t364);
        const __m128d t370 = _mm_add_pd(t368, t369);
        const __m128d t386 = _mm_sub_pd(t369, t368);
        const __m128d t388 = _mm_add_pd(t363, t364);
        const __m128d t392 = _mm_sub_pd(_mm_xor_pd(t364, _mm_set1_pd(-0.0)), t363);
        const __m128d t405 = _mm_sub_pd(t403, t404);
        const __m128d t346 = _mm_add_pd(t342, t345);
        const __m128d t406 = _mm_sub_pd(t402, t405);
        const __m128d t412 = _mm_sub_pd(_mm_xor_pd(t402, _mm_set1_pd(-0.0)), t405);
        const __m128d t347 = _mm_add_pd(t346, t346);
        const __m128d t438 = _mm_sub_pd(_mm_sub_pd(_mm_xor_pd(t403, _mm_set1_pd(-0.0)), t404), _mm_add_pd(t403, t404));
        const __m128d t454 = _mm_add_pd(t412, t412);
        const __m128d t477 = _mm_add_pd(_mm_fmadd_pd(t115, t370, t365), _mm_fmadd_pd(t134, t370, t365));
        const __m128d t484 = _mm_add_pd(_mm_fmsub_pd(t134, t386, t388), _mm_fmadd_pd(t134, t386, t392));
        const __m128d t495 = _mm_sub_pd(_mm_fmsub_pd(t134, t392, t386), _mm_fmadd_pd(t134, t388, t386));
        const __m128d t501 = _mm_sub_pd(_mm_fmsub_pd(t134, t365, t370), _mm_fnmadd_pd(t115, t365, t370));
        const __m128d t514 = _mm_add_pd(t406, t406);
        const __m128d t60 = _mm_loadu_pd(&in[2*K + k]);
        const __m128d t62 = _mm_loadu_pd(&in[14*K + k]);
        const __m128d t332 = _mm_fmadd_pd(t61, t62, _mm_mul_pd(t59, t60));
        const __m128d t352 = _mm_fmsub_pd(t60, t61, _mm_mul_pd(t59, t62));
        const __m128d t71 = _mm_loadu_pd(&in[6*K + k]);
        const __m128d t73 = _mm_loadu_pd(&in[10*K + k]);
        const __m128d t333 = _mm_fmadd_pd(t72, t73, _mm_mul_pd(t70, t71));
        const __m128d t353 = _mm_fmsub_pd(t71, t72, _mm_mul_pd(t70, t73));
        const __m128d t354 = _mm_add_pd(t352, t353);
        const __m128d t355 = _mm_sub_pd(t333, t332);
        const __m128d t398 = _mm_sub_pd(t353, t352);
        const __m128d t356 = _mm_sub_pd(t354, t355);
        const __m128d t334 = _mm_add_pd(t332, t333);
        const __m128d t335 = _mm_add_pd(t334, t334);
        const __m128d t400 = _mm_sub_pd(_mm_xor_pd(t398, _mm_set1_pd(-0.0)), t398);
        const __m128d t358 = _mm_sub_pd(_mm_xor_pd(t356, _mm_set1_pd(-0.0)), t356);
        const __m128d t383 = _mm_sub_pd(_mm_sub_pd(_mm_xor_pd(t355, _mm_set1_pd(-0.0)), t354), _mm_add_pd(t354, t355));
        const __m128d t87 = _mm_loadu_pd(&in[4*K + k]);
        const __m128d t89 = _mm_loadu_pd(&in[12*K + k]);
        const __m128d t336 = _mm_fmadd_pd(t88, t89, _mm_mul_pd(t86, t87));
        const __m128d t349 = _mm_fmsub_pd(t87, t88, _mm_mul_pd(t86, t89));
        const __m128d t337 = _mm_add_pd(t336, t336);
        const __m128d t350 = _mm_add_pd(t349, t349);
        const __m128d t98 = _mm_loadu_pd(&in[8*K + k]);
        const __m128d t101 = _mm_loadu_pd(&in[0*K + k]);
        const __m128d t468 = _mm_fmadd_pd(t98, t99, t101);
        const __m128d t472 = _mm_fnmadd_pd(t98, t99, t101);
        const __m128d t469 = _mm_add_pd(t337, t468);
        const __m128d t473 = _mm_add_pd(t350, t472);
        const __m128d t480 = _mm_sub_pd(t472, t350);
        const __m128d t487 = _mm_sub_pd(t468, t337);
        const __m128d t470 = _mm_add_pd(t335, t469);
        const __m128d t471 = _mm_sub_pd(t470, t347);
        const __m128d t513 = _mm_add_pd(t347, t470);
        const __m128d t488 = _mm_add_pd(t400, t487);
        const __m128d t521 = _mm_fmadd_pd(t155, t514, t488);
        const __m128d t526 = _mm_fnmadd_pd(t155, t514, t488);
        const __m128d t490 = _mm_sub_pd(t487, t400);
        const __m128d t491 = _mm_fnmadd_pd(t155, t454, t490);
        const __m128d t509 = _mm_fmadd_pd(t155, t454, t490);
        const __m128d t504 = _mm_sub_pd(t469, t335);
        const __m128d t505 = _mm_sub_pd(t504, t438);
        const __m128d t506 = _mm_add_pd(t438, t504);
        const __m128d t474 = _mm_fnmadd_pd(t155, t358, t473);
        const __m128d t519 = _mm_fnmadd_pd(t86, t477, t474);
        const __m128d t528 = _mm_fmadd_pd(t86, t477, t474);
        const __m128d t481 = _mm_fmadd_pd(t155, t383, t480);
        const __m128d t520 = _mm_fnmadd_pd(t86, t484, t481);
        const __m128d t527 = _mm_fmadd_pd(t86, t484, t481);
        const __m128d t492 = _mm_fnmadd_pd(t155, t383, t480);
        const __m128d t522 = _mm_fnmadd_pd(t86, t495, t492);
        const __m128d t525 = _mm_fmadd_pd(t86, t495, t492);
        const __m128d t498 = _mm_fmadd_pd(t155, t358, t473);
        const __m128d t523 = _mm_fnmadd_pd(t86, t501, t498);
        const __m128d t524 = _mm_fmadd_pd(t86, t501, t498);

        _mm_storeu_pd(&out[15*K + k], t471);
        _mm_storeu_pd(&out[14*K + k], t519);
        _mm_storeu_pd(&out[13*K + k], t520);
        _mm_storeu_pd(&out[12*K + k], t521);
        _mm_storeu_pd(&out[11*K + k], t491);
        _mm_storeu_pd(&out[10*K + k], t522);
        _mm_storeu_pd(&out[9*K + k], t523);
        _mm_storeu_pd(&out[8*K + k], t505);
        _mm_storeu_pd(&out[7*K + k], t506);
        _mm_storeu_pd(&out[6*K + k], t524);
        _mm_storeu_pd(&out[5*K + k], t525);
        _mm_storeu_pd(&out[4*K + k], t509);
        _mm_storeu_pd(&out[3*K + k], t526);
        _mm_storeu_pd(&out[2*K + k], t527);
        _mm_storeu_pd(&out[1*K + k], t528);
        _mm_storeu_pd(&out[0*K + k], t513);
            }
            if (k < K) {
        const double t0 = (0.99518472667219693);
        const double t13 = (0.77301045336273699);
        const double t25 = (0.88192126434835505);
        const double t36 = (0.95694033573220882);
        const double t59 = (0.98078528040323043);
        const double t70 = (0.83146961230254524);
        const double t2 = (0.098017140329560604);
        const double t15 = (0.63439328416364549);
        const double t27 = (0.47139673682599764);
        const double t38 = (0.29028467725446233);
        const double t61 = (0.19509032201612825);
        const double t72 = (0.55557023301960218);
        const double t86 = (0.92387953251128674);
        const double t88 = (0.38268343236508978);
        const double t99 = (1.4142135623730949);
        const double t115 = (0.41421356237309492);
        const double t134 = (0.41421356237309515);
        const double t155 = (0.70710678118654757);
        const double t1 = in[1*K + k];
        const double t3 = in[15*K + k];
        const double t340 = __builtin_fma(t2, t3, (t0 * t1));
        const double t366 = __builtin_fma(t1, t2, -((t0 * t3)));
        const double t14 = in[7*K + k];
        const double t16 = in[9*K + k];
        const double t341 = __builtin_fma(t15, t16, (t13 * t14));
        const double t367 = __builtin_fma(t14, t15, -((t13 * t16)));
        const double t342 = (t340 + t341);
        const double t364 = (t341 - t340);
        const double t368 = (t366 + t367);
        const double t404 = (t367 - t366);
        const double t26 = in[5*K + k];
        const double t28 = in[11*K + k];
        const double t343 = __builtin_fma(t27, t28, (t25 * t26));
        const double t361 = __builtin_fma(t26, t27, -((t25 * t28)));
        const double t37 = in[3*K + k];
        const double t39 = in[13*K + k];
        const double t344 = __builtin_fma(t38, t39, (t36 * t37));
        const double t362 = __builtin_fma(t37, t38, -((t36 * t39)));
        const double t345 = (t343 + t344);
        const double t363 = (t361 + t362);
        const double t369 = (t344 - t343);
        const double t403 = (t362 - t361);
        const double t402 = (t345 - t342);
        const double t365 = (t363 - t364);
        const double t370 = (t368 + t369);
        const double t386 = (t369 - t368);
        const double t388 = (t363 + t364);
        const double t392 = ((-(t364)) - t363);
        const double t405 = (t403 - t404);
        const double t346 = (t342 + t345);
        const double t406 = (t402 - t405);
        const double t412 = ((-(t402)) - t405);
        const double t347 = (t346 + t346);
        const double t438 = (((-(t403)) - t404) - (t403 + t404));
        const double t454 = (t412 + t412);
        const double t477 = (__builtin_fma(t115, t370, t365) + __builtin_fma(t134, t370, t365));
        const double t484 = (__builtin_fma(t134, t386, -(t388)) + __builtin_fma(t134, t386, t392));
        const double t495 = (__builtin_fma(t134, t392, -(t386)) - __builtin_fma(t134, t388, t386));
        const double t501 = (__builtin_fma(t134, t365, -(t370)) - __builtin_fma(-(t115), t365, t370));
        const double t514 = (t406 + t406);
        const double t60 = in[2*K + k];
        const double t62 = in[14*K + k];
        const double t332 = __builtin_fma(t61, t62, (t59 * t60));
        const double t352 = __builtin_fma(t60, t61, -((t59 * t62)));
        const double t71 = in[6*K + k];
        const double t73 = in[10*K + k];
        const double t333 = __builtin_fma(t72, t73, (t70 * t71));
        const double t353 = __builtin_fma(t71, t72, -((t70 * t73)));
        const double t354 = (t352 + t353);
        const double t355 = (t333 - t332);
        const double t398 = (t353 - t352);
        const double t356 = (t354 - t355);
        const double t334 = (t332 + t333);
        const double t335 = (t334 + t334);
        const double t400 = ((-(t398)) - t398);
        const double t358 = ((-(t356)) - t356);
        const double t383 = (((-(t355)) - t354) - (t354 + t355));
        const double t87 = in[4*K + k];
        const double t89 = in[12*K + k];
        const double t336 = __builtin_fma(t88, t89, (t86 * t87));
        const double t349 = __builtin_fma(t87, t88, -((t86 * t89)));
        const double t337 = (t336 + t336);
        const double t350 = (t349 + t349);
        const double t98 = in[8*K + k];
        const double t101 = in[0*K + k];
        const double t468 = __builtin_fma(t98, t99, t101);
        const double t472 = __builtin_fma(-(t98), t99, t101);
        const double t469 = (t337 + t468);
        const double t473 = (t350 + t472);
        const double t480 = (t472 - t350);
        const double t487 = (t468 - t337);
        const double t470 = (t335 + t469);
        const double t471 = (t470 - t347);
        const double t513 = (t347 + t470);
        const double t488 = (t400 + t487);
        const double t521 = __builtin_fma(t155, t514, t488);
        const double t526 = __builtin_fma(-(t155), t514, t488);
        const double t490 = (t487 - t400);
        const double t491 = __builtin_fma(-(t155), t454, t490);
        const double t509 = __builtin_fma(t155, t454, t490);
        const double t504 = (t469 - t335);
        const double t505 = (t504 - t438);
        const double t506 = (t438 + t504);
        const double t474 = __builtin_fma(-(t155), t358, t473);
        const double t519 = __builtin_fma(-(t86), t477, t474);
        const double t528 = __builtin_fma(t86, t477, t474);
        const double t481 = __builtin_fma(t155, t383, t480);
        const double t520 = __builtin_fma(-(t86), t484, t481);
        const double t527 = __builtin_fma(t86, t484, t481);
        const double t492 = __builtin_fma(-(t155), t383, t480);
        const double t522 = __builtin_fma(-(t86), t495, t492);
        const double t525 = __builtin_fma(t86, t495, t492);
        const double t498 = __builtin_fma(t155, t358, t473);
        const double t523 = __builtin_fma(-(t86), t501, t498);
        const double t524 = __builtin_fma(t86, t501, t498);

        out[15*K + k] = t471;
        out[14*K + k] = t519;
        out[13*K + k] = t520;
        out[12*K + k] = t521;
        out[11*K + k] = t491;
        out[10*K + k] = t522;
        out[9*K + k] = t523;
        out[8*K + k] = t505;
        out[7*K + k] = t506;
        out[6*K + k] = t524;
        out[5*K + k] = t525;
        out[4*K + k] = t509;
        out[3*K + k] = t526;
        out[2*K + k] = t527;
        out[1*K + k] = t528;
        out[0*K + k] = t513;
            }
        }
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=113  flops=153  (add=25 sub=28 mul=14 fma=40 cmul=0 neg=6)
 *   essential_io=32 ops (vec_loads=16 + stores=16)  [+0 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=0 slots => +0 mem ops, 0 vectors live across pass boundary
 *   memory_floor=32 mem ops   peak_live(max-per-pass)=34   budget=14 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: SPILLS (peak_live > budget)
 */
