#!/bin/bash
# Build the generator (explicit target only), prove the default emission
# byte-identical to eefc1bea's generator on every AVX2/AVX-512 IL recipe, then
# emit the six AVX2 remainder arms of the odd n1 / n1t / t2 kernels with the
# odd frame fix ON (VFFT_CX_ODDROLL=1 VFFT_CX_ODDP1=1), symbol suffixed _<arm>.
set -u
export DUNE_CACHE=disabled
S=/mnt/c/Users/Tugbars/AppData/Local/Temp/claude/c--Users-Tugbars-Desktop-highSpeedFFT/06015967-850f-49d4-a1b3-34bc9127dbe6/scratchpad
GNEW=/mnt/c/Users/Tugbars/Desktop/highSpeedFFT/src/dag-fft-compiler/generator
GOLD=$S/wt_aac38094/src/dag-fft-compiler/generator
CODE=/mnt/c/Users/Tugbars/Desktop/highSpeedFFT/src/dag-fft-compiler/codelets/zil/avx2
eval "$(opam env 2>/dev/null)" 2>/dev/null
cd "$GNEW" || exit 1
dune build ./bin/gen_radix.exe 2>&1 | head -40
NEWX=$GNEW/_build/default/bin/gen_radix.exe
OLDX=$GOLD/_build/default/bin/gen_radix.exe
[ -x "$NEWX" ] && [ -x "$OLDX" ] || { echo "NO GENERATOR"; exit 1; }
ls -la "$NEWX" | awk '{print "new generator", $5, $6, $7, $8}'
O=$S/mech_id; rm -rf "$O"; mkdir -p "$O"
same=0; diff=0; n=0
while IFS= read -r f; do
  rec=$(grep -m1 '^ \* Generated by:' "$f" | sed -E 's/^ \* Generated by: (\.\/_build\/default\/bin\/)?gen_radix\.exe //')
  envl=$(grep -m1 '^ \* Env overrides:' "$f" | sed -E 's/^ \* Env overrides: //')
  case "$envl" in "(none)"*) envl="";; esac
  [ -z "$rec" ] && continue
  n=$((n+1)); b=$(basename "$f" .c)
  (cd "$GNEW" && env $envl "$NEWX" $rec > "$O/$b.new" 2>/dev/null)
  (cd "$GOLD" && env $envl "$OLDX" $rec > "$O/$b.old" 2>/dev/null)
  if cmp -s "$O/$b.new" "$O/$b.old"; then same=$((same+1)); rm -f "$O/$b.new" "$O/$b.old"; else diff=$((diff+1)); echo "DIFF $b"; fi
done < <(find "$CODE" "$CODE/../avx512" -name '*.c' | sort)
echo "recipes=$n identical=$same differ=$diff"
V=$S/mech_k; rm -rf "$V"; mkdir -p "$V"
m=0
for R in 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 37 41 43 47; do
  for K in n1 n1t t2; do
    ARMS="narrow masked overrun"
    [ "$R" -ge 9 ] && [ "$K" != n1t ] && ARMS="$ARMS blk_narrow blk_masked blk_overrun"
    for A in $ARMS; do
      f="$V/radix${R}_z_${K}_fwd_avx2_${A}.c"
      (cd "$GNEW" && VFFT_CX_ODDROLL=1 VFFT_CX_ODDP1=1 VFFT_TAIL256=$A "$NEWX" "$R" --cil-$K --isa avx2 --uarch raptor_lake_avx2 --emit-c) > "$f.tmp" 2> "$f.err" \
        || { echo "REFUSED $R $K $A: $(head -c 300 "$f.err")"; rm -f "$f.tmp"; continue; }
      sed "s/\bradix${R}_z_${K}_fwd_avx2(/radix${R}_z_${K}_fwd_avx2_${A}(/" "$f.tmp" > "$f"; rm -f "$f.tmp" "$f.err"
      m=$((m+1))
    done
  done
done
echo "emitted $m arm kernels"
