/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 7 --hc2hc --t1s --isa avx512 --su --emit-c
 * Env overrides: (none)
 * Family: t1s (broadcast twiddles)
 * ISA: 512-bit vectors, 32 vector regs
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: false (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: MONOLITHIC (below blocking threshold, or prime/Direct: no CT pass boundary)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: no
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx512f")))
void radix7_hc2hc_dit_fwd_avx512(
    const double * __restrict__ in_re,
    const double * __restrict__ in_im,
    double       * __restrict__ out_re,
    double       * __restrict__ out_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    ptrdiff_t is,
    ptrdiff_t os,
    size_t vl)
{
    const __m512d t13 = _mm512_set1_pd(0.55495813208736999);
    const __m512d t29 = _mm512_set1_pd(0.80193773580483996);
    const __m512d t45 = _mm512_set1_pd(0.97492791218181996);
    const __m512d t48 = _mm512_set1_pd(0.35689586789221001);
    const __m512d t52 = _mm512_set1_pd(0.69202147163009997);
    const __m512d t56 = _mm512_set1_pd(0.90096886790242003);
    size_t v = 0;
    for (; v + 8 <= vl; v += 8) {






        const __m512d t0 = _mm512_loadu_pd(&in_re[4*is + v]);
        const __m512d t1 = _mm512_set1_pd(tw_im[3]);
        const __m512d t2 = _mm512_loadu_pd(&in_im[4*is + v]);
        const __m512d t3 = _mm512_set1_pd(tw_re[3]);
        const __m512d t5 = _mm512_fmadd_pd(t0, t1, _mm512_mul_pd(t2, t3));
        const __m512d t4 = _mm512_fnmadd_pd(t2, t1, _mm512_mul_pd(t0, t3));
        const __m512d t6 = _mm512_loadu_pd(&in_re[3*is + v]);
        const __m512d t7 = _mm512_set1_pd(tw_im[2]);
        const __m512d t8 = _mm512_loadu_pd(&in_im[3*is + v]);
        const __m512d t9 = _mm512_set1_pd(tw_re[2]);
        const __m512d t11 = _mm512_fmadd_pd(t6, t7, _mm512_mul_pd(t8, t9));
        const __m512d t10 = _mm512_fnmadd_pd(t8, t7, _mm512_mul_pd(t6, t9));
        const __m512d t98 = _mm512_add_pd(t5, t11);
        const __m512d t54 = _mm512_add_pd(t4, t10);
        const __m512d t95 = _mm512_sub_pd(t4, t10);
        const __m512d t12 = _mm512_sub_pd(t11, t5);
        const __m512d t15 = _mm512_loadu_pd(&in_re[6*is + v]);
        const __m512d t16 = _mm512_set1_pd(tw_im[5]);
        const __m512d t17 = _mm512_loadu_pd(&in_im[6*is + v]);
        const __m512d t18 = _mm512_set1_pd(tw_re[5]);
        const __m512d t20 = _mm512_fmadd_pd(t15, t16, _mm512_mul_pd(t17, t18));
        const __m512d t19 = _mm512_fnmadd_pd(t17, t16, _mm512_mul_pd(t15, t18));
        const __m512d t21 = _mm512_loadu_pd(&in_re[1*is + v]);
        const __m512d t22 = _mm512_set1_pd(tw_im[0]);
        const __m512d t23 = _mm512_loadu_pd(&in_im[1*is + v]);
        const __m512d t24 = _mm512_set1_pd(tw_re[0]);
        const __m512d t26 = _mm512_fmadd_pd(t21, t22, _mm512_mul_pd(t23, t24));
        const __m512d t25 = _mm512_fnmadd_pd(t23, t22, _mm512_mul_pd(t21, t24));
        const __m512d t103 = _mm512_add_pd(t20, t26);
        const __m512d t50 = _mm512_add_pd(t19, t25);
        const __m512d t90 = _mm512_sub_pd(t19, t25);
        const __m512d t27 = _mm512_sub_pd(t26, t20);
        const __m512d t31 = _mm512_loadu_pd(&in_re[5*is + v]);
        const __m512d t32 = _mm512_set1_pd(tw_im[4]);
        const __m512d t33 = _mm512_loadu_pd(&in_im[5*is + v]);
        const __m512d t34 = _mm512_set1_pd(tw_re[4]);
        const __m512d t36 = _mm512_fmadd_pd(t31, t32, _mm512_mul_pd(t33, t34));
        const __m512d t35 = _mm512_fnmadd_pd(t33, t32, _mm512_mul_pd(t31, t34));
        const __m512d t37 = _mm512_loadu_pd(&in_re[2*is + v]);
        const __m512d t38 = _mm512_set1_pd(tw_im[1]);
        const __m512d t39 = _mm512_loadu_pd(&in_im[2*is + v]);
        const __m512d t40 = _mm512_set1_pd(tw_re[1]);
        const __m512d t42 = _mm512_fmadd_pd(t37, t38, _mm512_mul_pd(t39, t40));
        const __m512d t41 = _mm512_fnmadd_pd(t39, t38, _mm512_mul_pd(t37, t40));
        const __m512d t100 = _mm512_add_pd(t36, t42);
        const __m512d t47 = _mm512_add_pd(t35, t41);
        const __m512d t92 = _mm512_sub_pd(t35, t41);
        const __m512d t43 = _mm512_sub_pd(t42, t36);
        const __m512d t268 = _mm512_fnmadd_pd(t29, _mm512_fnmadd_pd(t13, t90, t92), t95);
        const __m512d t275 = _mm512_fnmadd_pd(t29, _mm512_fmadd_pd(t13, t92, t95), t90);
        const __m512d t283 = _mm512_fmadd_pd(t29, _mm512_fmadd_pd(t13, t95, t90), t92);
        const __m512d t251 = _mm512_fmadd_pd(t29, _mm512_fmadd_pd(t12, t13, t27), t43);
        const __m512d t257 = _mm512_fnmadd_pd(t29, _mm512_fmadd_pd(t13, t43, t12), t27);
        const __m512d t264 = _mm512_fnmadd_pd(t29, _mm512_fnmadd_pd(t13, t27, t43), t12);
        const __m512d t58 = _mm512_loadu_pd(&in_re[0*is + v]);
        const __m512d t63 = _mm512_add_pd(t54, _mm512_add_pd(t47, _mm512_add_pd(t50, t58)));
        const __m512d t293 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t47, t48, t50), t54), t58);
        const __m512d t294 = _mm512_fnmadd_pd(t45, t251, t293);
        const __m512d t297 = _mm512_fmadd_pd(t45, t251, t293);
        const __m512d t295 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t50, t54), t47), t58);
        const __m512d t296 = _mm512_fnmadd_pd(t45, t257, t295);
        const __m512d t300 = _mm512_fmadd_pd(t45, t257, t295);
        const __m512d t298 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t54, t47), t50), t58);
        const __m512d t299 = _mm512_fnmadd_pd(t45, t264, t298);
        const __m512d t303 = _mm512_fmadd_pd(t45, t264, t298);
        const __m512d t106 = _mm512_loadu_pd(&in_im[0*is + v]);
        const __m512d t301 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t98, t100), t103), t106);
        const __m512d t302 = _mm512_fmadd_pd(t45, t268, t301);
        const __m512d t304 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t103, t98), t100), t106);
        const __m512d t305 = _mm512_fmadd_pd(t45, t275, t304);
        const __m512d t308 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t100, t103), t98), t106);
        const __m512d t309 = _mm512_fmadd_pd(t45, t283, t308);
        const __m512d t140 = _mm512_add_pd(t98, _mm512_add_pd(t100, _mm512_add_pd(t103, t106)));
        const __m512d t307 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t268, t301), _mm512_set1_pd(-0.0));
        const __m512d t311 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t275, t304), _mm512_set1_pd(-0.0));
        const __m512d t313 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t283, t308), _mm512_set1_pd(-0.0));

        _mm512_storeu_pd(&out_im[0*os + v], t294);
        _mm512_storeu_pd(&out_re[0*os + v], t63);
        _mm512_storeu_pd(&out_im[1*os + v], t296);
        _mm512_storeu_pd(&out_re[1*os + v], t297);
        _mm512_storeu_pd(&out_im[2*os + v], t299);
        _mm512_storeu_pd(&out_re[2*os + v], t300);
        _mm512_storeu_pd(&out_im[3*os + v], t302);
        _mm512_storeu_pd(&out_re[3*os + v], t303);
        _mm512_storeu_pd(&out_im[4*os + v], t305);
        _mm512_storeu_pd(&out_re[4*os + v], t307);
        _mm512_storeu_pd(&out_im[5*os + v], t309);
        _mm512_storeu_pd(&out_re[5*os + v], t311);
        _mm512_storeu_pd(&out_im[6*os + v], t140);
        _mm512_storeu_pd(&out_re[6*os + v], t313);
    }
    if (v < vl) {
        const size_t rem = vl - v;
        if (rem == 1) {
        const double t48 = (0.35689586789221001);
        const double t13 = (0.55495813208736999);
        const double t52 = (0.69202147163009997);
        const double t29 = (0.80193773580483996);
        const double t56 = (0.90096886790242003);
        const double t45 = (0.97492791218181996);
        const double t0 = in_re[4*is + v];
        const double t1 = (tw_im[3]);
        const double t2 = in_im[4*is + v];
        const double t3 = (tw_re[3]);
        const double t5 = __builtin_fma(t0, t1, (t2 * t3));
        const double t4 = __builtin_fma(-(t2), t1, (t0 * t3));
        const double t6 = in_re[3*is + v];
        const double t7 = (tw_im[2]);
        const double t8 = in_im[3*is + v];
        const double t9 = (tw_re[2]);
        const double t11 = __builtin_fma(t6, t7, (t8 * t9));
        const double t10 = __builtin_fma(-(t8), t7, (t6 * t9));
        const double t98 = (t5 + t11);
        const double t54 = (t4 + t10);
        const double t95 = (t4 - t10);
        const double t12 = (t11 - t5);
        const double t15 = in_re[6*is + v];
        const double t16 = (tw_im[5]);
        const double t17 = in_im[6*is + v];
        const double t18 = (tw_re[5]);
        const double t20 = __builtin_fma(t15, t16, (t17 * t18));
        const double t19 = __builtin_fma(-(t17), t16, (t15 * t18));
        const double t21 = in_re[1*is + v];
        const double t22 = (tw_im[0]);
        const double t23 = in_im[1*is + v];
        const double t24 = (tw_re[0]);
        const double t26 = __builtin_fma(t21, t22, (t23 * t24));
        const double t25 = __builtin_fma(-(t23), t22, (t21 * t24));
        const double t103 = (t20 + t26);
        const double t50 = (t19 + t25);
        const double t90 = (t19 - t25);
        const double t27 = (t26 - t20);
        const double t31 = in_re[5*is + v];
        const double t32 = (tw_im[4]);
        const double t33 = in_im[5*is + v];
        const double t34 = (tw_re[4]);
        const double t36 = __builtin_fma(t31, t32, (t33 * t34));
        const double t35 = __builtin_fma(-(t33), t32, (t31 * t34));
        const double t37 = in_re[2*is + v];
        const double t38 = (tw_im[1]);
        const double t39 = in_im[2*is + v];
        const double t40 = (tw_re[1]);
        const double t42 = __builtin_fma(t37, t38, (t39 * t40));
        const double t41 = __builtin_fma(-(t39), t38, (t37 * t40));
        const double t100 = (t36 + t42);
        const double t47 = (t35 + t41);
        const double t92 = (t35 - t41);
        const double t43 = (t42 - t36);
        const double t268 = __builtin_fma(-(t29), __builtin_fma(-(t13), t90, t92), t95);
        const double t275 = __builtin_fma(-(t29), __builtin_fma(t13, t92, t95), t90);
        const double t283 = __builtin_fma(t29, __builtin_fma(t13, t95, t90), t92);
        const double t251 = __builtin_fma(t29, __builtin_fma(t12, t13, t27), t43);
        const double t257 = __builtin_fma(-(t29), __builtin_fma(t13, t43, t12), t27);
        const double t264 = __builtin_fma(-(t29), __builtin_fma(-(t13), t27, t43), t12);
        const double t58 = in_re[0*is + v];
        const double t63 = (t54 + (t47 + (t50 + t58)));
        const double t293 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t47), t48, t50), t54), t58);
        const double t294 = __builtin_fma(-(t45), t251, t293);
        const double t297 = __builtin_fma(t45, t251, t293);
        const double t295 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t48), t50, t54), t47), t58);
        const double t296 = __builtin_fma(-(t45), t257, t295);
        const double t300 = __builtin_fma(t45, t257, t295);
        const double t298 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t48), t54, t47), t50), t58);
        const double t299 = __builtin_fma(-(t45), t264, t298);
        const double t303 = __builtin_fma(t45, t264, t298);
        const double t106 = in_im[0*is + v];
        const double t301 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t48), t98, t100), t103), t106);
        const double t302 = __builtin_fma(t45, t268, t301);
        const double t304 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t48), t103, t98), t100), t106);
        const double t305 = __builtin_fma(t45, t275, t304);
        const double t308 = __builtin_fma(-(t56), __builtin_fma(-(t52), __builtin_fma(-(t48), t100, t103), t98), t106);
        const double t309 = __builtin_fma(t45, t283, t308);
        const double t140 = (t98 + (t100 + (t103 + t106)));
        const double t307 = (-(__builtin_fma(-(t45), t268, t301)));
        const double t311 = (-(__builtin_fma(-(t45), t275, t304)));
        const double t313 = (-(__builtin_fma(-(t45), t283, t308)));

        out_im[0*os + v] = t294;
        out_re[0*os + v] = t63;
        out_im[1*os + v] = t296;
        out_re[1*os + v] = t297;
        out_im[2*os + v] = t299;
        out_re[2*os + v] = t300;
        out_im[3*os + v] = t302;
        out_re[3*os + v] = t303;
        out_im[4*os + v] = t305;
        out_re[4*os + v] = t307;
        out_im[5*os + v] = t309;
        out_re[5*os + v] = t311;
        out_im[6*os + v] = t140;
        out_re[6*os + v] = t313;
        } else {
            const __mmask8 _m = (__mmask8)((1u << rem) - 1u);
        const __m512d t48 = _mm512_set1_pd(0.35689586789221001);
        const __m512d t13 = _mm512_set1_pd(0.55495813208736999);
        const __m512d t52 = _mm512_set1_pd(0.69202147163009997);
        const __m512d t29 = _mm512_set1_pd(0.80193773580483996);
        const __m512d t56 = _mm512_set1_pd(0.90096886790242003);
        const __m512d t45 = _mm512_set1_pd(0.97492791218181996);
        const __m512d t0 = _mm512_maskz_loadu_pd(_m, &in_re[4*is + v]);
        const __m512d t1 = _mm512_set1_pd(tw_im[3]);
        const __m512d t2 = _mm512_maskz_loadu_pd(_m, &in_im[4*is + v]);
        const __m512d t3 = _mm512_set1_pd(tw_re[3]);
        const __m512d t5 = _mm512_fmadd_pd(t0, t1, _mm512_mul_pd(t2, t3));
        const __m512d t4 = _mm512_fnmadd_pd(t2, t1, _mm512_mul_pd(t0, t3));
        const __m512d t6 = _mm512_maskz_loadu_pd(_m, &in_re[3*is + v]);
        const __m512d t7 = _mm512_set1_pd(tw_im[2]);
        const __m512d t8 = _mm512_maskz_loadu_pd(_m, &in_im[3*is + v]);
        const __m512d t9 = _mm512_set1_pd(tw_re[2]);
        const __m512d t11 = _mm512_fmadd_pd(t6, t7, _mm512_mul_pd(t8, t9));
        const __m512d t10 = _mm512_fnmadd_pd(t8, t7, _mm512_mul_pd(t6, t9));
        const __m512d t98 = _mm512_add_pd(t5, t11);
        const __m512d t54 = _mm512_add_pd(t4, t10);
        const __m512d t95 = _mm512_sub_pd(t4, t10);
        const __m512d t12 = _mm512_sub_pd(t11, t5);
        const __m512d t15 = _mm512_maskz_loadu_pd(_m, &in_re[6*is + v]);
        const __m512d t16 = _mm512_set1_pd(tw_im[5]);
        const __m512d t17 = _mm512_maskz_loadu_pd(_m, &in_im[6*is + v]);
        const __m512d t18 = _mm512_set1_pd(tw_re[5]);
        const __m512d t20 = _mm512_fmadd_pd(t15, t16, _mm512_mul_pd(t17, t18));
        const __m512d t19 = _mm512_fnmadd_pd(t17, t16, _mm512_mul_pd(t15, t18));
        const __m512d t21 = _mm512_maskz_loadu_pd(_m, &in_re[1*is + v]);
        const __m512d t22 = _mm512_set1_pd(tw_im[0]);
        const __m512d t23 = _mm512_maskz_loadu_pd(_m, &in_im[1*is + v]);
        const __m512d t24 = _mm512_set1_pd(tw_re[0]);
        const __m512d t26 = _mm512_fmadd_pd(t21, t22, _mm512_mul_pd(t23, t24));
        const __m512d t25 = _mm512_fnmadd_pd(t23, t22, _mm512_mul_pd(t21, t24));
        const __m512d t103 = _mm512_add_pd(t20, t26);
        const __m512d t50 = _mm512_add_pd(t19, t25);
        const __m512d t90 = _mm512_sub_pd(t19, t25);
        const __m512d t27 = _mm512_sub_pd(t26, t20);
        const __m512d t31 = _mm512_maskz_loadu_pd(_m, &in_re[5*is + v]);
        const __m512d t32 = _mm512_set1_pd(tw_im[4]);
        const __m512d t33 = _mm512_maskz_loadu_pd(_m, &in_im[5*is + v]);
        const __m512d t34 = _mm512_set1_pd(tw_re[4]);
        const __m512d t36 = _mm512_fmadd_pd(t31, t32, _mm512_mul_pd(t33, t34));
        const __m512d t35 = _mm512_fnmadd_pd(t33, t32, _mm512_mul_pd(t31, t34));
        const __m512d t37 = _mm512_maskz_loadu_pd(_m, &in_re[2*is + v]);
        const __m512d t38 = _mm512_set1_pd(tw_im[1]);
        const __m512d t39 = _mm512_maskz_loadu_pd(_m, &in_im[2*is + v]);
        const __m512d t40 = _mm512_set1_pd(tw_re[1]);
        const __m512d t42 = _mm512_fmadd_pd(t37, t38, _mm512_mul_pd(t39, t40));
        const __m512d t41 = _mm512_fnmadd_pd(t39, t38, _mm512_mul_pd(t37, t40));
        const __m512d t100 = _mm512_add_pd(t36, t42);
        const __m512d t47 = _mm512_add_pd(t35, t41);
        const __m512d t92 = _mm512_sub_pd(t35, t41);
        const __m512d t43 = _mm512_sub_pd(t42, t36);
        const __m512d t268 = _mm512_fnmadd_pd(t29, _mm512_fnmadd_pd(t13, t90, t92), t95);
        const __m512d t275 = _mm512_fnmadd_pd(t29, _mm512_fmadd_pd(t13, t92, t95), t90);
        const __m512d t283 = _mm512_fmadd_pd(t29, _mm512_fmadd_pd(t13, t95, t90), t92);
        const __m512d t251 = _mm512_fmadd_pd(t29, _mm512_fmadd_pd(t12, t13, t27), t43);
        const __m512d t257 = _mm512_fnmadd_pd(t29, _mm512_fmadd_pd(t13, t43, t12), t27);
        const __m512d t264 = _mm512_fnmadd_pd(t29, _mm512_fnmadd_pd(t13, t27, t43), t12);
        const __m512d t58 = _mm512_maskz_loadu_pd(_m, &in_re[0*is + v]);
        const __m512d t63 = _mm512_add_pd(t54, _mm512_add_pd(t47, _mm512_add_pd(t50, t58)));
        const __m512d t293 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t47, t48, t50), t54), t58);
        const __m512d t294 = _mm512_fnmadd_pd(t45, t251, t293);
        const __m512d t297 = _mm512_fmadd_pd(t45, t251, t293);
        const __m512d t295 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t50, t54), t47), t58);
        const __m512d t296 = _mm512_fnmadd_pd(t45, t257, t295);
        const __m512d t300 = _mm512_fmadd_pd(t45, t257, t295);
        const __m512d t298 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t54, t47), t50), t58);
        const __m512d t299 = _mm512_fnmadd_pd(t45, t264, t298);
        const __m512d t303 = _mm512_fmadd_pd(t45, t264, t298);
        const __m512d t106 = _mm512_maskz_loadu_pd(_m, &in_im[0*is + v]);
        const __m512d t301 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t98, t100), t103), t106);
        const __m512d t302 = _mm512_fmadd_pd(t45, t268, t301);
        const __m512d t304 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t103, t98), t100), t106);
        const __m512d t305 = _mm512_fmadd_pd(t45, t275, t304);
        const __m512d t308 = _mm512_fnmadd_pd(t56, _mm512_fnmadd_pd(t52, _mm512_fnmadd_pd(t48, t100, t103), t98), t106);
        const __m512d t309 = _mm512_fmadd_pd(t45, t283, t308);
        const __m512d t140 = _mm512_add_pd(t98, _mm512_add_pd(t100, _mm512_add_pd(t103, t106)));
        const __m512d t307 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t268, t301), _mm512_set1_pd(-0.0));
        const __m512d t311 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t275, t304), _mm512_set1_pd(-0.0));
        const __m512d t313 = _mm512_xor_pd(_mm512_fnmadd_pd(t45, t283, t308), _mm512_set1_pd(-0.0));

        _mm512_mask_storeu_pd(&out_im[0*os + v], _m, t294);
        _mm512_mask_storeu_pd(&out_re[0*os + v], _m, t63);
        _mm512_mask_storeu_pd(&out_im[1*os + v], _m, t296);
        _mm512_mask_storeu_pd(&out_re[1*os + v], _m, t297);
        _mm512_mask_storeu_pd(&out_im[2*os + v], _m, t299);
        _mm512_mask_storeu_pd(&out_re[2*os + v], _m, t300);
        _mm512_mask_storeu_pd(&out_im[3*os + v], _m, t302);
        _mm512_mask_storeu_pd(&out_re[3*os + v], _m, t303);
        _mm512_mask_storeu_pd(&out_im[4*os + v], _m, t305);
        _mm512_mask_storeu_pd(&out_re[4*os + v], _m, t307);
        _mm512_mask_storeu_pd(&out_im[5*os + v], _m, t309);
        _mm512_mask_storeu_pd(&out_re[5*os + v], _m, t311);
        _mm512_mask_storeu_pd(&out_im[6*os + v], _m, t140);
        _mm512_mask_storeu_pd(&out_re[6*os + v], _m, t313);
        }
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=87  flops=129  (add=12 sub=6 mul=0 fma=42 cmul=12 neg=3)
 *   essential_io=28 ops (vec_loads=14 + stores=14)  [+12 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=0 slots => +0 mem ops, 0 vectors live across pass boundary
 *   memory_floor=28 mem ops   peak_live(max-per-pass)=34   budget=28 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: SPILLS (peak_live > budget)
 */
