/**
 * @file fft_radix8_avx512_il_dif_tw.h
 * @brief DFT-8 AVX512 DIF tw — interleaved + log3
 * Generated by gen_r8_log3.py
 */
#ifndef FFT_RADIX8_AVX512_IL_DIF_TW_H
#define FFT_RADIX8_AVX512_IL_DIF_TW_H
#include <stddef.h>
#include <immintrin.h>

__attribute__((target("avx512f,avx512dq,fma")))
static inline void
radix8_tw_dif_kernel_fwd_il_avx512(
    const double * __restrict__ in,
    double * __restrict__ out,
    const double * __restrict__ tw_re, const double * __restrict__ tw_im,
    size_t K)
{
    const __m512d vc = _mm512_set1_pd(0.707106781186547572737310929369414225220680236816);
    const __m512d vnc = _mm512_set1_pd(-0.707106781186547572737310929369414225220680236816);
    for (size_t k = 0; k < K; k += 8) {
        /* Load 3 base twiddles: W^1, W^2, W^4 */
        const __m512d tw1r = _mm512_load_pd(&tw_re[0*K+k]), tw1i = _mm512_load_pd(&tw_im[0*K+k]);
        const __m512d tw2r = _mm512_load_pd(&tw_re[1*K+k]), tw2i = _mm512_load_pd(&tw_im[1*K+k]);
        const __m512d tw4r = _mm512_load_pd(&tw_re[3*K+k]), tw4i = _mm512_load_pd(&tw_im[3*K+k]);
        /* Derive W^3 = W^1 × W^2 */
        const __m512d tw3r = _mm512_fmsub_pd(tw1r,tw2r,_mm512_mul_pd(tw1i,tw2i));
        const __m512d tw3i = _mm512_fmadd_pd(tw1r,tw2i,_mm512_mul_pd(tw1i,tw2r));
        /* Derive W^5 = W^1 × W^4 */
        const __m512d tw5r = _mm512_fmsub_pd(tw1r,tw4r,_mm512_mul_pd(tw1i,tw4i));
        const __m512d tw5i = _mm512_fmadd_pd(tw1r,tw4i,_mm512_mul_pd(tw1i,tw4r));
        /* Derive W^6 = W^2 × W^4 */
        const __m512d tw6r = _mm512_fmsub_pd(tw2r,tw4r,_mm512_mul_pd(tw2i,tw4i));
        const __m512d tw6i = _mm512_fmadd_pd(tw2r,tw4i,_mm512_mul_pd(tw2i,tw4r));
        /* Derive W^7 = W^3 × W^4 */
        const __m512d tw7r = _mm512_fmsub_pd(tw3r,tw4r,_mm512_mul_pd(tw3i,tw4i));
        const __m512d tw7i = _mm512_fmadd_pd(tw3r,tw4i,_mm512_mul_pd(tw3i,tw4r));
        __m512d x0r, x0i;
        { __m512d _lo = _mm512_load_pd(&in[2*(0*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(0*K+k+4)]);
          x0r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x0i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x1r, x1i;
        { __m512d _lo = _mm512_load_pd(&in[2*(1*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(1*K+k+4)]);
          x1r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x1i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x2r, x2i;
        { __m512d _lo = _mm512_load_pd(&in[2*(2*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(2*K+k+4)]);
          x2r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x2i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x3r, x3i;
        { __m512d _lo = _mm512_load_pd(&in[2*(3*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(3*K+k+4)]);
          x3r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x3i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x4r, x4i;
        { __m512d _lo = _mm512_load_pd(&in[2*(4*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(4*K+k+4)]);
          x4r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x4i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x5r, x5i;
        { __m512d _lo = _mm512_load_pd(&in[2*(5*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(5*K+k+4)]);
          x5r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x5i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x6r, x6i;
        { __m512d _lo = _mm512_load_pd(&in[2*(6*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(6*K+k+4)]);
          x6r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x6i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x7r, x7i;
        { __m512d _lo = _mm512_load_pd(&in[2*(7*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(7*K+k+4)]);
          x7r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x7i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        /* DFT-4 evens */
        const __m512d epr = _mm512_add_pd(x0r,x4r), epi = _mm512_add_pd(x0i,x4i);
        const __m512d eqr = _mm512_sub_pd(x0r,x4r), eqi = _mm512_sub_pd(x0i,x4i);
        const __m512d err = _mm512_add_pd(x2r,x6r), eri = _mm512_add_pd(x2i,x6i);
        const __m512d esr = _mm512_sub_pd(x2r,x6r), esi = _mm512_sub_pd(x2i,x6i);
        const __m512d A0r = _mm512_add_pd(epr,err), A0i = _mm512_add_pd(epi,eri);
        const __m512d A2r = _mm512_sub_pd(epr,err), A2i = _mm512_sub_pd(epi,eri);
        const __m512d A1r = _mm512_add_pd(eqr,esi), A1i = _mm512_sub_pd(eqi,esr);
        const __m512d A3r = _mm512_sub_pd(eqr,esi), A3i = _mm512_add_pd(eqi,esr);
        /* DFT-4 odds */
        const __m512d opr = _mm512_add_pd(x1r,x5r), opi = _mm512_add_pd(x1i,x5i);
        const __m512d oqr = _mm512_sub_pd(x1r,x5r), oqi = _mm512_sub_pd(x1i,x5i);
        const __m512d orr = _mm512_add_pd(x3r,x7r), ori = _mm512_add_pd(x3i,x7i);
        const __m512d osr = _mm512_sub_pd(x3r,x7r), osi = _mm512_sub_pd(x3i,x7i);
        const __m512d B0r = _mm512_add_pd(opr,orr), B0i = _mm512_add_pd(opi,ori);
        const __m512d B2r = _mm512_sub_pd(opr,orr), B2i = _mm512_sub_pd(opi,ori);
        const __m512d B1r = _mm512_add_pd(oqr,osi), B1i = _mm512_sub_pd(oqi,osr);
        const __m512d B3r = _mm512_sub_pd(oqr,osi), B3i = _mm512_add_pd(oqi,osr);
        /* W8 combine into Y vars */
        const __m512d Y0r = _mm512_add_pd(A0r,B0r), Y0i = _mm512_add_pd(A0i,B0i);
        const __m512d Y4r = _mm512_sub_pd(A0r,B0r), Y4i = _mm512_sub_pd(A0i,B0i);
        const __m512d t1r = _mm512_mul_pd(vc,_mm512_add_pd(B1r,B1i)), t1i = _mm512_mul_pd(vc,_mm512_sub_pd(B1i,B1r));
        const __m512d Y1r = _mm512_add_pd(A1r,t1r), Y1i = _mm512_add_pd(A1i,t1i);
        const __m512d Y5r = _mm512_sub_pd(A1r,t1r), Y5i = _mm512_sub_pd(A1i,t1i);
        const __m512d Y2r = _mm512_add_pd(A2r,B2i), Y2i = _mm512_sub_pd(A2i,B2r);
        const __m512d Y6r = _mm512_sub_pd(A2r,B2i), Y6i = _mm512_add_pd(A2i,B2r);
        const __m512d t3r = _mm512_mul_pd(vnc,_mm512_sub_pd(B3r,B3i)), t3i = _mm512_mul_pd(vnc,_mm512_add_pd(B3r,B3i));
        const __m512d Y3r = _mm512_add_pd(A3r,t3r), Y3i = _mm512_add_pd(A3i,t3i);
        const __m512d Y7r = _mm512_sub_pd(A3r,t3r), Y7i = _mm512_sub_pd(A3i,t3i);
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), Y0r);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), Y0i);
          _mm512_store_pd(&out[2*(0*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(0*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        { const __m512d tr = _mm512_fmsub_pd(Y1r,tw1r,_mm512_mul_pd(Y1i,tw1i));
          const __m512d ti = _mm512_fmadd_pd(Y1r,tw1i,_mm512_mul_pd(Y1i,tw1r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(1*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(1*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y2r,tw2r,_mm512_mul_pd(Y2i,tw2i));
          const __m512d ti = _mm512_fmadd_pd(Y2r,tw2i,_mm512_mul_pd(Y2i,tw2r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(2*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(2*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y3r,tw3r,_mm512_mul_pd(Y3i,tw3i));
          const __m512d ti = _mm512_fmadd_pd(Y3r,tw3i,_mm512_mul_pd(Y3i,tw3r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(3*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(3*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y4r,tw4r,_mm512_mul_pd(Y4i,tw4i));
          const __m512d ti = _mm512_fmadd_pd(Y4r,tw4i,_mm512_mul_pd(Y4i,tw4r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(4*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(4*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y5r,tw5r,_mm512_mul_pd(Y5i,tw5i));
          const __m512d ti = _mm512_fmadd_pd(Y5r,tw5i,_mm512_mul_pd(Y5i,tw5r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(5*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(5*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y6r,tw6r,_mm512_mul_pd(Y6i,tw6i));
          const __m512d ti = _mm512_fmadd_pd(Y6r,tw6i,_mm512_mul_pd(Y6i,tw6r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(6*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(6*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmsub_pd(Y7r,tw7r,_mm512_mul_pd(Y7i,tw7i));
          const __m512d ti = _mm512_fmadd_pd(Y7r,tw7i,_mm512_mul_pd(Y7i,tw7r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(7*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(7*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
    }
}

__attribute__((target("avx512f,avx512dq,fma")))
static inline void
radix8_tw_dif_kernel_bwd_il_avx512(
    const double * __restrict__ in,
    double * __restrict__ out,
    const double * __restrict__ tw_re, const double * __restrict__ tw_im,
    size_t K)
{
    const __m512d vc = _mm512_set1_pd(0.707106781186547572737310929369414225220680236816);
    const __m512d vnc = _mm512_set1_pd(-0.707106781186547572737310929369414225220680236816);
    for (size_t k = 0; k < K; k += 8) {
        /* Load 3 base twiddles: W^1, W^2, W^4 */
        const __m512d tw1r = _mm512_load_pd(&tw_re[0*K+k]), tw1i = _mm512_load_pd(&tw_im[0*K+k]);
        const __m512d tw2r = _mm512_load_pd(&tw_re[1*K+k]), tw2i = _mm512_load_pd(&tw_im[1*K+k]);
        const __m512d tw4r = _mm512_load_pd(&tw_re[3*K+k]), tw4i = _mm512_load_pd(&tw_im[3*K+k]);
        /* Derive W^3 = W^1 × W^2 */
        const __m512d tw3r = _mm512_fmsub_pd(tw1r,tw2r,_mm512_mul_pd(tw1i,tw2i));
        const __m512d tw3i = _mm512_fmadd_pd(tw1r,tw2i,_mm512_mul_pd(tw1i,tw2r));
        /* Derive W^5 = W^1 × W^4 */
        const __m512d tw5r = _mm512_fmsub_pd(tw1r,tw4r,_mm512_mul_pd(tw1i,tw4i));
        const __m512d tw5i = _mm512_fmadd_pd(tw1r,tw4i,_mm512_mul_pd(tw1i,tw4r));
        /* Derive W^6 = W^2 × W^4 */
        const __m512d tw6r = _mm512_fmsub_pd(tw2r,tw4r,_mm512_mul_pd(tw2i,tw4i));
        const __m512d tw6i = _mm512_fmadd_pd(tw2r,tw4i,_mm512_mul_pd(tw2i,tw4r));
        /* Derive W^7 = W^3 × W^4 */
        const __m512d tw7r = _mm512_fmsub_pd(tw3r,tw4r,_mm512_mul_pd(tw3i,tw4i));
        const __m512d tw7i = _mm512_fmadd_pd(tw3r,tw4i,_mm512_mul_pd(tw3i,tw4r));
        __m512d x0r, x0i;
        { __m512d _lo = _mm512_load_pd(&in[2*(0*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(0*K+k+4)]);
          x0r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x0i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x1r, x1i;
        { __m512d _lo = _mm512_load_pd(&in[2*(1*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(1*K+k+4)]);
          x1r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x1i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x2r, x2i;
        { __m512d _lo = _mm512_load_pd(&in[2*(2*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(2*K+k+4)]);
          x2r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x2i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x3r, x3i;
        { __m512d _lo = _mm512_load_pd(&in[2*(3*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(3*K+k+4)]);
          x3r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x3i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x4r, x4i;
        { __m512d _lo = _mm512_load_pd(&in[2*(4*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(4*K+k+4)]);
          x4r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x4i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x5r, x5i;
        { __m512d _lo = _mm512_load_pd(&in[2*(5*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(5*K+k+4)]);
          x5r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x5i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x6r, x6i;
        { __m512d _lo = _mm512_load_pd(&in[2*(6*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(6*K+k+4)]);
          x6r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x6i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        __m512d x7r, x7i;
        { __m512d _lo = _mm512_load_pd(&in[2*(7*K+k)]);
          __m512d _hi = _mm512_load_pd(&in[2*(7*K+k+4)]);
          x7r = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpacklo_pd(_lo,_hi));
          x7i = _mm512_permutexvar_pd(_mm512_set_epi64(7,5,3,1,6,4,2,0), _mm512_unpackhi_pd(_lo,_hi)); }
        /* DFT-4 evens */
        const __m512d epr = _mm512_add_pd(x0r,x4r), epi = _mm512_add_pd(x0i,x4i);
        const __m512d eqr = _mm512_sub_pd(x0r,x4r), eqi = _mm512_sub_pd(x0i,x4i);
        const __m512d err = _mm512_add_pd(x2r,x6r), eri = _mm512_add_pd(x2i,x6i);
        const __m512d esr = _mm512_sub_pd(x2r,x6r), esi = _mm512_sub_pd(x2i,x6i);
        const __m512d A0r = _mm512_add_pd(epr,err), A0i = _mm512_add_pd(epi,eri);
        const __m512d A2r = _mm512_sub_pd(epr,err), A2i = _mm512_sub_pd(epi,eri);
        const __m512d A1r = _mm512_sub_pd(eqr,esi), A1i = _mm512_add_pd(eqi,esr);
        const __m512d A3r = _mm512_add_pd(eqr,esi), A3i = _mm512_sub_pd(eqi,esr);
        /* DFT-4 odds */
        const __m512d opr = _mm512_add_pd(x1r,x5r), opi = _mm512_add_pd(x1i,x5i);
        const __m512d oqr = _mm512_sub_pd(x1r,x5r), oqi = _mm512_sub_pd(x1i,x5i);
        const __m512d orr = _mm512_add_pd(x3r,x7r), ori = _mm512_add_pd(x3i,x7i);
        const __m512d osr = _mm512_sub_pd(x3r,x7r), osi = _mm512_sub_pd(x3i,x7i);
        const __m512d B0r = _mm512_add_pd(opr,orr), B0i = _mm512_add_pd(opi,ori);
        const __m512d B2r = _mm512_sub_pd(opr,orr), B2i = _mm512_sub_pd(opi,ori);
        const __m512d B1r = _mm512_sub_pd(oqr,osi), B1i = _mm512_add_pd(oqi,osr);
        const __m512d B3r = _mm512_add_pd(oqr,osi), B3i = _mm512_sub_pd(oqi,osr);
        /* W8 combine into Y vars */
        const __m512d Y0r = _mm512_add_pd(A0r,B0r), Y0i = _mm512_add_pd(A0i,B0i);
        const __m512d Y4r = _mm512_sub_pd(A0r,B0r), Y4i = _mm512_sub_pd(A0i,B0i);
        const __m512d t1r = _mm512_mul_pd(vc,_mm512_sub_pd(B1r,B1i)), t1i = _mm512_mul_pd(vc,_mm512_add_pd(B1r,B1i));
        const __m512d Y1r = _mm512_add_pd(A1r,t1r), Y1i = _mm512_add_pd(A1i,t1i);
        const __m512d Y5r = _mm512_sub_pd(A1r,t1r), Y5i = _mm512_sub_pd(A1i,t1i);
        const __m512d Y2r = _mm512_sub_pd(A2r,B2i), Y2i = _mm512_add_pd(A2i,B2r);
        const __m512d Y6r = _mm512_add_pd(A2r,B2i), Y6i = _mm512_sub_pd(A2i,B2r);
        const __m512d t3r = _mm512_mul_pd(vnc,_mm512_add_pd(B3r,B3i)), t3i = _mm512_mul_pd(vc,_mm512_sub_pd(B3r,B3i));
        const __m512d Y3r = _mm512_add_pd(A3r,t3r), Y3i = _mm512_add_pd(A3i,t3i);
        const __m512d Y7r = _mm512_sub_pd(A3r,t3r), Y7i = _mm512_sub_pd(A3i,t3i);
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), Y0r);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), Y0i);
          _mm512_store_pd(&out[2*(0*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(0*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        { const __m512d tr = _mm512_fmadd_pd(Y1r,tw1r,_mm512_mul_pd(Y1i,tw1i));
          const __m512d ti = _mm512_fnmadd_pd(Y1r,tw1i,_mm512_mul_pd(Y1i,tw1r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(1*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(1*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y2r,tw2r,_mm512_mul_pd(Y2i,tw2i));
          const __m512d ti = _mm512_fnmadd_pd(Y2r,tw2i,_mm512_mul_pd(Y2i,tw2r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(2*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(2*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y3r,tw3r,_mm512_mul_pd(Y3i,tw3i));
          const __m512d ti = _mm512_fnmadd_pd(Y3r,tw3i,_mm512_mul_pd(Y3i,tw3r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(3*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(3*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y4r,tw4r,_mm512_mul_pd(Y4i,tw4i));
          const __m512d ti = _mm512_fnmadd_pd(Y4r,tw4i,_mm512_mul_pd(Y4i,tw4r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(4*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(4*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y5r,tw5r,_mm512_mul_pd(Y5i,tw5i));
          const __m512d ti = _mm512_fnmadd_pd(Y5r,tw5i,_mm512_mul_pd(Y5i,tw5r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(5*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(5*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y6r,tw6r,_mm512_mul_pd(Y6i,tw6i));
          const __m512d ti = _mm512_fnmadd_pd(Y6r,tw6i,_mm512_mul_pd(Y6i,tw6r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(6*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(6*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
        { const __m512d tr = _mm512_fmadd_pd(Y7r,tw7r,_mm512_mul_pd(Y7i,tw7i));
          const __m512d ti = _mm512_fnmadd_pd(Y7r,tw7i,_mm512_mul_pd(Y7i,tw7r));
        { __m512d _rp = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), tr);
          __m512d _ip = _mm512_permutexvar_pd(_mm512_set_epi64(7,3,6,2,5,1,4,0), ti);
          _mm512_store_pd(&out[2*(7*K+k)], _mm512_unpacklo_pd(_rp,_ip));
          _mm512_store_pd(&out[2*(7*K+k+4)], _mm512_unpackhi_pd(_rp,_ip)); }
        }
    }
}

#endif /* FFT_RADIX8_AVX512_IL_DIF_TW_H */
