/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 8 --cil-t2csgt --cil-bwd --isa avx512 --uarch sapphire_rapids_avx512 --emit-c
 * Env overrides: (none)
 * Family: full-IL (interleaved-complex) t2, radix-8 bwd
 * ISA: avx512; 4 complex per vector
 * Uarch: sapphire_rapids_avx512
 * Form: blocked=false split=- turnst=false turnst_gs=false pretw=false log3=false             tangent=false
 * ====================================================== */
/* Auto-generated by vfft_v2 — INTERLEAVED-COMPLEX (full-IL) family,
 * PIPELINE-HOSTED (codelet_cil.ml; docs/roadmap/zil_pipeline_port.md §11).
 * radix-8 bailey2 stage-2 mid t2 (streamed VTW2 twiddles, BYTW2 apply): 4 complex per 512-bit vector. Body scheduled by the
 * SHARED SR scheduler (Schedule.Make over the complex IR) and rendered
 * through the ISA layer, so the same source emits AVX2 / AVX-512.
 * tw_re = VTW2 records, cos-first and sign-folded: per column-group, per
 * leg 1..R-1, one 16-double record [c x8][-s,+s ...]. Cursor advances
 * 112 doubles per group; BYTW2 = fmadd(c, x, mul(s, cflip x)) — ONE
 * data-side shuffle, zero table-side work. tw_im unused.
 * count: ANY >= 1 — 4 columns per wide iteration, inline VEX-128
 * odd-count tail for the leftover (il_odd_count_tail.md §3). */
#include <immintrin.h>
#include <stddef.h>

static const __m512d _M_RE = { -0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0.0 };  /* negate re lanes: x*(+i) */
static const __m128d _M_RE_n = { -0.0, 0.0 };  /* tail twin */
static const __m256d _M_RE_y = { -0.0, 0.0, -0.0, 0.0 };  /* ymm tail twin */

__attribute__((target("avx512f,avx512dq,avx512vl,fma")))
void radix8_z_t2csgt_bwd_avx512(
    const double * __restrict__ zin,
    const double * __restrict__ zin_unused,
    double       * __restrict__ zout,
    double       * __restrict__ zout_unused,
    const double * tw_re, const double * tw_im,
    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)
{
    (void)zin_unused; (void)zout_unused; (void)tw_im; (void)Gs; (void)OGs;
    const __m512d _wgc = _mm512_loadu_pd(&tw_im[0]);
    const __m512d _wgs = _mm512_loadu_pd(&tw_im[8]);
    size_t k = 0;
    for (; k + 4 <= count; k += 4) {
        const double *twp = tw_re + (k / 4) * (size_t)16;
        const __m512d _t1c = _mm512_loadu_pd(&twp[0]);
        const __m512d _t1s = _mm512_loadu_pd(&twp[8]);
        const __m512d _wc1 = _mm512_fnmadd_pd(_t1s, _wgs, _mm512_mul_pd(_t1c, _wgc));
        const __m512d _ws1 = _mm512_fmadd_pd(_t1c, _wgs, _mm512_mul_pd(_t1s, _wgc));
        const __m512d _wc2 = _mm512_fnmadd_pd(_ws1, _ws1, _mm512_mul_pd(_wc1, _wc1));
        const __m512d _ws2 = _mm512_fmadd_pd(_wc1, _ws1, _mm512_mul_pd(_ws1, _wc1));
        const __m512d _wc3 = _mm512_fnmadd_pd(_ws2, _ws1, _mm512_mul_pd(_wc2, _wc1));
        const __m512d _ws3 = _mm512_fmadd_pd(_wc2, _ws1, _mm512_mul_pd(_ws2, _wc1));
        const __m512d _wc4 = _mm512_fnmadd_pd(_ws2, _ws2, _mm512_mul_pd(_wc2, _wc2));
        const __m512d _ws4 = _mm512_fmadd_pd(_wc2, _ws2, _mm512_mul_pd(_ws2, _wc2));
        const __m512d _wc5 = _mm512_fnmadd_pd(_ws4, _ws1, _mm512_mul_pd(_wc4, _wc1));
        const __m512d _ws5 = _mm512_fmadd_pd(_wc4, _ws1, _mm512_mul_pd(_ws4, _wc1));
        const __m512d _wc6 = _mm512_fnmadd_pd(_ws4, _ws2, _mm512_mul_pd(_wc4, _wc2));
        const __m512d _ws6 = _mm512_fmadd_pd(_wc4, _ws2, _mm512_mul_pd(_ws4, _wc2));
        const __m512d _wc7 = _mm512_fnmadd_pd(_ws4, _ws3, _mm512_mul_pd(_wc4, _wc3));
        const __m512d _ws7 = _mm512_fmadd_pd(_wc4, _ws3, _mm512_mul_pd(_ws4, _wc3));
        /* gen2: W^1 = T1[pair] x T2, 6 legs derived */
        const __m512d z0 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)0*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)0*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)0*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)0*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z1 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)1*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)1*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)1*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)1*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z2 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)2*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)2*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)2*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)2*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z3 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)3*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)3*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)3*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)3*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z4 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)4*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)4*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)4*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)4*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z5 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)5*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)5*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)5*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)5*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z6 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)6*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)6*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)6*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)6*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z7 = _mm512_insertf64x4(_mm512_castpd256_pd512(_mm256_loadu2_m128d(&zin[2*((size_t)7*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)7*Ls + (size_t)k*Gs)])), _mm256_loadu2_m128d(&zin[2*((size_t)7*Ls + ((size_t)k + 3)*Gs)], &zin[2*((size_t)7*Ls + ((size_t)k + 2)*Gs)]), 1);
        const __m512d z8 = _mm512_sub_pd(z0, z4);
        const __m512d z9 = _mm512_add_pd(z0, z4);
        const __m512d z17 = _mm512_sub_pd(z1, z5);
        const __m512d z18 = _mm512_add_pd(z1, z5);
        const __m512d z10 = _mm512_sub_pd(z2, z6);
        const __m512d z11 = _mm512_add_pd(z2, z6);
        const __m512d z14 = _mm512_xor_pd(_mm512_permute_pd(z10, 0x55), _M_RE);
        const __m512d z12 = _mm512_sub_pd(z9, z11);
        const __m512d z13 = _mm512_add_pd(z9, z11);
        const __m512d z15 = _mm512_sub_pd(z8, z14);
        const __m512d z16 = _mm512_add_pd(z8, z14);
        const __m512d z19 = _mm512_sub_pd(z3, z7);
        const __m512d z23 = _mm512_xor_pd(_mm512_permute_pd(z19, 0x55), _M_RE);
        const __m512d z20 = _mm512_add_pd(z3, z7);
        const __m512d z24 = _mm512_sub_pd(z17, z23);
        const __m512d z25 = _mm512_add_pd(z17, z23);
        const __m512d z21 = _mm512_sub_pd(z18, z20);
        const __m512d z28 = _mm512_xor_pd(_mm512_permute_pd(z25, 0x55), _M_RE);
        const __m512d z35 = _mm512_xor_pd(_mm512_permute_pd(z24, 0x55), _M_RE);
        const __m512d z22 = _mm512_add_pd(z18, z20);
        const __m512d z27 = _mm512_add_pd(z13, z22);
        const __m512d z32 = _mm512_xor_pd(_mm512_permute_pd(z21, 0x55), _M_RE);
        const __m512d z29 = _mm512_add_pd(z25, z28);
        const __m512d z36 = _mm512_sub_pd(z35, z24);
        const __m512d z26 = _mm512_sub_pd(z13, z22);
        const __m512d z42 = _mm512_fmadd_pd(_wc4, z26, _mm512_mul_pd(_ws4, _mm512_permute_pd(z26, 0x55)));
        const __m512d z30 = _mm512_fnmadd_pd(_mm512_set1_pd(0.70710678118654757), z29, z16);
        const __m512d z43 = _mm512_fmadd_pd(_wc5, z30, _mm512_mul_pd(_ws5, _mm512_permute_pd(z30, 0x55)));
        const __m512d z31 = _mm512_fmadd_pd(_mm512_set1_pd(0.70710678118654757), z29, z16);
        const __m512d z39 = _mm512_fmadd_pd(_wc1, z31, _mm512_mul_pd(_ws1, _mm512_permute_pd(z31, 0x55)));
        const __m512d z33 = _mm512_sub_pd(z12, z32);
        const __m512d z44 = _mm512_fmadd_pd(_wc6, z33, _mm512_mul_pd(_ws6, _mm512_permute_pd(z33, 0x55)));
        const __m512d z34 = _mm512_add_pd(z12, z32);
        const __m512d z40 = _mm512_fmadd_pd(_wc2, z34, _mm512_mul_pd(_ws2, _mm512_permute_pd(z34, 0x55)));
        const __m512d z37 = _mm512_fnmadd_pd(_mm512_set1_pd(0.70710678118654757), z36, z15);
        const __m512d z45 = _mm512_fmadd_pd(_wc7, z37, _mm512_mul_pd(_ws7, _mm512_permute_pd(z37, 0x55)));
        const __m512d z38 = _mm512_fmadd_pd(_mm512_set1_pd(0.70710678118654757), z36, z15);
        const __m512d z41 = _mm512_fmadd_pd(_wc3, z38, _mm512_mul_pd(_ws3, _mm512_permute_pd(z38, 0x55)));
        { const __m512d _cv = z27; _mm256_storeu2_m128d(&zout[2*((size_t)0*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)0*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)0*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)0*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z39; _mm256_storeu2_m128d(&zout[2*((size_t)1*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)1*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)1*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)1*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z40; _mm256_storeu2_m128d(&zout[2*((size_t)2*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)2*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)2*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)2*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z41; _mm256_storeu2_m128d(&zout[2*((size_t)3*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)3*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)3*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)3*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z42; _mm256_storeu2_m128d(&zout[2*((size_t)4*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)4*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)4*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)4*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z43; _mm256_storeu2_m128d(&zout[2*((size_t)5*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)5*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)5*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)5*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z44; _mm256_storeu2_m128d(&zout[2*((size_t)6*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)6*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)6*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)6*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
        { const __m512d _cv = z45; _mm256_storeu2_m128d(&zout[2*((size_t)7*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)7*OLs + (size_t)k*OGs)], _mm512_castpd512_pd256(_cv)); _mm256_storeu2_m128d(&zout[2*((size_t)7*OLs + ((size_t)k + 3)*OGs)], &zout[2*((size_t)7*OLs + ((size_t)k + 2)*OGs)], _mm512_extractf64x4_pd(_cv, 1)); };
    }
    const __m256d _wgc_y = _mm256_loadu_pd(&tw_im[0]);
    const __m256d _wgs_y = _mm256_loadu_pd(&tw_im[8]);
    const __m128d _wgc_n = _mm_loadu_pd(&tw_im[0]);
    const __m128d _wgs_n = _mm_loadu_pd(&tw_im[8]);
    if (count - k == 3) {  /* 3 leftover complex: ONE k-masked zmm pass (policy.h L10) */
        const __mmask8 _tm = (__mmask8)((1u << (2u * (unsigned)(count - k))) - 1u);
        const double *twp = tw_re + (k / 4) * (size_t)16;
        const __m512d _t1c = _mm512_maskz_loadu_pd(_tm, &twp[0]);
        const __m512d _t1s = _mm512_maskz_loadu_pd(_tm, &twp[8]);
        const __m512d _wc1 = _mm512_fnmadd_pd(_t1s, _wgs, _mm512_mul_pd(_t1c, _wgc));
        const __m512d _ws1 = _mm512_fmadd_pd(_t1c, _wgs, _mm512_mul_pd(_t1s, _wgc));
        const __m512d _wc2 = _mm512_fnmadd_pd(_ws1, _ws1, _mm512_mul_pd(_wc1, _wc1));
        const __m512d _ws2 = _mm512_fmadd_pd(_wc1, _ws1, _mm512_mul_pd(_ws1, _wc1));
        const __m512d _wc3 = _mm512_fnmadd_pd(_ws2, _ws1, _mm512_mul_pd(_wc2, _wc1));
        const __m512d _ws3 = _mm512_fmadd_pd(_wc2, _ws1, _mm512_mul_pd(_ws2, _wc1));
        const __m512d _wc4 = _mm512_fnmadd_pd(_ws2, _ws2, _mm512_mul_pd(_wc2, _wc2));
        const __m512d _ws4 = _mm512_fmadd_pd(_wc2, _ws2, _mm512_mul_pd(_ws2, _wc2));
        const __m512d _wc5 = _mm512_fnmadd_pd(_ws4, _ws1, _mm512_mul_pd(_wc4, _wc1));
        const __m512d _ws5 = _mm512_fmadd_pd(_wc4, _ws1, _mm512_mul_pd(_ws4, _wc1));
        const __m512d _wc6 = _mm512_fnmadd_pd(_ws4, _ws2, _mm512_mul_pd(_wc4, _wc2));
        const __m512d _ws6 = _mm512_fmadd_pd(_wc4, _ws2, _mm512_mul_pd(_ws4, _wc2));
        const __m512d _wc7 = _mm512_fnmadd_pd(_ws4, _ws3, _mm512_mul_pd(_wc4, _wc3));
        const __m512d _ws7 = _mm512_fmadd_pd(_wc4, _ws3, _mm512_mul_pd(_ws4, _wc3));
        /* gen2: W^1 = T1[pair] x T2, 6 legs derived */
        const __m512d z0 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)0*Ls + (size_t)k*Gs)]);
        const __m512d z1 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)1*Ls + (size_t)k*Gs)]);
        const __m512d z2 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)2*Ls + (size_t)k*Gs)]);
        const __m512d z3 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)3*Ls + (size_t)k*Gs)]);
        const __m512d z4 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)4*Ls + (size_t)k*Gs)]);
        const __m512d z5 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)5*Ls + (size_t)k*Gs)]);
        const __m512d z6 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)6*Ls + (size_t)k*Gs)]);
        const __m512d z7 = _mm512_maskz_loadu_pd(_tm, &zin[2*((size_t)7*Ls + (size_t)k*Gs)]);
        const __m512d z8 = _mm512_sub_pd(z0, z4);
        const __m512d z9 = _mm512_add_pd(z0, z4);
        const __m512d z17 = _mm512_sub_pd(z1, z5);
        const __m512d z18 = _mm512_add_pd(z1, z5);
        const __m512d z10 = _mm512_sub_pd(z2, z6);
        const __m512d z11 = _mm512_add_pd(z2, z6);
        const __m512d z14 = _mm512_xor_pd(_mm512_permute_pd(z10, 0x55), _M_RE);
        const __m512d z12 = _mm512_sub_pd(z9, z11);
        const __m512d z13 = _mm512_add_pd(z9, z11);
        const __m512d z15 = _mm512_sub_pd(z8, z14);
        const __m512d z16 = _mm512_add_pd(z8, z14);
        const __m512d z19 = _mm512_sub_pd(z3, z7);
        const __m512d z23 = _mm512_xor_pd(_mm512_permute_pd(z19, 0x55), _M_RE);
        const __m512d z20 = _mm512_add_pd(z3, z7);
        const __m512d z24 = _mm512_sub_pd(z17, z23);
        const __m512d z25 = _mm512_add_pd(z17, z23);
        const __m512d z21 = _mm512_sub_pd(z18, z20);
        const __m512d z28 = _mm512_xor_pd(_mm512_permute_pd(z25, 0x55), _M_RE);
        const __m512d z35 = _mm512_xor_pd(_mm512_permute_pd(z24, 0x55), _M_RE);
        const __m512d z22 = _mm512_add_pd(z18, z20);
        const __m512d z27 = _mm512_add_pd(z13, z22);
        const __m512d z32 = _mm512_xor_pd(_mm512_permute_pd(z21, 0x55), _M_RE);
        const __m512d z29 = _mm512_add_pd(z25, z28);
        const __m512d z36 = _mm512_sub_pd(z35, z24);
        const __m512d z26 = _mm512_sub_pd(z13, z22);
        const __m512d z42 = _mm512_fmadd_pd(_wc4, z26, _mm512_mul_pd(_ws4, _mm512_permute_pd(z26, 0x55)));
        const __m512d z30 = _mm512_fnmadd_pd(_mm512_set1_pd(0.70710678118654757), z29, z16);
        const __m512d z43 = _mm512_fmadd_pd(_wc5, z30, _mm512_mul_pd(_ws5, _mm512_permute_pd(z30, 0x55)));
        const __m512d z31 = _mm512_fmadd_pd(_mm512_set1_pd(0.70710678118654757), z29, z16);
        const __m512d z39 = _mm512_fmadd_pd(_wc1, z31, _mm512_mul_pd(_ws1, _mm512_permute_pd(z31, 0x55)));
        const __m512d z33 = _mm512_sub_pd(z12, z32);
        const __m512d z44 = _mm512_fmadd_pd(_wc6, z33, _mm512_mul_pd(_ws6, _mm512_permute_pd(z33, 0x55)));
        const __m512d z34 = _mm512_add_pd(z12, z32);
        const __m512d z40 = _mm512_fmadd_pd(_wc2, z34, _mm512_mul_pd(_ws2, _mm512_permute_pd(z34, 0x55)));
        const __m512d z37 = _mm512_fnmadd_pd(_mm512_set1_pd(0.70710678118654757), z36, z15);
        const __m512d z45 = _mm512_fmadd_pd(_wc7, z37, _mm512_mul_pd(_ws7, _mm512_permute_pd(z37, 0x55)));
        const __m512d z38 = _mm512_fmadd_pd(_mm512_set1_pd(0.70710678118654757), z36, z15);
        const __m512d z41 = _mm512_fmadd_pd(_wc3, z38, _mm512_mul_pd(_ws3, _mm512_permute_pd(z38, 0x55)));
        _mm512_mask_storeu_pd(&zout[2*((size_t)0*OLs + (size_t)k*OGs)], _tm, z27);
        _mm512_mask_storeu_pd(&zout[2*((size_t)1*OLs + (size_t)k*OGs)], _tm, z39);
        _mm512_mask_storeu_pd(&zout[2*((size_t)2*OLs + (size_t)k*OGs)], _tm, z40);
        _mm512_mask_storeu_pd(&zout[2*((size_t)3*OLs + (size_t)k*OGs)], _tm, z41);
        _mm512_mask_storeu_pd(&zout[2*((size_t)4*OLs + (size_t)k*OGs)], _tm, z42);
        _mm512_mask_storeu_pd(&zout[2*((size_t)5*OLs + (size_t)k*OGs)], _tm, z43);
        _mm512_mask_storeu_pd(&zout[2*((size_t)6*OLs + (size_t)k*OGs)], _tm, z44);
        _mm512_mask_storeu_pd(&zout[2*((size_t)7*OLs + (size_t)k*OGs)], _tm, z45);
        k = count;
    }
    if (k + 2 <= count) {  /* ladder: ymm pass, 2 complex */
        const double *twp = tw_re + (k / 4) * (size_t)16 + 2 * (k % 4);
        const __m256d _t1c_y = _mm256_loadu_pd(&twp[0]);
        const __m256d _t1s_y = _mm256_loadu_pd(&twp[8]);
        const __m256d _wc1_y = _mm256_fnmadd_pd(_t1s_y, _wgs_y, _mm256_mul_pd(_t1c_y, _wgc_y));
        const __m256d _ws1_y = _mm256_fmadd_pd(_t1c_y, _wgs_y, _mm256_mul_pd(_t1s_y, _wgc_y));
        const __m256d _wc2_y = _mm256_fnmadd_pd(_ws1_y, _ws1_y, _mm256_mul_pd(_wc1_y, _wc1_y));
        const __m256d _ws2_y = _mm256_fmadd_pd(_wc1_y, _ws1_y, _mm256_mul_pd(_ws1_y, _wc1_y));
        const __m256d _wc3_y = _mm256_fnmadd_pd(_ws2_y, _ws1_y, _mm256_mul_pd(_wc2_y, _wc1_y));
        const __m256d _ws3_y = _mm256_fmadd_pd(_wc2_y, _ws1_y, _mm256_mul_pd(_ws2_y, _wc1_y));
        const __m256d _wc4_y = _mm256_fnmadd_pd(_ws2_y, _ws2_y, _mm256_mul_pd(_wc2_y, _wc2_y));
        const __m256d _ws4_y = _mm256_fmadd_pd(_wc2_y, _ws2_y, _mm256_mul_pd(_ws2_y, _wc2_y));
        const __m256d _wc5_y = _mm256_fnmadd_pd(_ws4_y, _ws1_y, _mm256_mul_pd(_wc4_y, _wc1_y));
        const __m256d _ws5_y = _mm256_fmadd_pd(_wc4_y, _ws1_y, _mm256_mul_pd(_ws4_y, _wc1_y));
        const __m256d _wc6_y = _mm256_fnmadd_pd(_ws4_y, _ws2_y, _mm256_mul_pd(_wc4_y, _wc2_y));
        const __m256d _ws6_y = _mm256_fmadd_pd(_wc4_y, _ws2_y, _mm256_mul_pd(_ws4_y, _wc2_y));
        const __m256d _wc7_y = _mm256_fnmadd_pd(_ws4_y, _ws3_y, _mm256_mul_pd(_wc4_y, _wc3_y));
        const __m256d _ws7_y = _mm256_fmadd_pd(_wc4_y, _ws3_y, _mm256_mul_pd(_ws4_y, _wc3_y));
        /* gen2: W^1 = T1[pair] x T2, 6 legs derived */
        const __m256d z0 = _mm256_loadu2_m128d(&zin[2*((size_t)0*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)0*Ls + (size_t)k*Gs)]);
        const __m256d z1 = _mm256_loadu2_m128d(&zin[2*((size_t)1*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)1*Ls + (size_t)k*Gs)]);
        const __m256d z2 = _mm256_loadu2_m128d(&zin[2*((size_t)2*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)2*Ls + (size_t)k*Gs)]);
        const __m256d z3 = _mm256_loadu2_m128d(&zin[2*((size_t)3*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)3*Ls + (size_t)k*Gs)]);
        const __m256d z4 = _mm256_loadu2_m128d(&zin[2*((size_t)4*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)4*Ls + (size_t)k*Gs)]);
        const __m256d z5 = _mm256_loadu2_m128d(&zin[2*((size_t)5*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)5*Ls + (size_t)k*Gs)]);
        const __m256d z6 = _mm256_loadu2_m128d(&zin[2*((size_t)6*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)6*Ls + (size_t)k*Gs)]);
        const __m256d z7 = _mm256_loadu2_m128d(&zin[2*((size_t)7*Ls + ((size_t)k + 1)*Gs)], &zin[2*((size_t)7*Ls + (size_t)k*Gs)]);
        const __m256d z8 = _mm256_sub_pd(z0, z4);
        const __m256d z9 = _mm256_add_pd(z0, z4);
        const __m256d z17 = _mm256_sub_pd(z1, z5);
        const __m256d z18 = _mm256_add_pd(z1, z5);
        const __m256d z10 = _mm256_sub_pd(z2, z6);
        const __m256d z11 = _mm256_add_pd(z2, z6);
        const __m256d z14 = _mm256_xor_pd(_mm256_permute_pd(z10, 0x5), _M_RE_y);
        const __m256d z12 = _mm256_sub_pd(z9, z11);
        const __m256d z13 = _mm256_add_pd(z9, z11);
        const __m256d z15 = _mm256_sub_pd(z8, z14);
        const __m256d z16 = _mm256_add_pd(z8, z14);
        const __m256d z19 = _mm256_sub_pd(z3, z7);
        const __m256d z23 = _mm256_xor_pd(_mm256_permute_pd(z19, 0x5), _M_RE_y);
        const __m256d z20 = _mm256_add_pd(z3, z7);
        const __m256d z24 = _mm256_sub_pd(z17, z23);
        const __m256d z25 = _mm256_add_pd(z17, z23);
        const __m256d z21 = _mm256_sub_pd(z18, z20);
        const __m256d z28 = _mm256_xor_pd(_mm256_permute_pd(z25, 0x5), _M_RE_y);
        const __m256d z35 = _mm256_xor_pd(_mm256_permute_pd(z24, 0x5), _M_RE_y);
        const __m256d z22 = _mm256_add_pd(z18, z20);
        const __m256d z27 = _mm256_add_pd(z13, z22);
        const __m256d z32 = _mm256_xor_pd(_mm256_permute_pd(z21, 0x5), _M_RE_y);
        const __m256d z29 = _mm256_add_pd(z25, z28);
        const __m256d z36 = _mm256_sub_pd(z35, z24);
        const __m256d z26 = _mm256_sub_pd(z13, z22);
        const __m256d z42 = _mm256_fmadd_pd(_wc4_y, z26, _mm256_mul_pd(_ws4_y, _mm256_permute_pd(z26, 0x5)));
        const __m256d z30 = _mm256_fnmadd_pd(_mm256_set1_pd(0.70710678118654757), z29, z16);
        const __m256d z43 = _mm256_fmadd_pd(_wc5_y, z30, _mm256_mul_pd(_ws5_y, _mm256_permute_pd(z30, 0x5)));
        const __m256d z31 = _mm256_fmadd_pd(_mm256_set1_pd(0.70710678118654757), z29, z16);
        const __m256d z39 = _mm256_fmadd_pd(_wc1_y, z31, _mm256_mul_pd(_ws1_y, _mm256_permute_pd(z31, 0x5)));
        const __m256d z33 = _mm256_sub_pd(z12, z32);
        const __m256d z44 = _mm256_fmadd_pd(_wc6_y, z33, _mm256_mul_pd(_ws6_y, _mm256_permute_pd(z33, 0x5)));
        const __m256d z34 = _mm256_add_pd(z12, z32);
        const __m256d z40 = _mm256_fmadd_pd(_wc2_y, z34, _mm256_mul_pd(_ws2_y, _mm256_permute_pd(z34, 0x5)));
        const __m256d z37 = _mm256_fnmadd_pd(_mm256_set1_pd(0.70710678118654757), z36, z15);
        const __m256d z45 = _mm256_fmadd_pd(_wc7_y, z37, _mm256_mul_pd(_ws7_y, _mm256_permute_pd(z37, 0x5)));
        const __m256d z38 = _mm256_fmadd_pd(_mm256_set1_pd(0.70710678118654757), z36, z15);
        const __m256d z41 = _mm256_fmadd_pd(_wc3_y, z38, _mm256_mul_pd(_ws3_y, _mm256_permute_pd(z38, 0x5)));
        _mm256_storeu2_m128d(&zout[2*((size_t)0*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)0*OLs + (size_t)k*OGs)], z27);
        _mm256_storeu2_m128d(&zout[2*((size_t)1*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)1*OLs + (size_t)k*OGs)], z39);
        _mm256_storeu2_m128d(&zout[2*((size_t)2*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)2*OLs + (size_t)k*OGs)], z40);
        _mm256_storeu2_m128d(&zout[2*((size_t)3*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)3*OLs + (size_t)k*OGs)], z41);
        _mm256_storeu2_m128d(&zout[2*((size_t)4*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)4*OLs + (size_t)k*OGs)], z42);
        _mm256_storeu2_m128d(&zout[2*((size_t)5*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)5*OLs + (size_t)k*OGs)], z43);
        _mm256_storeu2_m128d(&zout[2*((size_t)6*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)6*OLs + (size_t)k*OGs)], z44);
        _mm256_storeu2_m128d(&zout[2*((size_t)7*OLs + ((size_t)k + 1)*OGs)], &zout[2*((size_t)7*OLs + (size_t)k*OGs)], z45);
        k += 2;
    }
    if (k < count) {  /* ladder: xmm pass, 1 complex */
        const double *twp = tw_re + (k / 4) * (size_t)16 + 2 * (k % 4);
        const __m128d _t1c_n = _mm_loadu_pd(&twp[0]);
        const __m128d _t1s_n = _mm_loadu_pd(&twp[8]);
        const __m128d _wc1_n = _mm_fnmadd_pd(_t1s_n, _wgs_n, _mm_mul_pd(_t1c_n, _wgc_n));
        const __m128d _ws1_n = _mm_fmadd_pd(_t1c_n, _wgs_n, _mm_mul_pd(_t1s_n, _wgc_n));
        const __m128d _wc2_n = _mm_fnmadd_pd(_ws1_n, _ws1_n, _mm_mul_pd(_wc1_n, _wc1_n));
        const __m128d _ws2_n = _mm_fmadd_pd(_wc1_n, _ws1_n, _mm_mul_pd(_ws1_n, _wc1_n));
        const __m128d _wc3_n = _mm_fnmadd_pd(_ws2_n, _ws1_n, _mm_mul_pd(_wc2_n, _wc1_n));
        const __m128d _ws3_n = _mm_fmadd_pd(_wc2_n, _ws1_n, _mm_mul_pd(_ws2_n, _wc1_n));
        const __m128d _wc4_n = _mm_fnmadd_pd(_ws2_n, _ws2_n, _mm_mul_pd(_wc2_n, _wc2_n));
        const __m128d _ws4_n = _mm_fmadd_pd(_wc2_n, _ws2_n, _mm_mul_pd(_ws2_n, _wc2_n));
        const __m128d _wc5_n = _mm_fnmadd_pd(_ws4_n, _ws1_n, _mm_mul_pd(_wc4_n, _wc1_n));
        const __m128d _ws5_n = _mm_fmadd_pd(_wc4_n, _ws1_n, _mm_mul_pd(_ws4_n, _wc1_n));
        const __m128d _wc6_n = _mm_fnmadd_pd(_ws4_n, _ws2_n, _mm_mul_pd(_wc4_n, _wc2_n));
        const __m128d _ws6_n = _mm_fmadd_pd(_wc4_n, _ws2_n, _mm_mul_pd(_ws4_n, _wc2_n));
        const __m128d _wc7_n = _mm_fnmadd_pd(_ws4_n, _ws3_n, _mm_mul_pd(_wc4_n, _wc3_n));
        const __m128d _ws7_n = _mm_fmadd_pd(_wc4_n, _ws3_n, _mm_mul_pd(_ws4_n, _wc3_n));
        /* gen2: W^1 = T1[pair] x T2, 6 legs derived */
        const __m128d z0 = _mm_loadu_pd(&zin[2*((size_t)0*Ls + (size_t)k*Gs)]);
        const __m128d z1 = _mm_loadu_pd(&zin[2*((size_t)1*Ls + (size_t)k*Gs)]);
        const __m128d z2 = _mm_loadu_pd(&zin[2*((size_t)2*Ls + (size_t)k*Gs)]);
        const __m128d z3 = _mm_loadu_pd(&zin[2*((size_t)3*Ls + (size_t)k*Gs)]);
        const __m128d z4 = _mm_loadu_pd(&zin[2*((size_t)4*Ls + (size_t)k*Gs)]);
        const __m128d z5 = _mm_loadu_pd(&zin[2*((size_t)5*Ls + (size_t)k*Gs)]);
        const __m128d z6 = _mm_loadu_pd(&zin[2*((size_t)6*Ls + (size_t)k*Gs)]);
        const __m128d z7 = _mm_loadu_pd(&zin[2*((size_t)7*Ls + (size_t)k*Gs)]);
        const __m128d z8 = _mm_sub_pd(z0, z4);
        const __m128d z9 = _mm_add_pd(z0, z4);
        const __m128d z17 = _mm_sub_pd(z1, z5);
        const __m128d z18 = _mm_add_pd(z1, z5);
        const __m128d z10 = _mm_sub_pd(z2, z6);
        const __m128d z11 = _mm_add_pd(z2, z6);
        const __m128d z14 = _mm_xor_pd(_mm_permute_pd(z10, 0x1), _M_RE_n);
        const __m128d z12 = _mm_sub_pd(z9, z11);
        const __m128d z13 = _mm_add_pd(z9, z11);
        const __m128d z15 = _mm_sub_pd(z8, z14);
        const __m128d z16 = _mm_add_pd(z8, z14);
        const __m128d z19 = _mm_sub_pd(z3, z7);
        const __m128d z23 = _mm_xor_pd(_mm_permute_pd(z19, 0x1), _M_RE_n);
        const __m128d z20 = _mm_add_pd(z3, z7);
        const __m128d z24 = _mm_sub_pd(z17, z23);
        const __m128d z25 = _mm_add_pd(z17, z23);
        const __m128d z21 = _mm_sub_pd(z18, z20);
        const __m128d z28 = _mm_xor_pd(_mm_permute_pd(z25, 0x1), _M_RE_n);
        const __m128d z35 = _mm_xor_pd(_mm_permute_pd(z24, 0x1), _M_RE_n);
        const __m128d z22 = _mm_add_pd(z18, z20);
        const __m128d z27 = _mm_add_pd(z13, z22);
        const __m128d z32 = _mm_xor_pd(_mm_permute_pd(z21, 0x1), _M_RE_n);
        const __m128d z29 = _mm_add_pd(z25, z28);
        const __m128d z36 = _mm_sub_pd(z35, z24);
        const __m128d z26 = _mm_sub_pd(z13, z22);
        const __m128d z42 = _mm_fmadd_pd(_wc4_n, z26, _mm_mul_pd(_ws4_n, _mm_permute_pd(z26, 0x1)));
        const __m128d z30 = _mm_fnmadd_pd(_mm_set1_pd(0.70710678118654757), z29, z16);
        const __m128d z43 = _mm_fmadd_pd(_wc5_n, z30, _mm_mul_pd(_ws5_n, _mm_permute_pd(z30, 0x1)));
        const __m128d z31 = _mm_fmadd_pd(_mm_set1_pd(0.70710678118654757), z29, z16);
        const __m128d z39 = _mm_fmadd_pd(_wc1_n, z31, _mm_mul_pd(_ws1_n, _mm_permute_pd(z31, 0x1)));
        const __m128d z33 = _mm_sub_pd(z12, z32);
        const __m128d z44 = _mm_fmadd_pd(_wc6_n, z33, _mm_mul_pd(_ws6_n, _mm_permute_pd(z33, 0x1)));
        const __m128d z34 = _mm_add_pd(z12, z32);
        const __m128d z40 = _mm_fmadd_pd(_wc2_n, z34, _mm_mul_pd(_ws2_n, _mm_permute_pd(z34, 0x1)));
        const __m128d z37 = _mm_fnmadd_pd(_mm_set1_pd(0.70710678118654757), z36, z15);
        const __m128d z45 = _mm_fmadd_pd(_wc7_n, z37, _mm_mul_pd(_ws7_n, _mm_permute_pd(z37, 0x1)));
        const __m128d z38 = _mm_fmadd_pd(_mm_set1_pd(0.70710678118654757), z36, z15);
        const __m128d z41 = _mm_fmadd_pd(_wc3_n, z38, _mm_mul_pd(_ws3_n, _mm_permute_pd(z38, 0x1)));
        _mm_storeu_pd(&zout[2*((size_t)0*OLs + (size_t)k*OGs)], z27);
        _mm_storeu_pd(&zout[2*((size_t)1*OLs + (size_t)k*OGs)], z39);
        _mm_storeu_pd(&zout[2*((size_t)2*OLs + (size_t)k*OGs)], z40);
        _mm_storeu_pd(&zout[2*((size_t)3*OLs + (size_t)k*OGs)], z41);
        _mm_storeu_pd(&zout[2*((size_t)4*OLs + (size_t)k*OGs)], z42);
        _mm_storeu_pd(&zout[2*((size_t)5*OLs + (size_t)k*OGs)], z43);
        _mm_storeu_pd(&zout[2*((size_t)6*OLs + (size_t)k*OGs)], z44);
        _mm_storeu_pd(&zout[2*((size_t)7*OLs + (size_t)k*OGs)], z45);
    }
}
