/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 15 --cil-n1 --cil-blocked --cil-split 3.5 --isa avx2 --uarch raptor_lake_avx2 --emit-c
 * Env overrides: (none)
 * Family: full-IL (interleaved-complex) n1, radix-15 fwd
 * ISA: avx2; 2 complex per vector
 * Uarch: raptor_lake_avx2
 * Form: blocked=true split=3.5 turnst=false turnst_gs=false pretw=false log3=false             tangent=false
 * ====================================================== */
/* Auto-generated by vfft_v2 — INTERLEAVED-COMPLEX (full-IL) family,
 * PIPELINE-HOSTED (codelet_cil.ml; docs/roadmap/zil_pipeline_port.md §11).
 * radix-15 solo n1 (natural order in/out, twiddle-free): 2 complex per 256-bit vector. Body scheduled by the
 * SHARED SR scheduler (Schedule.Make over the complex IR) and rendered
 * through the ISA layer, so the same source emits AVX2 / AVX-512.
 * tw_re/tw_im unused.
 * count: ANY >= 1 — BLOCKED, 2 columns per wide iteration, inline VEX-128
 * odd-count tail for the leftover (il_odd_count_tail.md §3). */
#include <immintrin.h>
#include <stddef.h>

static const __m256d _M_IM = { 0.0, -0.0, 0.0, -0.0 };  /* negate im lanes: x*(-i) */
static const __m128d _M_IM_n = { 0.0, -0.0 };  /* tail twin */
static const __m256d _ZW0_c = { 0.95105651629515353, 0.95105651629515353, 0.95105651629515353, 0.95105651629515353 };
static const __m256d _ZW0_s = { -0, 0, -0, 0 };
static const __m256d _ZW1_c = { 0.58778525229247325, 0.58778525229247325, 0.58778525229247325, 0.58778525229247325 };
static const __m256d _ZW1_s = { -0, 0, -0, 0 };
static const __m128d _ZW10_c = { 0.74314482547739413, 0.74314482547739413 };
static const __m128d _ZW10_s = { -0, 0 };
static const __m128d _ZW11_c = { 0.9945218953682734, 0.9945218953682734 };
static const __m128d _ZW11_s = { -0, 0 };
static const __m128d _ZW12_c = { 0.20791169081775931, 0.20791169081775931 };
static const __m128d _ZW12_s = { -0, 0 };
static const __m128d _ZW13_c = { 0.95105651629515353, 0.95105651629515353 };
static const __m128d _ZW13_s = { -0, 0 };
static const __m128d _ZW14_c = { 0.58778525229247325, 0.58778525229247325 };
static const __m128d _ZW14_s = { -0, 0 };
static const __m128d _ZW15_c = { 0.86602540378443871, 0.86602540378443871 };
static const __m128d _ZW15_s = { -0, 0 };
static const __m256d _ZW2_c = { 0.86602540378443871, 0.86602540378443871, 0.86602540378443871, 0.86602540378443871 };
static const __m256d _ZW2_s = { -0, 0, -0, 0 };
static const __m256d _ZW3_c = { 0.91354545764260087, 0.91354545764260087, 0.91354545764260087, 0.91354545764260087 };
static const __m256d _ZW3_s = { 0.40673664307580015, -0.40673664307580015, 0.40673664307580015, -0.40673664307580015 };
static const __m256d _ZW4_c = { 0.66913060635885824, 0.66913060635885824, 0.66913060635885824, 0.66913060635885824 };
static const __m256d _ZW4_s = { 0.74314482547739413, -0.74314482547739413, 0.74314482547739413, -0.74314482547739413 };
static const __m256d _ZW5_c = { -0.10452846326765333, -0.10452846326765333, -0.10452846326765333, -0.10452846326765333 };
static const __m256d _ZW5_s = { 0.9945218953682734, -0.9945218953682734, 0.9945218953682734, -0.9945218953682734 };
static const __m256d _ZW6_c = { 0.30901699437494745, 0.30901699437494745, 0.30901699437494745, 0.30901699437494745 };
static const __m256d _ZW6_s = { 0.95105651629515353, -0.95105651629515353, 0.95105651629515353, -0.95105651629515353 };
static const __m256d _ZW7_c = { -0.80901699437494734, -0.80901699437494734, -0.80901699437494734, -0.80901699437494734 };
static const __m256d _ZW7_s = { 0.58778525229247325, -0.58778525229247325, 0.58778525229247325, -0.58778525229247325 };
static const __m256d _ZW8_c = { -0.97814760073380569, -0.97814760073380569, -0.97814760073380569, -0.97814760073380569 };
static const __m256d _ZW8_s = { -0.20791169081775907, 0.20791169081775907, -0.20791169081775907, 0.20791169081775907 };
static const __m128d _ZW9_c = { 0.40673664307580015, 0.40673664307580015 };
static const __m128d _ZW9_s = { -0, 0 };

__attribute__((target("avx2,fma")))
void radix15_z_n1b_fwd_avx2(
    const double * __restrict__ zin,
    const double * __restrict__ zin_unused,
    double       * __restrict__ zout,
    double       * __restrict__ zout_unused,
    const double * tw_re, const double * tw_im,
    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)
{
    (void)zin_unused; (void)zout_unused; (void)tw_im; (void)Gs; (void)OGs; (void)tw_re;
    double S[60];  /* half-DFT spill: function-scope, L1-hot across iterations */
    size_t k = 0;
    for (; k + 2 <= count; k += 2) {
        { /* PASS 1.0: legs {a*3+0} -> S[0..4] */
        const __m256d z0 = _mm256_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m256d z1 = _mm256_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m256d z2 = _mm256_loadu_pd(&zin[2*((size_t)6*Ls + k)]);
        const __m256d z3 = _mm256_loadu_pd(&zin[2*((size_t)9*Ls + k)]);
        const __m256d z4 = _mm256_loadu_pd(&zin[2*((size_t)12*Ls + k)]);
        const __m256d z9 = _mm256_sub_pd(z2, z3);
        const __m256d z6 = _mm256_add_pd(z2, z3);
        const __m256d z10 = _mm256_xor_pd(_mm256_permute_pd(z9, 0x5), _M_IM);
        const __m256d z7 = _mm256_sub_pd(z1, z4);
        const __m256d z5 = _mm256_add_pd(z1, z4);
        const __m256d z8 = _mm256_xor_pd(_mm256_permute_pd(z7, 0x5), _M_IM);
        const __m256d z13 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494745), z5, z0);
        const __m256d z14 = _mm256_mul_pd(_ZW0_c, z8);
        const __m256d z19 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z5, z0);
        const __m256d z20 = _mm256_mul_pd(_ZW1_c, z8);
        const __m256d z11 = _mm256_add_pd(z0, z5);
        const __m256d z12 = _mm256_add_pd(z11, z6);
        const __m256d z15 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z6, z13);
        const __m256d z16 = _mm256_fmadd_pd(_mm256_set1_pd(0.58778525229247325), z10, z14);
        const __m256d z17 = _mm256_sub_pd(z15, z16);
        const __m256d z18 = _mm256_add_pd(z15, z16);
        const __m256d z21 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494723), z6, z19);
        const __m256d z22 = _mm256_fnmadd_pd(_mm256_set1_pd(0.95105651629515364), z10, z20);
        const __m256d z23 = _mm256_sub_pd(z21, z22);
        const __m256d z24 = _mm256_add_pd(z21, z22);
        _mm256_storeu_pd(&S[0], z12);
        _mm256_storeu_pd(&S[4], z18);
        _mm256_storeu_pd(&S[8], z24);
        _mm256_storeu_pd(&S[12], z23);
        _mm256_storeu_pd(&S[16], z17);
        }
        { /* PASS 1.1: legs {a*3+1} -> S[5..9] */
        const __m256d z0 = _mm256_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m256d z1 = _mm256_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m256d z2 = _mm256_loadu_pd(&zin[2*((size_t)7*Ls + k)]);
        const __m256d z3 = _mm256_loadu_pd(&zin[2*((size_t)10*Ls + k)]);
        const __m256d z4 = _mm256_loadu_pd(&zin[2*((size_t)13*Ls + k)]);
        const __m256d z9 = _mm256_sub_pd(z2, z3);
        const __m256d z6 = _mm256_add_pd(z2, z3);
        const __m256d z10 = _mm256_xor_pd(_mm256_permute_pd(z9, 0x5), _M_IM);
        const __m256d z7 = _mm256_sub_pd(z1, z4);
        const __m256d z5 = _mm256_add_pd(z1, z4);
        const __m256d z8 = _mm256_xor_pd(_mm256_permute_pd(z7, 0x5), _M_IM);
        const __m256d z13 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494745), z5, z0);
        const __m256d z14 = _mm256_mul_pd(_ZW0_c, z8);
        const __m256d z19 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z5, z0);
        const __m256d z20 = _mm256_mul_pd(_ZW1_c, z8);
        const __m256d z11 = _mm256_add_pd(z0, z5);
        const __m256d z12 = _mm256_add_pd(z11, z6);
        const __m256d z15 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z6, z13);
        const __m256d z16 = _mm256_fmadd_pd(_mm256_set1_pd(0.58778525229247325), z10, z14);
        const __m256d z17 = _mm256_sub_pd(z15, z16);
        const __m256d z18 = _mm256_add_pd(z15, z16);
        const __m256d z21 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494723), z6, z19);
        const __m256d z22 = _mm256_fnmadd_pd(_mm256_set1_pd(0.95105651629515364), z10, z20);
        const __m256d z23 = _mm256_sub_pd(z21, z22);
        const __m256d z24 = _mm256_add_pd(z21, z22);
        _mm256_storeu_pd(&S[20], z12);
        _mm256_storeu_pd(&S[24], z18);
        _mm256_storeu_pd(&S[28], z24);
        _mm256_storeu_pd(&S[32], z23);
        _mm256_storeu_pd(&S[36], z17);
        }
        { /* PASS 1.2: legs {a*3+2} -> S[10..14] */
        const __m256d z0 = _mm256_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m256d z1 = _mm256_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m256d z2 = _mm256_loadu_pd(&zin[2*((size_t)8*Ls + k)]);
        const __m256d z3 = _mm256_loadu_pd(&zin[2*((size_t)11*Ls + k)]);
        const __m256d z4 = _mm256_loadu_pd(&zin[2*((size_t)14*Ls + k)]);
        const __m256d z9 = _mm256_sub_pd(z2, z3);
        const __m256d z6 = _mm256_add_pd(z2, z3);
        const __m256d z10 = _mm256_xor_pd(_mm256_permute_pd(z9, 0x5), _M_IM);
        const __m256d z7 = _mm256_sub_pd(z1, z4);
        const __m256d z5 = _mm256_add_pd(z1, z4);
        const __m256d z8 = _mm256_xor_pd(_mm256_permute_pd(z7, 0x5), _M_IM);
        const __m256d z13 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494745), z5, z0);
        const __m256d z14 = _mm256_mul_pd(_ZW0_c, z8);
        const __m256d z19 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z5, z0);
        const __m256d z20 = _mm256_mul_pd(_ZW1_c, z8);
        const __m256d z11 = _mm256_add_pd(z0, z5);
        const __m256d z12 = _mm256_add_pd(z11, z6);
        const __m256d z15 = _mm256_fnmadd_pd(_mm256_set1_pd(0.80901699437494734), z6, z13);
        const __m256d z16 = _mm256_fmadd_pd(_mm256_set1_pd(0.58778525229247325), z10, z14);
        const __m256d z17 = _mm256_sub_pd(z15, z16);
        const __m256d z18 = _mm256_add_pd(z15, z16);
        const __m256d z21 = _mm256_fmadd_pd(_mm256_set1_pd(0.30901699437494723), z6, z19);
        const __m256d z22 = _mm256_fnmadd_pd(_mm256_set1_pd(0.95105651629515364), z10, z20);
        const __m256d z23 = _mm256_sub_pd(z21, z22);
        const __m256d z24 = _mm256_add_pd(z21, z22);
        _mm256_storeu_pd(&S[40], z12);
        _mm256_storeu_pd(&S[44], z18);
        _mm256_storeu_pd(&S[48], z24);
        _mm256_storeu_pd(&S[52], z23);
        _mm256_storeu_pd(&S[56], z17);
        }
        { /* PASS 2.0: S[i*5+0] -> X[0 + 5*k2] */
        const __m256d z0 = _mm256_loadu_pd(&S[0]);
        const __m256d z1 = _mm256_loadu_pd(&S[20]);
        const __m256d z2 = _mm256_loadu_pd(&S[40]);
        const __m256d z4 = _mm256_sub_pd(z1, z2);
        const __m256d z3 = _mm256_add_pd(z1, z2);
        const __m256d z6 = _mm256_add_pd(z0, z3);
        const __m256d z5 = _mm256_xor_pd(_mm256_permute_pd(z4, 0x5), _M_IM);
        const __m256d z7 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z3, z0);
        const __m256d z8 = _mm256_mul_pd(_ZW2_c, z5);
        const __m256d z9 = _mm256_sub_pd(z7, z8);
        const __m256d z10 = _mm256_add_pd(z7, z8);
        _mm256_storeu_pd(&zout[2*((size_t)0*OLs + k)], z6);
        _mm256_storeu_pd(&zout[2*((size_t)5*OLs + k)], z10);
        _mm256_storeu_pd(&zout[2*((size_t)10*OLs + k)], z9);
        }
        { /* PASS 2.1: S[i*5+1] -> X[1 + 5*k2] */
        const __m256d z0 = _mm256_loadu_pd(&S[4]);
        const __m256d z1 = _mm256_loadu_pd(&S[24]);
        const __m256d z2 = _mm256_loadu_pd(&S[44]);
        const __m256d z3 = _mm256_fmadd_pd(_ZW3_c, z1, _mm256_mul_pd(_ZW3_s, _mm256_permute_pd(z1, 0x5)));
        const __m256d z4 = _mm256_fmadd_pd(_ZW4_c, z2, _mm256_mul_pd(_ZW4_s, _mm256_permute_pd(z2, 0x5)));
        const __m256d z6 = _mm256_sub_pd(z3, z4);
        const __m256d z5 = _mm256_add_pd(z3, z4);
        const __m256d z8 = _mm256_add_pd(z0, z5);
        const __m256d z7 = _mm256_xor_pd(_mm256_permute_pd(z6, 0x5), _M_IM);
        const __m256d z9 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z5, z0);
        const __m256d z10 = _mm256_mul_pd(_ZW2_c, z7);
        const __m256d z11 = _mm256_sub_pd(z9, z10);
        const __m256d z12 = _mm256_add_pd(z9, z10);
        _mm256_storeu_pd(&zout[2*((size_t)1*OLs + k)], z8);
        _mm256_storeu_pd(&zout[2*((size_t)6*OLs + k)], z12);
        _mm256_storeu_pd(&zout[2*((size_t)11*OLs + k)], z11);
        }
        { /* PASS 2.2: S[i*5+2] -> X[2 + 5*k2] */
        const __m256d z0 = _mm256_loadu_pd(&S[8]);
        const __m256d z1 = _mm256_loadu_pd(&S[28]);
        const __m256d z2 = _mm256_loadu_pd(&S[48]);
        const __m256d z3 = _mm256_fmadd_pd(_ZW4_c, z1, _mm256_mul_pd(_ZW4_s, _mm256_permute_pd(z1, 0x5)));
        const __m256d z4 = _mm256_fmadd_pd(_ZW5_c, z2, _mm256_mul_pd(_ZW5_s, _mm256_permute_pd(z2, 0x5)));
        const __m256d z6 = _mm256_sub_pd(z3, z4);
        const __m256d z5 = _mm256_add_pd(z3, z4);
        const __m256d z8 = _mm256_add_pd(z0, z5);
        const __m256d z7 = _mm256_xor_pd(_mm256_permute_pd(z6, 0x5), _M_IM);
        const __m256d z9 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z5, z0);
        const __m256d z10 = _mm256_mul_pd(_ZW2_c, z7);
        const __m256d z11 = _mm256_sub_pd(z9, z10);
        const __m256d z12 = _mm256_add_pd(z9, z10);
        _mm256_storeu_pd(&zout[2*((size_t)2*OLs + k)], z8);
        _mm256_storeu_pd(&zout[2*((size_t)7*OLs + k)], z12);
        _mm256_storeu_pd(&zout[2*((size_t)12*OLs + k)], z11);
        }
        { /* PASS 2.3: S[i*5+3] -> X[3 + 5*k2] */
        const __m256d z0 = _mm256_loadu_pd(&S[12]);
        const __m256d z1 = _mm256_loadu_pd(&S[32]);
        const __m256d z2 = _mm256_loadu_pd(&S[52]);
        const __m256d z3 = _mm256_fmadd_pd(_ZW6_c, z1, _mm256_mul_pd(_ZW6_s, _mm256_permute_pd(z1, 0x5)));
        const __m256d z4 = _mm256_fmadd_pd(_ZW7_c, z2, _mm256_mul_pd(_ZW7_s, _mm256_permute_pd(z2, 0x5)));
        const __m256d z6 = _mm256_sub_pd(z3, z4);
        const __m256d z5 = _mm256_add_pd(z3, z4);
        const __m256d z8 = _mm256_add_pd(z0, z5);
        const __m256d z7 = _mm256_xor_pd(_mm256_permute_pd(z6, 0x5), _M_IM);
        const __m256d z9 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z5, z0);
        const __m256d z10 = _mm256_mul_pd(_ZW2_c, z7);
        const __m256d z11 = _mm256_sub_pd(z9, z10);
        const __m256d z12 = _mm256_add_pd(z9, z10);
        _mm256_storeu_pd(&zout[2*((size_t)3*OLs + k)], z8);
        _mm256_storeu_pd(&zout[2*((size_t)8*OLs + k)], z12);
        _mm256_storeu_pd(&zout[2*((size_t)13*OLs + k)], z11);
        }
        { /* PASS 2.4: S[i*5+4] -> X[4 + 5*k2] */
        const __m256d z0 = _mm256_loadu_pd(&S[16]);
        const __m256d z1 = _mm256_loadu_pd(&S[36]);
        const __m256d z2 = _mm256_loadu_pd(&S[56]);
        const __m256d z3 = _mm256_fmadd_pd(_ZW5_c, z1, _mm256_mul_pd(_ZW5_s, _mm256_permute_pd(z1, 0x5)));
        const __m256d z4 = _mm256_fmadd_pd(_ZW8_c, z2, _mm256_mul_pd(_ZW8_s, _mm256_permute_pd(z2, 0x5)));
        const __m256d z6 = _mm256_sub_pd(z3, z4);
        const __m256d z5 = _mm256_add_pd(z3, z4);
        const __m256d z8 = _mm256_add_pd(z0, z5);
        const __m256d z7 = _mm256_xor_pd(_mm256_permute_pd(z6, 0x5), _M_IM);
        const __m256d z9 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z5, z0);
        const __m256d z10 = _mm256_mul_pd(_ZW2_c, z7);
        const __m256d z11 = _mm256_sub_pd(z9, z10);
        const __m256d z12 = _mm256_add_pd(z9, z10);
        _mm256_storeu_pd(&zout[2*((size_t)4*OLs + k)], z8);
        _mm256_storeu_pd(&zout[2*((size_t)9*OLs + k)], z12);
        _mm256_storeu_pd(&zout[2*((size_t)14*OLs + k)], z11);
        }
    }
    /* odd-count tail: same DAG at VEX-128, one complex per iteration */
    for (; k < count; ++k) {
        const __m128d z0 = _mm_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m128d z1 = _mm_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m128d z2 = _mm_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m128d z3 = _mm_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m128d z4 = _mm_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m128d z5 = _mm_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m128d z6 = _mm_loadu_pd(&zin[2*((size_t)6*Ls + k)]);
        const __m128d z7 = _mm_loadu_pd(&zin[2*((size_t)7*Ls + k)]);
        const __m128d z8 = _mm_loadu_pd(&zin[2*((size_t)8*Ls + k)]);
        const __m128d z9 = _mm_loadu_pd(&zin[2*((size_t)9*Ls + k)]);
        const __m128d z10 = _mm_loadu_pd(&zin[2*((size_t)10*Ls + k)]);
        const __m128d z11 = _mm_loadu_pd(&zin[2*((size_t)11*Ls + k)]);
        const __m128d z12 = _mm_loadu_pd(&zin[2*((size_t)12*Ls + k)]);
        const __m128d z13 = _mm_loadu_pd(&zin[2*((size_t)13*Ls + k)]);
        const __m128d z14 = _mm_loadu_pd(&zin[2*((size_t)14*Ls + k)]);
        const __m128d z34 = _mm_sub_pd(z7, z8);
        const __m128d z21 = _mm_add_pd(z7, z8);
        const __m128d z35 = _mm_xor_pd(_mm_permute_pd(z34, 0x1), _M_IM_n);
        const __m128d z32 = _mm_sub_pd(z6, z9);
        const __m128d z20 = _mm_add_pd(z6, z9);
        const __m128d z33 = _mm_xor_pd(_mm_permute_pd(z32, 0x1), _M_IM_n);
        const __m128d z30 = _mm_sub_pd(z5, z10);
        const __m128d z19 = _mm_add_pd(z5, z10);
        const __m128d z31 = _mm_xor_pd(_mm_permute_pd(z30, 0x1), _M_IM_n);
        const __m128d z28 = _mm_sub_pd(z4, z11);
        const __m128d z18 = _mm_add_pd(z4, z11);
        const __m128d z29 = _mm_xor_pd(_mm_permute_pd(z28, 0x1), _M_IM_n);
        const __m128d z26 = _mm_sub_pd(z3, z12);
        const __m128d z17 = _mm_add_pd(z3, z12);
        const __m128d z27 = _mm_xor_pd(_mm_permute_pd(z26, 0x1), _M_IM_n);
        const __m128d z24 = _mm_sub_pd(z2, z13);
        const __m128d z16 = _mm_add_pd(z2, z13);
        const __m128d z25 = _mm_xor_pd(_mm_permute_pd(z24, 0x1), _M_IM_n);
        const __m128d z22 = _mm_sub_pd(z1, z14);
        const __m128d z15 = _mm_add_pd(z1, z14);
        const __m128d z23 = _mm_xor_pd(_mm_permute_pd(z22, 0x1), _M_IM_n);
        const __m128d z43 = _mm_fmadd_pd(_mm_set1_pd(0.91354545764260087), z15, z0);
        const __m128d z44 = _mm_mul_pd(_ZW9_c, z23);
        const __m128d z59 = _mm_fmadd_pd(_mm_set1_pd(0.66913060635885824), z15, z0);
        const __m128d z60 = _mm_mul_pd(_ZW10_c, z23);
        const __m128d z75 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494745), z15, z0);
        const __m128d z90 = _mm_fnmadd_pd(_mm_set1_pd(0.10452846326765333), z15, z0);
        const __m128d z91 = _mm_mul_pd(_ZW11_c, z23);
        const __m128d z106 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z15, z0);
        const __m128d z120 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z15, z0);
        const __m128d z135 = _mm_fnmadd_pd(_mm_set1_pd(0.97814760073380569), z15, z0);
        const __m128d z136 = _mm_mul_pd(_ZW12_c, z23);
        const __m128d z36 = _mm_add_pd(z0, z15);
        const __m128d z76 = _mm_mul_pd(_ZW13_c, z23);
        const __m128d z121 = _mm_mul_pd(_ZW14_c, z23);
        const __m128d z45 = _mm_fmadd_pd(_mm_set1_pd(0.66913060635885824), z16, z43);
        const __m128d z46 = _mm_fmadd_pd(_mm_set1_pd(0.74314482547739413), z25, z44);
        const __m128d z61 = _mm_fnmadd_pd(_mm_set1_pd(0.10452846326765333), z16, z59);
        const __m128d z62 = _mm_fmadd_pd(_mm_set1_pd(0.9945218953682734), z25, z60);
        const __m128d z77 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z16, z75);
        const __m128d z92 = _mm_fnmadd_pd(_mm_set1_pd(0.97814760073380569), z16, z90);
        const __m128d z93 = _mm_fnmadd_pd(_mm_set1_pd(0.20791169081775907), z25, z91);
        const __m128d z108 = _mm_fnmadd_pd(_mm_set1_pd(0.50000000000000044), z16, z106);
        const __m128d z122 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z16, z120);
        const __m128d z137 = _mm_fmadd_pd(_mm_set1_pd(0.91354545764260098), z16, z135);
        const __m128d z138 = _mm_fnmadd_pd(_mm_set1_pd(0.40673664307580015), z25, z136);
        const __m128d z107 = _mm_mul_pd(_ZW15_c, z23);
        const __m128d z37 = _mm_add_pd(z36, z16);
        const __m128d z47 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494745), z17, z45);
        const __m128d z48 = _mm_fmadd_pd(_mm_set1_pd(0.95105651629515353), z27, z46);
        const __m128d z63 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z17, z61);
        const __m128d z64 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z27, z62);
        const __m128d z78 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z25, z76);
        const __m128d z79 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494756), z17, z77);
        const __m128d z94 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z17, z92);
        const __m128d z95 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z27, z93);
        const __m128d z110 = _mm_add_pd(z108, z17);
        const __m128d z123 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z25, z121);
        const __m128d z124 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494745), z17, z122);
        const __m128d z139 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z17, z137);
        const __m128d z140 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z27, z138);
        const __m128d z38 = _mm_add_pd(z37, z17);
        const __m128d z49 = _mm_fnmadd_pd(_mm_set1_pd(0.10452846326765333), z18, z47);
        const __m128d z50 = _mm_fmadd_pd(_mm_set1_pd(0.9945218953682734), z29, z48);
        const __m128d z65 = _mm_fnmadd_pd(_mm_set1_pd(0.97814760073380569), z18, z63);
        const __m128d z66 = _mm_fnmadd_pd(_mm_set1_pd(0.20791169081775907), z29, z64);
        const __m128d z80 = _mm_fnmadd_pd(_mm_set1_pd(0.58778525229247303), z27, z78);
        const __m128d z81 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z18, z79);
        const __m128d z96 = _mm_fmadd_pd(_mm_set1_pd(0.91354545764260087), z18, z94);
        const __m128d z97 = _mm_fmadd_pd(_mm_set1_pd(0.40673664307580015), z29, z95);
        const __m128d z109 = _mm_fnmadd_pd(_mm_set1_pd(0.86602540378443837), z25, z107);
        const __m128d z111 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z18, z110);
        const __m128d z125 = _mm_fmadd_pd(_mm_set1_pd(0.95105651629515353), z27, z123);
        const __m128d z126 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494756), z18, z124);
        const __m128d z141 = _mm_fmadd_pd(_mm_set1_pd(0.66913060635885846), z18, z139);
        const __m128d z142 = _mm_fnmadd_pd(_mm_set1_pd(0.74314482547739402), z29, z140);
        const __m128d z39 = _mm_add_pd(z38, z18);
        const __m128d z51 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z19, z49);
        const __m128d z52 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z31, z50);
        const __m128d z67 = _mm_fnmadd_pd(_mm_set1_pd(0.50000000000000044), z19, z65);
        const __m128d z68 = _mm_fnmadd_pd(_mm_set1_pd(0.86602540378443837), z31, z66);
        const __m128d z82 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z29, z80);
        const __m128d z83 = _mm_add_pd(z81, z19);
        const __m128d z98 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z19, z96);
        const __m128d z99 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z31, z97);
        const __m128d z112 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z29, z109);
        const __m128d z113 = _mm_fnmadd_pd(_mm_set1_pd(0.50000000000000044), z19, z111);
        const __m128d z127 = _mm_fnmadd_pd(_mm_set1_pd(0.58778525229247303), z29, z125);
        const __m128d z128 = _mm_add_pd(z126, z19);
        const __m128d z143 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z19, z141);
        const __m128d z144 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z31, z142);
        const __m128d z40 = _mm_add_pd(z39, z19);
        const __m128d z53 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z20, z51);
        const __m128d z54 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z33, z52);
        const __m128d z69 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z20, z67);
        const __m128d z70 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z33, z68);
        const __m128d z84 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494745), z20, z83);
        const __m128d z85 = _mm_fmadd_pd(_mm_set1_pd(0.95105651629515353), z33, z82);
        const __m128d z100 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494756), z20, z98);
        const __m128d z101 = _mm_fnmadd_pd(_mm_set1_pd(0.58778525229247303), z33, z99);
        const __m128d z114 = _mm_fnmadd_pd(_mm_set1_pd(0.86602540378443837), z31, z112);
        const __m128d z115 = _mm_add_pd(z113, z20);
        const __m128d z129 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z20, z128);
        const __m128d z130 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z33, z127);
        const __m128d z145 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z20, z143);
        const __m128d z146 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z33, z144);
        const __m128d z41 = _mm_add_pd(z40, z20);
        const __m128d z42 = _mm_add_pd(z41, z21);
        const __m128d z55 = _mm_fnmadd_pd(_mm_set1_pd(0.97814760073380569), z21, z53);
        const __m128d z56 = _mm_fmadd_pd(_mm_set1_pd(0.20791169081775931), z35, z54);
        const __m128d z57 = _mm_sub_pd(z55, z56);
        const __m128d z58 = _mm_add_pd(z55, z56);
        const __m128d z71 = _mm_fmadd_pd(_mm_set1_pd(0.91354545764260098), z21, z69);
        const __m128d z72 = _mm_fnmadd_pd(_mm_set1_pd(0.40673664307580015), z35, z70);
        const __m128d z73 = _mm_sub_pd(z71, z72);
        const __m128d z74 = _mm_add_pd(z71, z72);
        const __m128d z86 = _mm_fnmadd_pd(_mm_set1_pd(0.80901699437494734), z21, z84);
        const __m128d z87 = _mm_fmadd_pd(_mm_set1_pd(0.58778525229247325), z35, z85);
        const __m128d z88 = _mm_sub_pd(z86, z87);
        const __m128d z89 = _mm_add_pd(z86, z87);
        const __m128d z102 = _mm_fmadd_pd(_mm_set1_pd(0.66913060635885846), z21, z100);
        const __m128d z103 = _mm_fnmadd_pd(_mm_set1_pd(0.74314482547739402), z35, z101);
        const __m128d z104 = _mm_sub_pd(z102, z103);
        const __m128d z105 = _mm_add_pd(z102, z103);
        const __m128d z116 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z21, z115);
        const __m128d z117 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z35, z114);
        const __m128d z118 = _mm_sub_pd(z116, z117);
        const __m128d z119 = _mm_add_pd(z116, z117);
        const __m128d z131 = _mm_fmadd_pd(_mm_set1_pd(0.30901699437494723), z21, z129);
        const __m128d z132 = _mm_fnmadd_pd(_mm_set1_pd(0.95105651629515364), z35, z130);
        const __m128d z133 = _mm_sub_pd(z131, z132);
        const __m128d z134 = _mm_add_pd(z131, z132);
        const __m128d z147 = _mm_fnmadd_pd(_mm_set1_pd(0.10452846326765333), z21, z145);
        const __m128d z148 = _mm_fmadd_pd(_mm_set1_pd(0.9945218953682734), z35, z146);
        const __m128d z149 = _mm_sub_pd(z147, z148);
        const __m128d z150 = _mm_add_pd(z147, z148);
        _mm_storeu_pd(&zout[2*((size_t)0*OLs + k)], z42);
        _mm_storeu_pd(&zout[2*((size_t)1*OLs + k)], z58);
        _mm_storeu_pd(&zout[2*((size_t)2*OLs + k)], z74);
        _mm_storeu_pd(&zout[2*((size_t)3*OLs + k)], z89);
        _mm_storeu_pd(&zout[2*((size_t)4*OLs + k)], z105);
        _mm_storeu_pd(&zout[2*((size_t)5*OLs + k)], z119);
        _mm_storeu_pd(&zout[2*((size_t)6*OLs + k)], z134);
        _mm_storeu_pd(&zout[2*((size_t)7*OLs + k)], z150);
        _mm_storeu_pd(&zout[2*((size_t)8*OLs + k)], z149);
        _mm_storeu_pd(&zout[2*((size_t)9*OLs + k)], z133);
        _mm_storeu_pd(&zout[2*((size_t)10*OLs + k)], z118);
        _mm_storeu_pd(&zout[2*((size_t)11*OLs + k)], z104);
        _mm_storeu_pd(&zout[2*((size_t)12*OLs + k)], z88);
        _mm_storeu_pd(&zout[2*((size_t)13*OLs + k)], z73);
        _mm_storeu_pd(&zout[2*((size_t)14*OLs + k)], z57);
    }
}
