/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 6 --cil-t2 --isa avx2 --uarch raptor_lake_avx2 --emit-c
 * Env overrides: (none)
 * Family: full-IL (interleaved-complex) t2, radix-6 fwd
 * ISA: avx2; 2 complex per vector
 * Uarch: raptor_lake_avx2
 * Form: blocked=false split=- turnst=false turnst_gs=false pretw=false log3=false             tangent=false
 * ====================================================== */
/* Auto-generated by vfft_v2 — INTERLEAVED-COMPLEX (full-IL) family,
 * PIPELINE-HOSTED (codelet_cil.ml; docs/roadmap/zil_pipeline_port.md §11).
 * radix-6 bailey2 stage-2 mid t2 (streamed VTW2 twiddles, BYTW2 apply): 2 complex per 256-bit vector. Body scheduled by the
 * SHARED SR scheduler (Schedule.Make over the complex IR) and rendered
 * through the ISA layer, so the same source emits AVX2 / AVX-512.
 * tw_re = VTW2 records, cos-first and sign-folded: per column-group, per
 * leg 1..R-1, one 8-double record [c x4][-s,+s ...]. Cursor advances
 * 40 doubles per group; BYTW2 = fmadd(c, x, mul(s, cflip x)) — ONE
 * data-side shuffle, zero table-side work. tw_im unused.
 * count: ANY >= 1 — 2 columns per wide iteration, inline VEX-128
 * odd-count tail for the leftover (il_odd_count_tail.md §3). */
#include <immintrin.h>
#include <stddef.h>

static const __m256d _M_IM = { 0.0, -0.0, 0.0, -0.0 };  /* negate im lanes: x*(-i) */
static const __m128d _M_IM_n = { 0.0, -0.0 };  /* tail twin */
static const __m256d _ZW0_c = { 0.50000000000000011, 0.50000000000000011, 0.50000000000000011, 0.50000000000000011 };
static const __m256d _ZW0_s = { 0.8660254037844386, -0.8660254037844386, 0.8660254037844386, -0.8660254037844386 };
static const __m256d _ZW1_c = { -0.49999999999999978, -0.49999999999999978, -0.49999999999999978, -0.49999999999999978 };
static const __m256d _ZW1_s = { 0.86602540378443871, -0.86602540378443871, 0.86602540378443871, -0.86602540378443871 };
static const __m128d _ZW2_c = { 0.50000000000000011, 0.50000000000000011 };
static const __m128d _ZW2_s = { 0.8660254037844386, -0.8660254037844386 };
static const __m128d _ZW3_c = { -0.49999999999999978, -0.49999999999999978 };
static const __m128d _ZW3_s = { 0.86602540378443871, -0.86602540378443871 };

__attribute__((target("avx2,fma")))
void radix6_z_t2_fwd_avx2(
    const double *            zin,
    const double *            zin_unused,
    double       *            zout,
    double       *            zout_unused,
    const double * tw_re, const double * tw_im,
    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)
{
    (void)zin_unused; (void)zout_unused; (void)tw_im; (void)Gs; (void)OGs;
    size_t k = 0;
    for (; k + 2 <= count; k += 2) {
        const double *twp = tw_re + (k / 2) * (size_t)40;
        const __m256d z0 = _mm256_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m256d z1 = _mm256_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m256d z3 = _mm256_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m256d z5 = _mm256_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m256d z7 = _mm256_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m256d z9 = _mm256_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m256d z2 = _mm256_fmadd_pd(_mm256_loadu_pd(&twp[0]), z1, _mm256_mul_pd(_mm256_loadu_pd(&twp[4]), _mm256_permute_pd(z1, 0x5)));
        const __m256d z4 = _mm256_fmadd_pd(_mm256_loadu_pd(&twp[8]), z3, _mm256_mul_pd(_mm256_loadu_pd(&twp[12]), _mm256_permute_pd(z3, 0x5)));
        const __m256d z6 = _mm256_fmadd_pd(_mm256_loadu_pd(&twp[16]), z5, _mm256_mul_pd(_mm256_loadu_pd(&twp[20]), _mm256_permute_pd(z5, 0x5)));
        const __m256d z8 = _mm256_fmadd_pd(_mm256_loadu_pd(&twp[24]), z7, _mm256_mul_pd(_mm256_loadu_pd(&twp[28]), _mm256_permute_pd(z7, 0x5)));
        const __m256d z11 = _mm256_add_pd(z4, z8);
        const __m256d z12 = _mm256_sub_pd(z4, z8);
        const __m256d z13 = _mm256_xor_pd(_mm256_permute_pd(z12, 0x5), _M_IM);
        const __m256d z15 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z11, z0);
        const __m256d z14 = _mm256_add_pd(z0, z11);
        const __m256d z16 = _mm256_fnmadd_pd(_mm256_set1_pd(0.86602540378443871), z13, z15);
        const __m256d z17 = _mm256_fmadd_pd(_mm256_set1_pd(0.86602540378443871), z13, z15);
        const __m256d z10 = _mm256_fmadd_pd(_mm256_loadu_pd(&twp[32]), z9, _mm256_mul_pd(_mm256_loadu_pd(&twp[36]), _mm256_permute_pd(z9, 0x5)));
        const __m256d z18 = _mm256_add_pd(z6, z10);
        const __m256d z19 = _mm256_sub_pd(z6, z10);
        const __m256d z20 = _mm256_xor_pd(_mm256_permute_pd(z19, 0x5), _M_IM);
        const __m256d z22 = _mm256_fnmadd_pd(_mm256_set1_pd(0.49999999999999978), z18, z2);
        const __m256d z23 = _mm256_fnmadd_pd(_mm256_set1_pd(0.86602540378443871), z20, z22);
        const __m256d z24 = _mm256_fmadd_pd(_mm256_set1_pd(0.86602540378443871), z20, z22);
        const __m256d z21 = _mm256_add_pd(z2, z18);
        const __m256d z25 = _mm256_sub_pd(z14, z21);
        const __m256d z26 = _mm256_add_pd(z14, z21);
        const __m256d z27 = _mm256_fmadd_pd(_ZW0_c, z24, _mm256_mul_pd(_ZW0_s, _mm256_permute_pd(z24, 0x5)));
        const __m256d z28 = _mm256_sub_pd(z17, z27);
        const __m256d z29 = _mm256_add_pd(z17, z27);
        const __m256d z30 = _mm256_fmadd_pd(_ZW1_c, z23, _mm256_mul_pd(_ZW1_s, _mm256_permute_pd(z23, 0x5)));
        const __m256d z31 = _mm256_sub_pd(z16, z30);
        const __m256d z32 = _mm256_add_pd(z16, z30);
        _mm256_storeu_pd(&zout[2*((size_t)0*OLs + k)], z26);
        _mm256_storeu_pd(&zout[2*((size_t)1*OLs + k)], z29);
        _mm256_storeu_pd(&zout[2*((size_t)2*OLs + k)], z32);
        _mm256_storeu_pd(&zout[2*((size_t)3*OLs + k)], z25);
        _mm256_storeu_pd(&zout[2*((size_t)4*OLs + k)], z28);
        _mm256_storeu_pd(&zout[2*((size_t)5*OLs + k)], z31);
    }
    /* odd-count tail: same DAG at VEX-128, one complex per iteration */
    for (; k < count; ++k) {
        const double *twp = tw_re + (k / 2) * (size_t)40;
        const __m128d z0 = _mm_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m128d z1 = _mm_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m128d z3 = _mm_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m128d z5 = _mm_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m128d z7 = _mm_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m128d z9 = _mm_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m128d z2 = _mm_fmadd_pd(_mm_loadu_pd(&twp[0]), z1, _mm_mul_pd(_mm_loadu_pd(&twp[4]), _mm_permute_pd(z1, 0x1)));
        const __m128d z4 = _mm_fmadd_pd(_mm_loadu_pd(&twp[8]), z3, _mm_mul_pd(_mm_loadu_pd(&twp[12]), _mm_permute_pd(z3, 0x1)));
        const __m128d z6 = _mm_fmadd_pd(_mm_loadu_pd(&twp[16]), z5, _mm_mul_pd(_mm_loadu_pd(&twp[20]), _mm_permute_pd(z5, 0x1)));
        const __m128d z8 = _mm_fmadd_pd(_mm_loadu_pd(&twp[24]), z7, _mm_mul_pd(_mm_loadu_pd(&twp[28]), _mm_permute_pd(z7, 0x1)));
        const __m128d z11 = _mm_add_pd(z4, z8);
        const __m128d z12 = _mm_sub_pd(z4, z8);
        const __m128d z13 = _mm_xor_pd(_mm_permute_pd(z12, 0x1), _M_IM_n);
        const __m128d z15 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z11, z0);
        const __m128d z14 = _mm_add_pd(z0, z11);
        const __m128d z16 = _mm_fnmadd_pd(_mm_set1_pd(0.86602540378443871), z13, z15);
        const __m128d z17 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z13, z15);
        const __m128d z10 = _mm_fmadd_pd(_mm_loadu_pd(&twp[32]), z9, _mm_mul_pd(_mm_loadu_pd(&twp[36]), _mm_permute_pd(z9, 0x1)));
        const __m128d z18 = _mm_add_pd(z6, z10);
        const __m128d z19 = _mm_sub_pd(z6, z10);
        const __m128d z20 = _mm_xor_pd(_mm_permute_pd(z19, 0x1), _M_IM_n);
        const __m128d z22 = _mm_fnmadd_pd(_mm_set1_pd(0.49999999999999978), z18, z2);
        const __m128d z23 = _mm_fnmadd_pd(_mm_set1_pd(0.86602540378443871), z20, z22);
        const __m128d z24 = _mm_fmadd_pd(_mm_set1_pd(0.86602540378443871), z20, z22);
        const __m128d z21 = _mm_add_pd(z2, z18);
        const __m128d z25 = _mm_sub_pd(z14, z21);
        const __m128d z26 = _mm_add_pd(z14, z21);
        const __m128d z27 = _mm_fmadd_pd(_ZW2_c, z24, _mm_mul_pd(_ZW2_s, _mm_permute_pd(z24, 0x1)));
        const __m128d z28 = _mm_sub_pd(z17, z27);
        const __m128d z29 = _mm_add_pd(z17, z27);
        const __m128d z30 = _mm_fmadd_pd(_ZW3_c, z23, _mm_mul_pd(_ZW3_s, _mm_permute_pd(z23, 0x1)));
        const __m128d z31 = _mm_sub_pd(z16, z30);
        const __m128d z32 = _mm_add_pd(z16, z30);
        _mm_storeu_pd(&zout[2*((size_t)0*OLs + k)], z26);
        _mm_storeu_pd(&zout[2*((size_t)1*OLs + k)], z29);
        _mm_storeu_pd(&zout[2*((size_t)2*OLs + k)], z32);
        _mm_storeu_pd(&zout[2*((size_t)3*OLs + k)], z25);
        _mm_storeu_pd(&zout[2*((size_t)4*OLs + k)], z28);
        _mm_storeu_pd(&zout[2*((size_t)5*OLs + k)], z31);
    }
}
