(* codelet_zil.ml — TRUE interleaved-native (z-layout) codelet emitter.
 *
 * Tier-2 of the IL-native workstream (docs/roadmap/il_native_design.md,
 * docs/research/mkl_il_512_anatomy.md). Unlike the split codelets +
 * il_in/il_out boundary lattices (the DELETED il_derive population and the
 * K=1 boundary twins), these codelets keep every value INTERLEAVED
 * (2 complex per %ymm, [re0,im0,re1,im1]) end-to-end — no split re/im planes,
 * no boundary conversion. This is FFTW's n1fv / MKL's zzd2 model.
 *
 * The existing emitter (codelet_oop.ml + emit_c.ml + algsimp) is a REAL-valued
 * (split) backend: the `expr` type is Const/Load/Add/Sub/Mul over reals and the
 * DAG carries CmulRe/CmulIm nodes. That backend cannot be "re-rendered"
 * interleaved — it has already split complex into real subtrees. So this is a
 * separate, small complex-vector backend for the pow-2 radices (which cover
 * every cell we ship: 512 = 8/16/32/64, etc.).
 *
 * M1 (this file, first cut): radix-8 n1 leaf (twiddle-free), forward, matching
 * the bit-exact hand oracle in build_tuned/benches/il_r8_m1_race.c (r8_z).
 * M2+: radix 4/16/32/64, the t2 twiddle variant (VTW2 table + BYTW2), backward.
 *
 * Complex-vector primitives emitted (AVX2, VL=2):
 *   Vadd/Vsub          -> _mm256_add_pd / _mm256_sub_pd  (act on both re,im)
 *   ZmulNI(z)=z*(-i)   -> (im,-re): _mm256_xor_pd(_mm256_permute_pd(z,5), M_IM)
 *   scale by const c   -> _mm256_mul_pd(_C, z)
 * where M_IM negates the imaginary lanes and _C is a broadcast constant.
 *)

(* radix-8 forward n1, interleaved. `outs.(p)` is the C expression producing
 * output point p from inputs in.(0..7). EXACT translation of the verified
 * split dft8v (mono-64) — see the race oracle. Emitted straight-line; gcc
 * schedules. *)
let r8_body (buf : Buffer.t) ~(ind : string) : unit =
  let p s = Buffer.add_string buf (ind ^ s ^ "\n") in
  p "const __m256d _C = _mm256_set1_pd(0.70710678118654752440);";
  (* t = radix-2 on even/odd 4-groups *)
  p "__m256d t0=_mm256_add_pd(in0,in4), t1=_mm256_sub_pd(in0,in4);";
  p "__m256d t2=_mm256_add_pd(in2,in6), t3=_mm256_sub_pd(in2,in6);";
  p "__m256d E0=_mm256_add_pd(t0,t2),   E2=_mm256_sub_pd(t0,t2);";
  p "__m256d _t3ni=_mm256_xor_pd(_mm256_permute_pd(t3,0x5),_M_IM); /* t3*(-i) */";
  p "__m256d E1=_mm256_add_pd(t1,_t3ni), E3=_mm256_sub_pd(t1,_t3ni);";
  p "__m256d s0=_mm256_add_pd(in1,in5), s1=_mm256_sub_pd(in1,in5);";
  p "__m256d s2=_mm256_add_pd(in3,in7), s3=_mm256_sub_pd(in3,in7);";
  p "__m256d O0=_mm256_add_pd(s0,s2),   O2=_mm256_sub_pd(s0,s2);";
  p "__m256d _s3ni=_mm256_xor_pd(_mm256_permute_pd(s3,0x5),_M_IM); /* s3*(-i) */";
  p "__m256d O1=_mm256_add_pd(s1,_s3ni), O3=_mm256_sub_pd(s1,_s3ni);";
  (* twiddled odd combine: W1=C*(O1+O1*(-i)), W2=O2*(-i), W3=C*(O3*(-i)-O3) *)
  p "__m256d _o1ni=_mm256_xor_pd(_mm256_permute_pd(O1,0x5),_M_IM);";
  p "__m256d W1=_mm256_mul_pd(_C,_mm256_add_pd(O1,_o1ni));";
  p "__m256d W2=_mm256_xor_pd(_mm256_permute_pd(O2,0x5),_M_IM); /* O2*(-i) */";
  p "__m256d _o3ni=_mm256_xor_pd(_mm256_permute_pd(O3,0x5),_M_IM);";
  p "__m256d W3=_mm256_mul_pd(_C,_mm256_sub_pd(_o3ni,O3));";
  p "out0=_mm256_add_pd(E0,O0); out4=_mm256_sub_pd(E0,O0);";
  p "out1=_mm256_add_pd(E1,W1); out5=_mm256_sub_pd(E1,W1);";
  p "out2=_mm256_add_pd(E2,W2); out6=_mm256_sub_pd(E2,W2);";
  p "out3=_mm256_add_pd(E3,W3); out7=_mm256_sub_pd(E3,W3);"

(* Emit a z-native n1 leaf codelet. ABI mirrors the il-style oop11 shape so it
 * plugs into the existing execution machinery: z in the "re" pointer slot, the
 * "im" slot unused; strides in COMPLEX units (leg Ls, group Gs, out OLs/OGs).
 * Loops `count` columns, 2 per %ymm. *)
let emit_z_n1 ~(vec_width : int) ~(radix : int) : string =
  if vec_width <> 4 then failwith "codelet_zil: avx2 only (vec_width 4)";
  if radix <> 8 then failwith "codelet_zil M1: radix 8 only (M2 adds 4/16/32/64)";
  let fname = Printf.sprintf "radix%d_z_n1_fwd_avx2" radix in
  let buf = Buffer.create 8192 in
  Buffer.add_string buf
    "/* Auto-generated by vfft_v2 — TRUE interleaved-native (z) codelet family\n\
    \ * (codelet_zil.ml; docs/roadmap/il_native_design.md). 2 complex per ymm,\n\
    \ * no split planes, no boundary conversion. n1 leaf (twiddle-free), fwd. */\n\
     #include <immintrin.h>\n\
     #include <stddef.h>\n\n\
     static const __m256d _M_IM = { 0.0, -0.0, 0.0, -0.0 }; /* negate im lanes */\n\n";
  Buffer.add_string buf
    (Printf.sprintf
       "__attribute__((target(\"avx2,fma\")))\n\
        void %s(\n\
       \    const double * __restrict__ zin,\n\
       \    const double * __restrict__ zin_unused,\n\
       \    double       * __restrict__ zout,\n\
       \    double       * __restrict__ zout_unused,\n\
       \    const double * tw_re, const double * tw_im,\n\
       \    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)\n\
        {\n\
       \    (void)zin_unused; (void)zout_unused; (void)tw_re; (void)tw_im; (void)Gs; (void)OGs;\n\
       \    for (size_t k = 0; k + 2 <= count; k += 2) {\n"
       fname);
  (* loads: point p of columns k,k+1 = zin[2*(p*Ls + k) ..+3] *)
  for pt = 0 to radix - 1 do
    Buffer.add_string buf
      (Printf.sprintf
         "        __m256d in%d = _mm256_loadu_pd(zin + 2*((size_t)%d*Ls + k));\n"
         pt pt)
  done;
  for pt = 0 to radix - 1 do
    Buffer.add_string buf (Printf.sprintf "        __m256d out%d;\n" pt)
  done;
  r8_body buf ~ind:"        ";
  for pt = 0 to radix - 1 do
    Buffer.add_string buf
      (Printf.sprintf
         "        _mm256_storeu_pd(zout + 2*((size_t)%d*OLs + k), out%d);\n"
         pt pt)
  done;
  Buffer.add_string buf "    }\n}\n";
  Buffer.contents buf
