/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 32 --strided --isa avx2 --bwd --emit-c
 * Env overrides: (none)
 * Family: strided-batch (Design C, 2D rows)
 * ISA: 256-bit vectors, 16 vector regs (16-reg pressure rules apply)
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: true (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: MONOLITHIC (below blocking threshold, or prime/Direct: no CT pass boundary)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: no
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix32_n1_bwd_avx2_strided(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t row_stride,
    size_t me)
{
    (void)tw_re; (void)tw_im;
    for (size_t b = 0; b < me; b += 4) {
        __m256d lane_re_0, lane_im_0;
        __m256d out_lane_re_0, out_lane_im_0;
        __m256d lane_re_1, lane_im_1;
        __m256d out_lane_re_1, out_lane_im_1;
        __m256d lane_re_2, lane_im_2;
        __m256d out_lane_re_2, out_lane_im_2;
        __m256d lane_re_3, lane_im_3;
        __m256d out_lane_re_3, out_lane_im_3;
        __m256d lane_re_4, lane_im_4;
        __m256d out_lane_re_4, out_lane_im_4;
        __m256d lane_re_5, lane_im_5;
        __m256d out_lane_re_5, out_lane_im_5;
        __m256d lane_re_6, lane_im_6;
        __m256d out_lane_re_6, out_lane_im_6;
        __m256d lane_re_7, lane_im_7;
        __m256d out_lane_re_7, out_lane_im_7;
        __m256d lane_re_8, lane_im_8;
        __m256d out_lane_re_8, out_lane_im_8;
        __m256d lane_re_9, lane_im_9;
        __m256d out_lane_re_9, out_lane_im_9;
        __m256d lane_re_10, lane_im_10;
        __m256d out_lane_re_10, out_lane_im_10;
        __m256d lane_re_11, lane_im_11;
        __m256d out_lane_re_11, out_lane_im_11;
        __m256d lane_re_12, lane_im_12;
        __m256d out_lane_re_12, out_lane_im_12;
        __m256d lane_re_13, lane_im_13;
        __m256d out_lane_re_13, out_lane_im_13;
        __m256d lane_re_14, lane_im_14;
        __m256d out_lane_re_14, out_lane_im_14;
        __m256d lane_re_15, lane_im_15;
        __m256d out_lane_re_15, out_lane_im_15;
        __m256d lane_re_16, lane_im_16;
        __m256d out_lane_re_16, out_lane_im_16;
        __m256d lane_re_17, lane_im_17;
        __m256d out_lane_re_17, out_lane_im_17;
        __m256d lane_re_18, lane_im_18;
        __m256d out_lane_re_18, out_lane_im_18;
        __m256d lane_re_19, lane_im_19;
        __m256d out_lane_re_19, out_lane_im_19;
        __m256d lane_re_20, lane_im_20;
        __m256d out_lane_re_20, out_lane_im_20;
        __m256d lane_re_21, lane_im_21;
        __m256d out_lane_re_21, out_lane_im_21;
        __m256d lane_re_22, lane_im_22;
        __m256d out_lane_re_22, out_lane_im_22;
        __m256d lane_re_23, lane_im_23;
        __m256d out_lane_re_23, out_lane_im_23;
        __m256d lane_re_24, lane_im_24;
        __m256d out_lane_re_24, out_lane_im_24;
        __m256d lane_re_25, lane_im_25;
        __m256d out_lane_re_25, out_lane_im_25;
        __m256d lane_re_26, lane_im_26;
        __m256d out_lane_re_26, out_lane_im_26;
        __m256d lane_re_27, lane_im_27;
        __m256d out_lane_re_27, out_lane_im_27;
        __m256d lane_re_28, lane_im_28;
        __m256d out_lane_re_28, out_lane_im_28;
        __m256d lane_re_29, lane_im_29;
        __m256d out_lane_re_29, out_lane_im_29;
        __m256d lane_re_30, lane_im_30;
        __m256d out_lane_re_30, out_lane_im_30;
        __m256d lane_re_31, lane_im_31;
        __m256d out_lane_re_31, out_lane_im_31;

        {  /* 4x4 transpose group: fft_idx 0..3, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 0]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 0]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 0]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 0]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_0 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_1 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_2 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_3 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 4..7, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 4]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 4]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 4]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 4]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_4 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_5 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_6 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_7 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 8..11, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 8]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 8]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 8]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 8]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_8 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_9 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_10 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_11 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 12..15, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 12]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 12]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 12]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 12]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_12 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_13 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_14 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_15 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 16..19, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 16]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 16]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 16]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 16]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_16 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_17 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_18 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_19 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 20..23, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 20]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 20]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 20]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 20]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_20 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_21 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_22 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_23 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 24..27, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 24]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 24]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 24]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 24]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_24 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_25 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_26 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_27 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 28..31, re */
            const __m256d _row_re_0 = _mm256_loadu_pd(&rio_re[(b+0)*row_stride + 28]);
            const __m256d _row_re_1 = _mm256_loadu_pd(&rio_re[(b+1)*row_stride + 28]);
            const __m256d _row_re_2 = _mm256_loadu_pd(&rio_re[(b+2)*row_stride + 28]);
            const __m256d _row_re_3 = _mm256_loadu_pd(&rio_re[(b+3)*row_stride + 28]);
            const __m256d _t0_re = _mm256_unpacklo_pd(_row_re_0, _row_re_1);
            const __m256d _t1_re = _mm256_unpackhi_pd(_row_re_0, _row_re_1);
            const __m256d _t2_re = _mm256_unpacklo_pd(_row_re_2, _row_re_3);
            const __m256d _t3_re = _mm256_unpackhi_pd(_row_re_2, _row_re_3);
            lane_re_28 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x20);
            lane_re_29 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x20);
            lane_re_30 = _mm256_permute2f128_pd(_t0_re, _t2_re, 0x31);
            lane_re_31 = _mm256_permute2f128_pd(_t1_re, _t3_re, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 0..3, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 0]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 0]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 0]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 0]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_0 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_1 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_2 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_3 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 4..7, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 4]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 4]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 4]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 4]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_4 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_5 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_6 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_7 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 8..11, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 8]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 8]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 8]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 8]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_8 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_9 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_10 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_11 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 12..15, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 12]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 12]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 12]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 12]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_12 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_13 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_14 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_15 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 16..19, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 16]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 16]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 16]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 16]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_16 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_17 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_18 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_19 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 20..23, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 20]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 20]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 20]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 20]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_20 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_21 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_22 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_23 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 24..27, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 24]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 24]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 24]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 24]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_24 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_25 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_26 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_27 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }
        {  /* 4x4 transpose group: fft_idx 28..31, im */
            const __m256d _row_im_0 = _mm256_loadu_pd(&rio_im[(b+0)*row_stride + 28]);
            const __m256d _row_im_1 = _mm256_loadu_pd(&rio_im[(b+1)*row_stride + 28]);
            const __m256d _row_im_2 = _mm256_loadu_pd(&rio_im[(b+2)*row_stride + 28]);
            const __m256d _row_im_3 = _mm256_loadu_pd(&rio_im[(b+3)*row_stride + 28]);
            const __m256d _t0_im = _mm256_unpacklo_pd(_row_im_0, _row_im_1);
            const __m256d _t1_im = _mm256_unpackhi_pd(_row_im_0, _row_im_1);
            const __m256d _t2_im = _mm256_unpacklo_pd(_row_im_2, _row_im_3);
            const __m256d _t3_im = _mm256_unpackhi_pd(_row_im_2, _row_im_3);
            lane_im_28 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x20);
            lane_im_29 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x20);
            lane_im_30 = _mm256_permute2f128_pd(_t0_im, _t2_im, 0x31);
            lane_im_31 = _mm256_permute2f128_pd(_t1_im, _t3_im, 0x31);
        }

        const __m256d t25 = _mm256_set1_pd(0.70710678118655002);
        const __m256d t55 = _mm256_set1_pd(0.66817863791929);
        const __m256d t116 = _mm256_set1_pd(0.19891236737966);
        const __m256d t176 = _mm256_set1_pd(0.41421356237308998);
        const __m256d t58 = _mm256_set1_pd(0.83146961230255001);
        const __m256d t119 = _mm256_set1_pd(0.98078528040322999);
        const __m256d t182 = _mm256_set1_pd(0.92387953251128996);
        const __m256d t0 = lane_re_31;
        const __m256d t2 = lane_im_31;
        const __m256d t5 = lane_re_15;
        const __m256d t10 = _mm256_sub_pd(t5, t0);
        const __m256d t247 = _mm256_add_pd(t0, t5);
        const __m256d t6 = lane_im_15;
        const __m256d t8 = _mm256_sub_pd(t6, t2);
        const __m256d t246 = _mm256_add_pd(t2, t6);
        const __m256d t13 = lane_re_23;
        const __m256d t14 = lane_im_23;
        const __m256d t16 = lane_re_7;
        const __m256d t20 = _mm256_sub_pd(t16, t13);
        const __m256d t23 = _mm256_add_pd(t8, t20);
        const __m256d t357 = _mm256_sub_pd(t20, t8);
        const __m256d t250 = _mm256_add_pd(t13, t16);
        const __m256d t253 = _mm256_sub_pd(t250, t247);
        const __m256d t441 = _mm256_add_pd(t247, t250);
        const __m256d t17 = lane_im_7;
        const __m256d t18 = _mm256_sub_pd(t17, t14);
        const __m256d t21 = _mm256_sub_pd(t18, t10);
        const __m256d t356 = _mm256_add_pd(t10, t18);
        const __m256d t249 = _mm256_add_pd(t14, t17);
        const __m256d t24 = _mm256_add_pd(t21, t23);
        const __m256d t30 = _mm256_sub_pd(t21, t23);
        const __m256d t358 = _mm256_sub_pd(t357, t356);
        const __m256d t360 = _mm256_add_pd(t356, t357);
        const __m256d t251 = _mm256_sub_pd(t249, t246);
        const __m256d t440 = _mm256_add_pd(t246, t249);
        const __m256d t33 = lane_re_27;
        const __m256d t34 = lane_im_27;
        const __m256d t36 = lane_re_11;
        const __m256d t40 = _mm256_sub_pd(t36, t33);
        const __m256d t257 = _mm256_add_pd(t33, t36);
        const __m256d t37 = lane_im_11;
        const __m256d t38 = _mm256_sub_pd(t37, t34);
        const __m256d t256 = _mm256_add_pd(t34, t37);
        const __m256d t43 = lane_re_19;
        const __m256d t44 = lane_im_19;
        const __m256d t46 = lane_re_3;
        const __m256d t50 = _mm256_sub_pd(t46, t43);
        const __m256d t260 = _mm256_add_pd(t43, t46);
        const __m256d t52 = _mm256_add_pd(t38, t50);
        const __m256d t364 = _mm256_sub_pd(t50, t38);
        const __m256d t263 = _mm256_sub_pd(t260, t257);
        const __m256d t444 = _mm256_add_pd(t257, t260);
        const __m256d t981 = _mm256_fnmadd_pd(t24, t25, t52);
        const __m256d t1010 = _mm256_fmadd_pd(t25, t358, t364);
        const __m256d t266 = _mm256_add_pd(t251, t263);
        const __m256d t448 = _mm256_sub_pd(t444, t441);
        const __m256d t535 = _mm256_sub_pd(t263, t251);
        const __m256d t919 = _mm256_fmadd_pd(t24, t25, t52);
        const __m256d t954 = _mm256_fnmadd_pd(t25, t358, t364);
        const __m256d t609 = _mm256_add_pd(t441, t444);
        const __m256d t47 = lane_im_3;
        const __m256d t48 = _mm256_sub_pd(t47, t44);
        const __m256d t259 = _mm256_add_pd(t44, t47);
        const __m256d t51 = _mm256_sub_pd(t48, t40);
        const __m256d t363 = _mm256_add_pd(t40, t48);
        const __m256d t261 = _mm256_sub_pd(t259, t256);
        const __m256d t443 = _mm256_add_pd(t256, t259);
        const __m256d t980 = _mm256_fnmadd_pd(t25, t30, t51);
        const __m256d t1011 = _mm256_fmadd_pd(t25, t360, t363);
        const __m256d t264 = _mm256_sub_pd(t261, t253);
        const __m256d t445 = _mm256_sub_pd(t443, t440);
        const __m256d t534 = _mm256_add_pd(t253, t261);
        const __m256d t918 = _mm256_fmadd_pd(t25, t30, t51);
        const __m256d t955 = _mm256_fnmadd_pd(t25, t360, t363);
        const __m256d t608 = _mm256_add_pd(t440, t443);
        const __m256d t449 = _mm256_add_pd(t445, t448);
        const __m256d t453 = _mm256_sub_pd(t445, t448);
        const __m256d t742 = _mm256_fmadd_pd(t176, t266, t264);
        const __m256d t748 = _mm256_fnmadd_pd(t176, t264, t266);
        const __m256d t787 = _mm256_fmadd_pd(t176, t534, t535);
        const __m256d t793 = _mm256_fmsub_pd(t176, t535, t534);
        const __m256d t920 = _mm256_fmadd_pd(t918, t55, t919);
        const __m256d t938 = _mm256_fmsub_pd(t919, t55, t918);
        const __m256d t956 = _mm256_fnmadd_pd(t116, t954, t955);
        const __m256d t968 = _mm256_fmadd_pd(t116, t955, t954);
        const __m256d t983 = _mm256_mul_pd(t119, _mm256_fnmadd_pd(t116, t980, t981));
        const __m256d t999 = _mm256_mul_pd(t119, _mm256_fnmsub_pd(t116, t981, t980));
        const __m256d t1013 = _mm256_mul_pd(t58, _mm256_fmadd_pd(t55, t1010, t1011));
        const __m256d t1029 = _mm256_mul_pd(t58, _mm256_fnmadd_pd(t55, t1011, t1010));
        const __m256d t66 = lane_re_29;
        const __m256d t67 = lane_im_29;
        const __m256d t69 = lane_re_13;
        const __m256d t73 = _mm256_sub_pd(t69, t66);
        const __m256d t275 = _mm256_add_pd(t66, t69);
        const __m256d t70 = lane_im_13;
        const __m256d t71 = _mm256_sub_pd(t70, t67);
        const __m256d t274 = _mm256_add_pd(t67, t70);
        const __m256d t76 = lane_re_21;
        const __m256d t77 = lane_im_21;
        const __m256d t79 = lane_re_5;
        const __m256d t83 = _mm256_sub_pd(t79, t76);
        const __m256d t278 = _mm256_add_pd(t76, t79);
        const __m256d t86 = _mm256_add_pd(t71, t83);
        const __m256d t381 = _mm256_sub_pd(t83, t71);
        const __m256d t281 = _mm256_sub_pd(t278, t275);
        const __m256d t457 = _mm256_add_pd(t275, t278);
        const __m256d t80 = lane_im_5;
        const __m256d t81 = _mm256_sub_pd(t80, t77);
        const __m256d t277 = _mm256_add_pd(t77, t80);
        const __m256d t84 = _mm256_sub_pd(t81, t73);
        const __m256d t380 = _mm256_add_pd(t73, t81);
        const __m256d t279 = _mm256_sub_pd(t277, t274);
        const __m256d t456 = _mm256_add_pd(t274, t277);
        const __m256d t87 = _mm256_add_pd(t84, t86);
        const __m256d t91 = _mm256_sub_pd(t84, t86);
        const __m256d t382 = _mm256_sub_pd(t381, t380);
        const __m256d t384 = _mm256_add_pd(t380, t381);
        const __m256d t94 = lane_re_25;
        const __m256d t95 = lane_im_25;
        const __m256d t97 = lane_re_9;
        const __m256d t101 = _mm256_sub_pd(t97, t94);
        const __m256d t285 = _mm256_add_pd(t94, t97);
        const __m256d t98 = lane_im_9;
        const __m256d t99 = _mm256_sub_pd(t98, t95);
        const __m256d t284 = _mm256_add_pd(t95, t98);
        const __m256d t104 = lane_re_17;
        const __m256d t105 = lane_im_17;
        const __m256d t107 = lane_re_1;
        const __m256d t111 = _mm256_sub_pd(t107, t104);
        const __m256d t288 = _mm256_add_pd(t104, t107);
        const __m256d t113 = _mm256_add_pd(t99, t111);
        const __m256d t291 = _mm256_sub_pd(t288, t285);
        const __m256d t388 = _mm256_sub_pd(t111, t99);
        const __m256d t460 = _mm256_add_pd(t285, t288);
        const __m256d t293 = _mm256_add_pd(t279, t291);
        const __m256d t463 = _mm256_sub_pd(t460, t457);
        const __m256d t545 = _mm256_sub_pd(t291, t279);
        const __m256d t923 = _mm256_fmadd_pd(t25, t87, t113);
        const __m256d t959 = _mm256_fnmadd_pd(t25, t382, t388);
        const __m256d t976 = _mm256_fnmadd_pd(t25, t87, t113);
        const __m256d t1006 = _mm256_fmadd_pd(t25, t382, t388);
        const __m256d t612 = _mm256_add_pd(t457, t460);
        const __m256d t615 = _mm256_sub_pd(t612, t609);
        const __m256d t685 = _mm256_add_pd(t609, t612);
        const __m256d t108 = lane_im_1;
        const __m256d t109 = _mm256_sub_pd(t108, t105);
        const __m256d t287 = _mm256_add_pd(t105, t108);
        const __m256d t112 = _mm256_sub_pd(t109, t101);
        const __m256d t289 = _mm256_sub_pd(t287, t284);
        const __m256d t387 = _mm256_add_pd(t101, t109);
        const __m256d t459 = _mm256_add_pd(t284, t287);
        const __m256d t292 = _mm256_sub_pd(t289, t281);
        const __m256d t461 = _mm256_sub_pd(t459, t456);
        const __m256d t543 = _mm256_add_pd(t281, t289);
        const __m256d t922 = _mm256_fmadd_pd(t25, t91, t112);
        const __m256d t958 = _mm256_fnmadd_pd(t25, t384, t387);
        const __m256d t977 = _mm256_fnmadd_pd(t25, t91, t112);
        const __m256d t1007 = _mm256_fmadd_pd(t25, t384, t387);
        const __m256d t611 = _mm256_add_pd(t456, t459);
        const __m256d t464 = _mm256_sub_pd(t463, t461);
        const __m256d t466 = _mm256_add_pd(t461, t463);
        const __m256d t744 = _mm256_fmadd_pd(t176, t292, t293);
        const __m256d t750 = _mm256_fmsub_pd(t176, t293, t292);
        const __m256d t785 = _mm256_fmadd_pd(t176, t545, t543);
        const __m256d t791 = _mm256_fnmadd_pd(t176, t543, t545);
        const __m256d t924 = _mm256_fmadd_pd(t922, t116, t923);
        const __m256d t940 = _mm256_fmsub_pd(t923, t116, t922);
        const __m256d t960 = _mm256_fmadd_pd(t55, t958, t959);
        const __m256d t970 = _mm256_fmsub_pd(t55, t959, t958);
        const __m256d t978 = _mm256_fmadd_pd(t55, t976, t977);
        const __m256d t996 = _mm256_fnmadd_pd(t55, t977, t976);
        const __m256d t1008 = _mm256_fmadd_pd(t116, t1006, t1007);
        const __m256d t1026 = _mm256_fnmadd_pd(t116, t1007, t1006);
        const __m256d t613 = _mm256_sub_pd(t611, t608);
        const __m256d t684 = _mm256_add_pd(t608, t611);
        const __m256d t870 = _mm256_add_pd(t742, t744);
        const __m256d t873 = _mm256_add_pd(t748, t750);
        const __m256d t876 = _mm256_add_pd(t453, t466);
        const __m256d t879 = _mm256_add_pd(t449, t464);
        const __m256d t882 = _mm256_sub_pd(t785, t787);
        const __m256d t885 = _mm256_sub_pd(t791, t793);
        const __m256d t888 = _mm256_sub_pd(t750, t748);
        const __m256d t891 = _mm256_sub_pd(t744, t742);
        const __m256d t894 = _mm256_sub_pd(t464, t449);
        const __m256d t897 = _mm256_sub_pd(t466, t453);
        const __m256d t900 = _mm256_add_pd(t791, t793);
        const __m256d t903 = _mm256_add_pd(t785, t787);
        const __m256d t1106 = _mm256_fmsub_pd(t58, t978, t983);
        const __m256d t1110 = _mm256_fmsub_pd(t58, t996, t999);
        const __m256d t1112 = _mm256_fmsub_pd(t119, t1008, t1013);
        const __m256d t1116 = _mm256_fmsub_pd(t119, t1026, t1029);
        const __m256d t1131 = _mm256_fmadd_pd(t58, t996, t999);
        const __m256d t1134 = _mm256_fmadd_pd(t58, t978, t983);
        const __m256d t1137 = _mm256_fmadd_pd(t119, t1026, t1029);
        const __m256d t1140 = _mm256_fmadd_pd(t119, t1008, t1013);
        const __m256d t127 = lane_re_30;
        const __m256d t128 = lane_im_30;
        const __m256d t130 = lane_re_14;
        const __m256d t134 = _mm256_sub_pd(t130, t127);
        const __m256d t304 = _mm256_add_pd(t127, t130);
        const __m256d t131 = lane_im_14;
        const __m256d t132 = _mm256_sub_pd(t131, t128);
        const __m256d t303 = _mm256_add_pd(t128, t131);
        const __m256d t137 = lane_re_22;
        const __m256d t138 = lane_im_22;
        const __m256d t140 = lane_re_6;
        const __m256d t144 = _mm256_sub_pd(t140, t137);
        const __m256d t147 = _mm256_add_pd(t132, t144);
        const __m256d t402 = _mm256_sub_pd(t144, t132);
        const __m256d t307 = _mm256_add_pd(t137, t140);
        const __m256d t310 = _mm256_sub_pd(t307, t304);
        const __m256d t472 = _mm256_add_pd(t304, t307);
        const __m256d t141 = lane_im_6;
        const __m256d t142 = _mm256_sub_pd(t141, t138);
        const __m256d t145 = _mm256_sub_pd(t142, t134);
        const __m256d t401 = _mm256_add_pd(t134, t142);
        const __m256d t306 = _mm256_add_pd(t138, t141);
        const __m256d t148 = _mm256_add_pd(t145, t147);
        const __m256d t152 = _mm256_sub_pd(t145, t147);
        const __m256d t403 = _mm256_sub_pd(t402, t401);
        const __m256d t405 = _mm256_add_pd(t401, t402);
        const __m256d t308 = _mm256_sub_pd(t306, t303);
        const __m256d t471 = _mm256_add_pd(t303, t306);
        const __m256d t155 = lane_re_26;
        const __m256d t156 = lane_im_26;
        const __m256d t158 = lane_re_10;
        const __m256d t162 = _mm256_sub_pd(t158, t155);
        const __m256d t314 = _mm256_add_pd(t155, t158);
        const __m256d t159 = lane_im_10;
        const __m256d t160 = _mm256_sub_pd(t159, t156);
        const __m256d t313 = _mm256_add_pd(t156, t159);
        const __m256d t165 = lane_re_18;
        const __m256d t166 = lane_im_18;
        const __m256d t168 = lane_re_2;
        const __m256d t172 = _mm256_sub_pd(t168, t165);
        const __m256d t317 = _mm256_add_pd(t165, t168);
        const __m256d t174 = _mm256_add_pd(t160, t172);
        const __m256d t409 = _mm256_sub_pd(t172, t160);
        const __m256d t320 = _mm256_sub_pd(t317, t314);
        const __m256d t929 = _mm256_fmadd_pd(t25, t148, t174);
        const __m256d t949 = _mm256_fnmadd_pd(t25, t403, t409);
        const __m256d t475 = _mm256_add_pd(t314, t317);
        const __m256d t323 = _mm256_add_pd(t308, t320);
        const __m256d t556 = _mm256_sub_pd(t320, t308);
        const __m256d t986 = _mm256_fnmadd_pd(t25, t148, t174);
        const __m256d t1017 = _mm256_fmadd_pd(t25, t403, t409);
        const __m256d t478 = _mm256_sub_pd(t475, t472);
        const __m256d t618 = _mm256_add_pd(t472, t475);
        const __m256d t169 = lane_im_2;
        const __m256d t170 = _mm256_sub_pd(t169, t166);
        const __m256d t316 = _mm256_add_pd(t166, t169);
        const __m256d t173 = _mm256_sub_pd(t170, t162);
        const __m256d t408 = _mm256_add_pd(t162, t170);
        const __m256d t318 = _mm256_sub_pd(t316, t313);
        const __m256d t928 = _mm256_fmadd_pd(t25, t152, t173);
        const __m256d t950 = _mm256_fnmadd_pd(t25, t405, t408);
        const __m256d t474 = _mm256_add_pd(t313, t316);
        const __m256d t321 = _mm256_sub_pd(t318, t310);
        const __m256d t555 = _mm256_add_pd(t310, t318);
        const __m256d t987 = _mm256_fnmadd_pd(t25, t152, t173);
        const __m256d t1016 = _mm256_fmadd_pd(t25, t405, t408);
        const __m256d t930 = _mm256_fmadd_pd(t928, t176, t929);
        const __m256d t935 = _mm256_fnmadd_pd(t176, t929, t928);
        const __m256d t951 = _mm256_fnmsub_pd(t176, t949, t950);
        const __m256d t965 = _mm256_fnmadd_pd(t176, t950, t949);
        const __m256d t476 = _mm256_sub_pd(t474, t471);
        const __m256d t617 = _mm256_add_pd(t471, t474);
        const __m256d t324 = _mm256_add_pd(t321, t323);
        const __m256d t328 = _mm256_sub_pd(t321, t323);
        const __m256d t557 = _mm256_sub_pd(t556, t555);
        const __m256d t559 = _mm256_add_pd(t555, t556);
        const __m256d t988 = _mm256_fmsub_pd(t176, t986, t987);
        const __m256d t993 = _mm256_fmadd_pd(t176, t987, t986);
        const __m256d t1018 = _mm256_fnmadd_pd(t176, t1016, t1017);
        const __m256d t1023 = _mm256_fmadd_pd(t176, t1017, t1016);
        const __m256d t191 = lane_re_28;
        const __m256d t192 = lane_im_28;
        const __m256d t194 = lane_re_12;
        const __m256d t198 = _mm256_sub_pd(t194, t191);
        const __m256d t332 = _mm256_add_pd(t191, t194);
        const __m256d t195 = lane_im_12;
        const __m256d t196 = _mm256_sub_pd(t195, t192);
        const __m256d t331 = _mm256_add_pd(t192, t195);
        const __m256d t201 = lane_re_20;
        const __m256d t202 = lane_im_20;
        const __m256d t204 = lane_re_4;
        const __m256d t208 = _mm256_sub_pd(t204, t201);
        const __m256d t211 = _mm256_add_pd(t196, t208);
        const __m256d t423 = _mm256_sub_pd(t208, t196);
        const __m256d t335 = _mm256_add_pd(t201, t204);
        const __m256d t338 = _mm256_sub_pd(t335, t332);
        const __m256d t482 = _mm256_add_pd(t332, t335);
        const __m256d t205 = lane_im_4;
        const __m256d t206 = _mm256_sub_pd(t205, t202);
        const __m256d t209 = _mm256_sub_pd(t206, t198);
        const __m256d t422 = _mm256_add_pd(t198, t206);
        const __m256d t334 = _mm256_add_pd(t202, t205);
        const __m256d t212 = _mm256_add_pd(t209, t211);
        const __m256d t216 = _mm256_sub_pd(t209, t211);
        const __m256d t424 = _mm256_sub_pd(t423, t422);
        const __m256d t426 = _mm256_add_pd(t422, t423);
        const __m256d t336 = _mm256_sub_pd(t334, t331);
        const __m256d t481 = _mm256_add_pd(t331, t334);
        const __m256d t219 = lane_re_24;
        const __m256d t220 = lane_im_24;
        const __m256d t222 = lane_re_8;
        const __m256d t226 = _mm256_sub_pd(t222, t219);
        const __m256d t342 = _mm256_add_pd(t219, t222);
        const __m256d t223 = lane_im_8;
        const __m256d t224 = _mm256_sub_pd(t223, t220);
        const __m256d t341 = _mm256_add_pd(t220, t223);
        const __m256d t229 = lane_re_16;
        const __m256d t230 = lane_im_16;
        const __m256d t232 = lane_re_0;
        const __m256d t236 = _mm256_sub_pd(t232, t229);
        const __m256d t345 = _mm256_add_pd(t229, t232);
        const __m256d t238 = _mm256_add_pd(t224, t236);
        const __m256d t430 = _mm256_sub_pd(t236, t224);
        const __m256d t348 = _mm256_sub_pd(t345, t342);
        const __m256d t485 = _mm256_add_pd(t342, t345);
        const __m256d t927 = _mm256_fmadd_pd(t25, t212, t238);
        const __m256d t948 = _mm256_fnmadd_pd(t25, t424, t430);
        const __m256d t350 = _mm256_add_pd(t336, t348);
        const __m256d t488 = _mm256_sub_pd(t485, t482);
        const __m256d t563 = _mm256_sub_pd(t348, t336);
        const __m256d t621 = _mm256_add_pd(t482, t485);
        const __m256d t985 = _mm256_fnmadd_pd(t25, t212, t238);
        const __m256d t1015 = _mm256_fmadd_pd(t25, t424, t430);
        const __m256d t1095 = _mm256_fmadd_pd(t182, t930, t927);
        const __m256d t1100 = _mm256_fnmadd_pd(t182, t951, t948);
        const __m256d t1118 = _mm256_fnmadd_pd(t182, t930, t927);
        const __m256d t1124 = _mm256_fmadd_pd(t182, t951, t948);
        const __m256d t490 = _mm256_add_pd(t476, t488);
        const __m256d t974 = _mm256_fmadd_pd(t25, t876, t490);
        const __m256d t1072 = _mm256_fnmadd_pd(t25, t876, t490);
        const __m256d t624 = _mm256_sub_pd(t621, t618);
        const __m256d t625 = _mm256_add_pd(t613, t624);
        const __m256d t706 = _mm256_sub_pd(t624, t613);
        const __m256d t656 = _mm256_sub_pd(t488, t476);
        const __m256d t1048 = _mm256_fnmadd_pd(t25, t894, t656);
        const __m256d t1086 = _mm256_fmadd_pd(t25, t894, t656);
        const __m256d t688 = _mm256_add_pd(t618, t621);
        const __m256d t689 = _mm256_sub_pd(t688, t685);
        const __m256d t722 = _mm256_add_pd(t685, t688);
        const __m256d t944 = _mm256_fmadd_pd(t25, t324, t350);
        const __m256d t945 = _mm256_fmadd_pd(t182, t870, t944);
        const __m256d t1068 = _mm256_fnmadd_pd(t182, t870, t944);
        const __m256d t1002 = _mm256_fnmadd_pd(t25, t557, t563);
        const __m256d t1003 = _mm256_fmadd_pd(t182, t882, t1002);
        const __m256d t1076 = _mm256_fnmadd_pd(t182, t882, t1002);
        const __m256d t1038 = _mm256_fnmadd_pd(t25, t324, t350);
        const __m256d t1039 = _mm256_fnmadd_pd(t182, t888, t1038);
        const __m256d t1082 = _mm256_fmadd_pd(t182, t888, t1038);
        const __m256d t1056 = _mm256_fmadd_pd(t25, t557, t563);
        const __m256d t1057 = _mm256_fnmadd_pd(t182, t900, t1056);
        const __m256d t1090 = _mm256_fmadd_pd(t182, t900, t1056);
        const __m256d t1107 = _mm256_fnmadd_pd(t182, t988, t985);
        const __m256d t1108 = _mm256_add_pd(t1106, t1107);
        const __m256d t1146 = _mm256_sub_pd(t1107, t1106);
        const __m256d t1113 = _mm256_fnmadd_pd(t182, t1018, t1015);
        const __m256d t1114 = _mm256_add_pd(t1112, t1113);
        const __m256d t1148 = _mm256_sub_pd(t1113, t1112);
        const __m256d t1130 = _mm256_fmadd_pd(t182, t988, t985);
        const __m256d t1132 = _mm256_sub_pd(t1130, t1131);
        const __m256d t1154 = _mm256_add_pd(t1130, t1131);
        const __m256d t1136 = _mm256_fmadd_pd(t182, t1018, t1015);
        const __m256d t1138 = _mm256_sub_pd(t1136, t1137);
        const __m256d t1156 = _mm256_add_pd(t1136, t1137);
        const __m256d t1159 = _mm256_fmadd_pd(t119, t924, _mm256_fmadd_pd(t58, t920, t1095));
        const __m256d t1163 = _mm256_fmadd_pd(t58, t960, _mm256_fmadd_pd(t119, t956, t1100));
        const __m256d t1167 = _mm256_fmadd_pd(t58, t938, _mm256_fnmadd_pd(t119, t940, t1118));
        const __m256d t1171 = _mm256_fmadd_pd(t119, t968, _mm256_fnmadd_pd(t58, t970, t1124));
        const __m256d t1175 = _mm256_fnmadd_pd(t119, t924, _mm256_fnmadd_pd(t58, t920, t1095));
        const __m256d t1179 = _mm256_fnmadd_pd(t58, t960, _mm256_fnmadd_pd(t119, t956, t1100));
        const __m256d t1183 = _mm256_fnmadd_pd(t58, t938, _mm256_fmadd_pd(t119, t940, t1118));
        const __m256d t1187 = _mm256_fnmadd_pd(t119, t968, _mm256_fmadd_pd(t58, t970, t1124));
        const __m256d t233 = lane_im_0;
        const __m256d t234 = _mm256_sub_pd(t233, t230);
        const __m256d t344 = _mm256_add_pd(t230, t233);
        const __m256d t237 = _mm256_sub_pd(t234, t226);
        const __m256d t429 = _mm256_add_pd(t226, t234);
        const __m256d t346 = _mm256_sub_pd(t344, t341);
        const __m256d t484 = _mm256_add_pd(t341, t344);
        const __m256d t934 = _mm256_fmadd_pd(t25, t216, t237);
        const __m256d t964 = _mm256_fnmadd_pd(t25, t426, t429);
        const __m256d t349 = _mm256_sub_pd(t346, t338);
        const __m256d t486 = _mm256_sub_pd(t484, t481);
        const __m256d t562 = _mm256_add_pd(t338, t346);
        const __m256d t620 = _mm256_add_pd(t481, t484);
        const __m256d t992 = _mm256_fnmadd_pd(t25, t216, t237);
        const __m256d t1022 = _mm256_fmadd_pd(t25, t426, t429);
        const __m256d t1097 = _mm256_fmadd_pd(t182, t935, t934);
        const __m256d t1103 = _mm256_fnmadd_pd(t182, t965, t964);
        const __m256d t1121 = _mm256_fnmadd_pd(t182, t935, t934);
        const __m256d t1127 = _mm256_fmadd_pd(t182, t965, t964);
        const __m256d t489 = _mm256_sub_pd(t486, t478);
        const __m256d t975 = _mm256_fnmadd_pd(t25, t879, t489);
        const __m256d t1073 = _mm256_fmadd_pd(t25, t879, t489);
        const __m256d t622 = _mm256_sub_pd(t620, t617);
        const __m256d t627 = _mm256_sub_pd(t622, t615);
        const __m256d t707 = _mm256_add_pd(t615, t622);
        const __m256d t655 = _mm256_add_pd(t478, t486);
        const __m256d t1049 = _mm256_fnmadd_pd(t25, t897, t655);
        const __m256d t1087 = _mm256_fmadd_pd(t25, t897, t655);
        const __m256d t687 = _mm256_add_pd(t617, t620);
        const __m256d t691 = _mm256_sub_pd(t687, t684);
        const __m256d t723 = _mm256_add_pd(t684, t687);
        const __m256d t946 = _mm256_fmadd_pd(t25, t328, t349);
        const __m256d t947 = _mm256_fnmadd_pd(t182, t873, t946);
        const __m256d t1069 = _mm256_fmadd_pd(t182, t873, t946);
        const __m256d t1004 = _mm256_fnmadd_pd(t25, t559, t562);
        const __m256d t1005 = _mm256_fnmadd_pd(t182, t885, t1004);
        const __m256d t1077 = _mm256_fmadd_pd(t182, t885, t1004);
        const __m256d t1040 = _mm256_fnmadd_pd(t25, t328, t349);
        const __m256d t1041 = _mm256_fnmadd_pd(t182, t891, t1040);
        const __m256d t1083 = _mm256_fmadd_pd(t182, t891, t1040);
        const __m256d t1058 = _mm256_fmadd_pd(t25, t559, t562);
        const __m256d t1059 = _mm256_fnmadd_pd(t182, t903, t1058);
        const __m256d t1091 = _mm256_fmadd_pd(t182, t903, t1058);
        const __m256d t1109 = _mm256_fnmadd_pd(t182, t993, t992);
        const __m256d t1111 = _mm256_sub_pd(t1109, t1110);
        const __m256d t1147 = _mm256_add_pd(t1109, t1110);
        const __m256d t1115 = _mm256_fnmadd_pd(t182, t1023, t1022);
        const __m256d t1117 = _mm256_sub_pd(t1115, t1116);
        const __m256d t1149 = _mm256_add_pd(t1115, t1116);
        const __m256d t1133 = _mm256_fmadd_pd(t182, t993, t992);
        const __m256d t1135 = _mm256_sub_pd(t1133, t1134);
        const __m256d t1155 = _mm256_add_pd(t1133, t1134);
        const __m256d t1139 = _mm256_fmadd_pd(t182, t1023, t1022);
        const __m256d t1141 = _mm256_sub_pd(t1139, t1140);
        const __m256d t1157 = _mm256_add_pd(t1139, t1140);
        const __m256d t1161 = _mm256_fnmadd_pd(t119, t940, _mm256_fnmadd_pd(t58, t938, t1097));
        const __m256d t1165 = _mm256_fnmadd_pd(t58, t970, _mm256_fnmadd_pd(t119, t968, t1103));
        const __m256d t1169 = _mm256_fmadd_pd(t58, t920, _mm256_fnmadd_pd(t119, t924, t1121));
        const __m256d t1173 = _mm256_fmadd_pd(t119, t956, _mm256_fnmadd_pd(t58, t960, t1127));
        const __m256d t1177 = _mm256_fmadd_pd(t119, t940, _mm256_fmadd_pd(t58, t938, t1097));
        const __m256d t1181 = _mm256_fmadd_pd(t58, t970, _mm256_fmadd_pd(t119, t968, t1103));
        const __m256d t1185 = _mm256_fnmadd_pd(t58, t920, _mm256_fmadd_pd(t119, t924, t1121));
        const __m256d t1189 = _mm256_fnmadd_pd(t119, t956, _mm256_fmadd_pd(t58, t960, t1127));

        out_lane_re_31 = t1159;
        out_lane_im_31 = t1161;
        out_lane_re_30 = t945;
        out_lane_im_30 = t947;
        out_lane_re_29 = t1163;
        out_lane_im_29 = t1165;
        out_lane_re_28 = t974;
        out_lane_im_28 = t975;
        out_lane_re_27 = t1108;
        out_lane_im_27 = t1111;
        out_lane_re_26 = t1003;
        out_lane_im_26 = t1005;
        out_lane_re_25 = t1114;
        out_lane_im_25 = t1117;
        out_lane_re_24 = t625;
        out_lane_im_24 = t627;
        out_lane_re_23 = t1167;
        out_lane_im_23 = t1169;
        out_lane_re_22 = t1039;
        out_lane_im_22 = t1041;
        out_lane_re_21 = t1171;
        out_lane_im_21 = t1173;
        out_lane_re_20 = t1048;
        out_lane_im_20 = t1049;
        out_lane_re_19 = t1132;
        out_lane_im_19 = t1135;
        out_lane_re_18 = t1057;
        out_lane_im_18 = t1059;
        out_lane_re_17 = t1138;
        out_lane_im_17 = t1141;
        out_lane_re_16 = t689;
        out_lane_im_16 = t691;
        out_lane_re_15 = t1175;
        out_lane_im_15 = t1177;
        out_lane_re_14 = t1068;
        out_lane_im_14 = t1069;
        out_lane_re_13 = t1179;
        out_lane_im_13 = t1181;
        out_lane_re_12 = t1072;
        out_lane_im_12 = t1073;
        out_lane_re_11 = t1146;
        out_lane_im_11 = t1147;
        out_lane_re_10 = t1076;
        out_lane_im_10 = t1077;
        out_lane_re_9 = t1148;
        out_lane_im_9 = t1149;
        out_lane_re_8 = t706;
        out_lane_im_8 = t707;
        out_lane_re_7 = t1183;
        out_lane_im_7 = t1185;
        out_lane_re_6 = t1082;
        out_lane_im_6 = t1083;
        out_lane_re_5 = t1187;
        out_lane_im_5 = t1189;
        out_lane_re_4 = t1086;
        out_lane_im_4 = t1087;
        out_lane_re_3 = t1154;
        out_lane_im_3 = t1155;
        out_lane_re_2 = t1090;
        out_lane_im_2 = t1091;
        out_lane_re_1 = t1156;
        out_lane_im_1 = t1157;
        out_lane_re_0 = t722;
        out_lane_im_0 = t723;

        {  /* inverse 4x4 transpose group: fft_idx 0..3, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_0, out_lane_re_1);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_0, out_lane_re_1);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_2, out_lane_re_3);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_2, out_lane_re_3);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 0], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 0], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 0], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 0], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 4..7, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_4, out_lane_re_5);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_4, out_lane_re_5);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_6, out_lane_re_7);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_6, out_lane_re_7);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 4], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 4], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 4], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 4], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 8..11, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_8, out_lane_re_9);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_8, out_lane_re_9);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_10, out_lane_re_11);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_10, out_lane_re_11);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 8], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 8], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 8], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 8], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 12..15, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_12, out_lane_re_13);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_12, out_lane_re_13);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_14, out_lane_re_15);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_14, out_lane_re_15);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 12], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 12], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 12], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 12], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 16..19, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_16, out_lane_re_17);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_16, out_lane_re_17);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_18, out_lane_re_19);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_18, out_lane_re_19);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 16], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 16], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 16], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 16], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 20..23, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_20, out_lane_re_21);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_20, out_lane_re_21);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_22, out_lane_re_23);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_22, out_lane_re_23);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 20], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 20], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 20], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 20], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 24..27, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_24, out_lane_re_25);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_24, out_lane_re_25);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_26, out_lane_re_27);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_26, out_lane_re_27);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 24], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 24], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 24], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 24], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 28..31, re */
            const __m256d _u0_re = _mm256_unpacklo_pd(out_lane_re_28, out_lane_re_29);
            const __m256d _u1_re = _mm256_unpackhi_pd(out_lane_re_28, out_lane_re_29);
            const __m256d _u2_re = _mm256_unpacklo_pd(out_lane_re_30, out_lane_re_31);
            const __m256d _u3_re = _mm256_unpackhi_pd(out_lane_re_30, out_lane_re_31);
            _mm256_storeu_pd(&rio_re[(b+0)*row_stride + 28], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+1)*row_stride + 28], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x20));
            _mm256_storeu_pd(&rio_re[(b+2)*row_stride + 28], _mm256_permute2f128_pd(_u0_re, _u2_re, 0x31));
            _mm256_storeu_pd(&rio_re[(b+3)*row_stride + 28], _mm256_permute2f128_pd(_u1_re, _u3_re, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 0..3, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_0, out_lane_im_1);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_0, out_lane_im_1);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_2, out_lane_im_3);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_2, out_lane_im_3);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 0], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 0], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 0], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 0], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 4..7, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_4, out_lane_im_5);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_4, out_lane_im_5);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_6, out_lane_im_7);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_6, out_lane_im_7);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 4], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 4], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 4], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 4], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 8..11, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_8, out_lane_im_9);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_8, out_lane_im_9);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_10, out_lane_im_11);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_10, out_lane_im_11);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 8], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 8], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 8], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 8], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 12..15, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_12, out_lane_im_13);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_12, out_lane_im_13);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_14, out_lane_im_15);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_14, out_lane_im_15);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 12], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 12], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 12], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 12], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 16..19, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_16, out_lane_im_17);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_16, out_lane_im_17);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_18, out_lane_im_19);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_18, out_lane_im_19);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 16], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 16], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 16], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 16], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 20..23, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_20, out_lane_im_21);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_20, out_lane_im_21);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_22, out_lane_im_23);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_22, out_lane_im_23);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 20], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 20], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 20], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 20], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 24..27, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_24, out_lane_im_25);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_24, out_lane_im_25);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_26, out_lane_im_27);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_26, out_lane_im_27);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 24], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 24], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 24], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 24], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
        {  /* inverse 4x4 transpose group: fft_idx 28..31, im */
            const __m256d _u0_im = _mm256_unpacklo_pd(out_lane_im_28, out_lane_im_29);
            const __m256d _u1_im = _mm256_unpackhi_pd(out_lane_im_28, out_lane_im_29);
            const __m256d _u2_im = _mm256_unpacklo_pd(out_lane_im_30, out_lane_im_31);
            const __m256d _u3_im = _mm256_unpackhi_pd(out_lane_im_30, out_lane_im_31);
            _mm256_storeu_pd(&rio_im[(b+0)*row_stride + 28], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+1)*row_stride + 28], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x20));
            _mm256_storeu_pd(&rio_im[(b+2)*row_stride + 28], _mm256_permute2f128_pd(_u0_im, _u2_im, 0x31));
            _mm256_storeu_pd(&rio_im[(b+3)*row_stride + 28], _mm256_permute2f128_pd(_u1_im, _u3_im, 0x31));
        }
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=388  flops=540  (add=116 sub=116 mul=4 fma=152 cmul=0 neg=0)
 *   essential_io=128 ops (vec_loads=64 + stores=64)  [+0 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=0 slots => +0 mem ops, 0 vectors live across pass boundary
 *   memory_floor=128 mem ops   peak_live(max-per-pass)=140   budget=14 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: SPILLS (peak_live > budget)
 */
