/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 12 --cil-r2z --cil-bwd --isa avx2 --uarch raptor_lake_avx2 --emit-c
 * Env overrides: (none)
 * Family: full-IL (interleaved-complex) r2z, radix-12 bwd
 * ISA: avx2; 4 real columns per vector
 * Uarch: raptor_lake_avx2
 * Form: the real pair's real leaf (real_il.ml, cx_real.ml)
 * ====================================================== */
/* Auto-generated by vfft_v2 — INTERLEAVED-COMPLEX (full-IL) family,
 * PIPELINE-HOSTED (real_il.ml). radix-12 r2z bwd: the corner-turned half spectra (slot p of column c at
 * zin[2*(p*Ls + c)], slot 0 packed) -> R real rows zout[l*OLs + k],
 * the unnormalized inverse (R times x).
 * count = the real columns (a multiple of 2; four per wide iteration,
 * a two-column remainder at VEX-128). tw_re, tw_im, Gs, OGs unused. */
#include <immintrin.h>
#include <stddef.h>

static const __m256d _ZW0_c = { 2, 2, 2, 2 };
static const __m256d _ZW0_s = { -0, 0, -0, 0 };
static const __m256d _ZW1_c = { 0.50000000000000011, 0.50000000000000011, 0.50000000000000011, 0.50000000000000011 };
static const __m256d _ZW1_s = { -0, 0, -0, 0 };
static const __m256d _ZW2_c = { 0.86602540378443871, 0.86602540378443871, 0.86602540378443871, 0.86602540378443871 };
static const __m256d _ZW2_s = { -0, 0, -0, 0 };
static const __m256d _ZW3_c = { 1.7320508075688774, 1.7320508075688774, 1.7320508075688774, 1.7320508075688774 };
static const __m256d _ZW3_s = { -0, 0, -0, 0 };
static const __m128d _ZW4_c = { 2, 2 };
static const __m128d _ZW4_s = { -0, 0 };
static const __m128d _ZW5_c = { 0.50000000000000011, 0.50000000000000011 };
static const __m128d _ZW5_s = { -0, 0 };
static const __m128d _ZW6_c = { 0.86602540378443871, 0.86602540378443871 };
static const __m128d _ZW6_s = { -0, 0 };
static const __m128d _ZW7_c = { 1.7320508075688774, 1.7320508075688774 };
static const __m128d _ZW7_s = { -0, 0 };

__attribute__((target("avx2,fma")))
void radix12_z_r2z_bwd_avx2(
    const double * __restrict__ zin,
    const double * __restrict__ zin_unused,
    double       * __restrict__ zout,
    double       * __restrict__ zout_unused,
    const double * tw_re, const double * tw_im,
    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)
{
    (void)zin_unused; (void)zout_unused; (void)tw_re; (void)tw_im; (void)Gs; (void)OGs;
    size_t k = 0;
    for (; k + 4 <= count; k += 4) {
        { /* four real columns */
        const __m256d z0 = _mm256_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m256d z1 = _mm256_loadu_pd(&zin[2*((size_t)0*Ls + k + 2)]);
        const __m256d z6 = _mm256_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m256d z7 = _mm256_loadu_pd(&zin[2*((size_t)1*Ls + k + 2)]);
        const __m256d z12 = _mm256_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m256d z13 = _mm256_loadu_pd(&zin[2*((size_t)2*Ls + k + 2)]);
        const __m256d z18 = _mm256_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m256d z19 = _mm256_loadu_pd(&zin[2*((size_t)3*Ls + k + 2)]);
        const __m256d z24 = _mm256_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m256d z25 = _mm256_loadu_pd(&zin[2*((size_t)4*Ls + k + 2)]);
        const __m256d z30 = _mm256_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m256d z31 = _mm256_loadu_pd(&zin[2*((size_t)5*Ls + k + 2)]);
        const __m256d z2 = _mm256_permute2f128_pd(z0, z1, 0x20);
        const __m256d z3 = _mm256_permute2f128_pd(z0, z1, 0x31);
        const __m256d z4 = _mm256_unpackhi_pd(z2, z3);
        const __m256d z5 = _mm256_unpacklo_pd(z2, z3);
        const __m256d z36 = _mm256_add_pd(z5, z4);
        const __m256d z37 = _mm256_sub_pd(z5, z4);
        const __m256d z8 = _mm256_permute2f128_pd(z6, z7, 0x20);
        const __m256d z9 = _mm256_permute2f128_pd(z6, z7, 0x31);
        const __m256d z10 = _mm256_unpackhi_pd(z8, z9);
        const __m256d z11 = _mm256_unpacklo_pd(z8, z9);
        const __m256d z14 = _mm256_permute2f128_pd(z12, z13, 0x20);
        const __m256d z15 = _mm256_permute2f128_pd(z12, z13, 0x31);
        const __m256d z16 = _mm256_unpackhi_pd(z14, z15);
        const __m256d z17 = _mm256_unpacklo_pd(z14, z15);
        const __m256d z20 = _mm256_permute2f128_pd(z18, z19, 0x20);
        const __m256d z21 = _mm256_permute2f128_pd(z18, z19, 0x31);
        const __m256d z22 = _mm256_unpackhi_pd(z20, z21);
        const __m256d z23 = _mm256_unpacklo_pd(z20, z21);
        const __m256d z54 = _mm256_mul_pd(_ZW0_c, z22);
        const __m256d z55 = _mm256_mul_pd(_ZW0_c, z23);
        const __m256d z56 = _mm256_xor_pd(z54, _mm256_set1_pd(-0.0));
        const __m256d z57 = _mm256_add_pd(z36, z55);
        const __m256d z58 = _mm256_sub_pd(z36, z55);
        const __m256d z77 = _mm256_add_pd(z37, z56);
        const __m256d z78 = _mm256_sub_pd(z37, z56);
        const __m256d z26 = _mm256_permute2f128_pd(z24, z25, 0x20);
        const __m256d z27 = _mm256_permute2f128_pd(z24, z25, 0x31);
        const __m256d z28 = _mm256_unpackhi_pd(z26, z27);
        const __m256d z29 = _mm256_unpacklo_pd(z26, z27);
        const __m256d z48 = _mm256_sub_pd(z17, z29);
        const __m256d z49 = _mm256_add_pd(z16, z28);
        const __m256d z50 = _mm256_mul_pd(_ZW1_c, z49);
        const __m256d z52 = _mm256_mul_pd(_ZW1_c, z48);
        const __m256d z46 = _mm256_add_pd(z17, z29);
        const __m256d z47 = _mm256_sub_pd(z16, z28);
        const __m256d z51 = _mm256_fmadd_pd(_mm256_set1_pd(0.8660254037844386), z48, z50);
        const __m256d z53 = _mm256_fmadd_pd(_mm256_set1_pd(-0.8660254037844386), z49, z52);
        const __m256d z32 = _mm256_permute2f128_pd(z30, z31, 0x20);
        const __m256d z33 = _mm256_permute2f128_pd(z30, z31, 0x31);
        const __m256d z34 = _mm256_unpackhi_pd(z32, z33);
        const __m256d z35 = _mm256_unpacklo_pd(z32, z33);
        const __m256d z40 = _mm256_sub_pd(z11, z35);
        const __m256d z41 = _mm256_add_pd(z10, z34);
        const __m256d z42 = _mm256_mul_pd(_ZW2_c, z41);
        const __m256d z44 = _mm256_mul_pd(_ZW2_c, z40);
        const __m256d z38 = _mm256_add_pd(z11, z35);
        const __m256d z39 = _mm256_sub_pd(z10, z34);
        const __m256d z43 = _mm256_fmadd_pd(_mm256_set1_pd(0.49999999999999994), z40, z42);
        const __m256d z45 = _mm256_fmadd_pd(_mm256_set1_pd(-0.49999999999999994), z41, z44);
        const __m256d z61 = _mm256_sub_pd(z38, z46);
        const __m256d z62 = _mm256_add_pd(z39, z47);
        const __m256d z81 = _mm256_sub_pd(z45, z53);
        const __m256d z82 = _mm256_add_pd(z43, z51);
        const __m256d z63 = _mm256_mul_pd(_ZW1_c, z62);
        const __m256d z65 = _mm256_mul_pd(_ZW1_c, z61);
        const __m256d z83 = _mm256_mul_pd(_ZW1_c, z82);
        const __m256d z85 = _mm256_mul_pd(_ZW1_c, z81);
        const __m256d z59 = _mm256_add_pd(z38, z46);
        const __m256d z67 = _mm256_fmadd_pd(_mm256_set1_pd(2), z59, z57);
        const __m256d z60 = _mm256_sub_pd(z39, z47);
        const __m256d z64 = _mm256_fmadd_pd(_mm256_set1_pd(0.8660254037844386), z61, z63);
        const __m256d z66 = _mm256_fmadd_pd(_mm256_set1_pd(-0.8660254037844386), z62, z65);
        const __m256d z72 = _mm256_fmadd_pd(_mm256_set1_pd(2), z66, z58);
        const __m256d z79 = _mm256_add_pd(z45, z53);
        const __m256d z87 = _mm256_fmadd_pd(_mm256_set1_pd(2), z79, z77);
        const __m256d z80 = _mm256_sub_pd(z43, z51);
        const __m256d z84 = _mm256_fmadd_pd(_mm256_set1_pd(0.8660254037844386), z81, z83);
        const __m256d z86 = _mm256_fmadd_pd(_mm256_set1_pd(-0.8660254037844386), z82, z85);
        const __m256d z92 = _mm256_fmadd_pd(_mm256_set1_pd(2), z86, z78);
        const __m256d z68 = _mm256_sub_pd(z57, z59);
        const __m256d z69 = _mm256_mul_pd(_ZW3_c, z60);
        const __m256d z70 = _mm256_sub_pd(z68, z69);
        const __m256d z71 = _mm256_add_pd(z68, z69);
        const __m256d z73 = _mm256_sub_pd(z58, z66);
        const __m256d z74 = _mm256_mul_pd(_ZW3_c, z64);
        const __m256d z75 = _mm256_sub_pd(z73, z74);
        const __m256d z76 = _mm256_add_pd(z73, z74);
        const __m256d z88 = _mm256_sub_pd(z77, z79);
        const __m256d z89 = _mm256_mul_pd(_ZW3_c, z80);
        const __m256d z90 = _mm256_sub_pd(z88, z89);
        const __m256d z91 = _mm256_add_pd(z88, z89);
        const __m256d z93 = _mm256_sub_pd(z78, z86);
        const __m256d z94 = _mm256_mul_pd(_ZW3_c, z84);
        const __m256d z95 = _mm256_sub_pd(z93, z94);
        const __m256d z96 = _mm256_add_pd(z93, z94);
        _mm256_storeu_pd(&zout[(size_t)0*OLs + k], z67);
        _mm256_storeu_pd(&zout[(size_t)1*OLs + k], z87);
        _mm256_storeu_pd(&zout[(size_t)2*OLs + k], z72);
        _mm256_storeu_pd(&zout[(size_t)3*OLs + k], z92);
        _mm256_storeu_pd(&zout[(size_t)4*OLs + k], z70);
        _mm256_storeu_pd(&zout[(size_t)5*OLs + k], z90);
        _mm256_storeu_pd(&zout[(size_t)6*OLs + k], z75);
        _mm256_storeu_pd(&zout[(size_t)7*OLs + k], z95);
        _mm256_storeu_pd(&zout[(size_t)8*OLs + k], z71);
        _mm256_storeu_pd(&zout[(size_t)9*OLs + k], z91);
        _mm256_storeu_pd(&zout[(size_t)10*OLs + k], z76);
        _mm256_storeu_pd(&zout[(size_t)11*OLs + k], z96);
        }
    }
    if (k < count) {  /* two columns at VEX-128 */
        { /* the two-column remainder at VEX-128 */
        const __m128d z0 = _mm_loadu_pd(&zin[2*((size_t)0*Ls + k)]);
        const __m128d z1 = _mm_loadu_pd(&zin[2*((size_t)0*Ls + k + 1)]);
        const __m128d z4 = _mm_loadu_pd(&zin[2*((size_t)1*Ls + k)]);
        const __m128d z5 = _mm_loadu_pd(&zin[2*((size_t)1*Ls + k + 1)]);
        const __m128d z8 = _mm_loadu_pd(&zin[2*((size_t)2*Ls + k)]);
        const __m128d z9 = _mm_loadu_pd(&zin[2*((size_t)2*Ls + k + 1)]);
        const __m128d z12 = _mm_loadu_pd(&zin[2*((size_t)3*Ls + k)]);
        const __m128d z13 = _mm_loadu_pd(&zin[2*((size_t)3*Ls + k + 1)]);
        const __m128d z16 = _mm_loadu_pd(&zin[2*((size_t)4*Ls + k)]);
        const __m128d z17 = _mm_loadu_pd(&zin[2*((size_t)4*Ls + k + 1)]);
        const __m128d z20 = _mm_loadu_pd(&zin[2*((size_t)5*Ls + k)]);
        const __m128d z21 = _mm_loadu_pd(&zin[2*((size_t)5*Ls + k + 1)]);
        const __m128d z2 = _mm_unpackhi_pd(z0, z1);
        const __m128d z3 = _mm_unpacklo_pd(z0, z1);
        const __m128d z24 = _mm_add_pd(z3, z2);
        const __m128d z25 = _mm_sub_pd(z3, z2);
        const __m128d z6 = _mm_unpackhi_pd(z4, z5);
        const __m128d z7 = _mm_unpacklo_pd(z4, z5);
        const __m128d z10 = _mm_unpackhi_pd(z8, z9);
        const __m128d z11 = _mm_unpacklo_pd(z8, z9);
        const __m128d z14 = _mm_unpackhi_pd(z12, z13);
        const __m128d z15 = _mm_unpacklo_pd(z12, z13);
        const __m128d z42 = _mm_mul_pd(_ZW4_c, z14);
        const __m128d z43 = _mm_mul_pd(_ZW4_c, z15);
        const __m128d z44 = _mm_xor_pd(z42, _mm_set1_pd(-0.0));
        const __m128d z45 = _mm_add_pd(z24, z43);
        const __m128d z46 = _mm_sub_pd(z24, z43);
        const __m128d z65 = _mm_add_pd(z25, z44);
        const __m128d z66 = _mm_sub_pd(z25, z44);
        const __m128d z18 = _mm_unpackhi_pd(z16, z17);
        const __m128d z19 = _mm_unpacklo_pd(z16, z17);
        const __m128d z36 = _mm_sub_pd(z11, z19);
        const __m128d z37 = _mm_add_pd(z10, z18);
        const __m128d z38 = _mm_mul_pd(_ZW5_c, z37);
        const __m128d z40 = _mm_mul_pd(_ZW5_c, z36);
        const __m128d z34 = _mm_add_pd(z11, z19);
        const __m128d z35 = _mm_sub_pd(z10, z18);
        const __m128d z39 = _mm_fmadd_pd(_mm_set1_pd(0.8660254037844386), z36, z38);
        const __m128d z41 = _mm_fmadd_pd(_mm_set1_pd(-0.8660254037844386), z37, z40);
        const __m128d z22 = _mm_unpackhi_pd(z20, z21);
        const __m128d z23 = _mm_unpacklo_pd(z20, z21);
        const __m128d z28 = _mm_sub_pd(z7, z23);
        const __m128d z29 = _mm_add_pd(z6, z22);
        const __m128d z30 = _mm_mul_pd(_ZW6_c, z29);
        const __m128d z32 = _mm_mul_pd(_ZW6_c, z28);
        const __m128d z26 = _mm_add_pd(z7, z23);
        const __m128d z27 = _mm_sub_pd(z6, z22);
        const __m128d z31 = _mm_fmadd_pd(_mm_set1_pd(0.49999999999999994), z28, z30);
        const __m128d z33 = _mm_fmadd_pd(_mm_set1_pd(-0.49999999999999994), z29, z32);
        const __m128d z49 = _mm_sub_pd(z26, z34);
        const __m128d z50 = _mm_add_pd(z27, z35);
        const __m128d z69 = _mm_sub_pd(z33, z41);
        const __m128d z70 = _mm_add_pd(z31, z39);
        const __m128d z51 = _mm_mul_pd(_ZW5_c, z50);
        const __m128d z53 = _mm_mul_pd(_ZW5_c, z49);
        const __m128d z71 = _mm_mul_pd(_ZW5_c, z70);
        const __m128d z73 = _mm_mul_pd(_ZW5_c, z69);
        const __m128d z47 = _mm_add_pd(z26, z34);
        const __m128d z55 = _mm_fmadd_pd(_mm_set1_pd(2), z47, z45);
        const __m128d z48 = _mm_sub_pd(z27, z35);
        const __m128d z52 = _mm_fmadd_pd(_mm_set1_pd(0.8660254037844386), z49, z51);
        const __m128d z54 = _mm_fmadd_pd(_mm_set1_pd(-0.8660254037844386), z50, z53);
        const __m128d z60 = _mm_fmadd_pd(_mm_set1_pd(2), z54, z46);
        const __m128d z67 = _mm_add_pd(z33, z41);
        const __m128d z75 = _mm_fmadd_pd(_mm_set1_pd(2), z67, z65);
        const __m128d z68 = _mm_sub_pd(z31, z39);
        const __m128d z72 = _mm_fmadd_pd(_mm_set1_pd(0.8660254037844386), z69, z71);
        const __m128d z74 = _mm_fmadd_pd(_mm_set1_pd(-0.8660254037844386), z70, z73);
        const __m128d z80 = _mm_fmadd_pd(_mm_set1_pd(2), z74, z66);
        const __m128d z56 = _mm_sub_pd(z45, z47);
        const __m128d z57 = _mm_mul_pd(_ZW7_c, z48);
        const __m128d z58 = _mm_sub_pd(z56, z57);
        const __m128d z59 = _mm_add_pd(z56, z57);
        const __m128d z61 = _mm_sub_pd(z46, z54);
        const __m128d z62 = _mm_mul_pd(_ZW7_c, z52);
        const __m128d z63 = _mm_sub_pd(z61, z62);
        const __m128d z64 = _mm_add_pd(z61, z62);
        const __m128d z76 = _mm_sub_pd(z65, z67);
        const __m128d z77 = _mm_mul_pd(_ZW7_c, z68);
        const __m128d z78 = _mm_sub_pd(z76, z77);
        const __m128d z79 = _mm_add_pd(z76, z77);
        const __m128d z81 = _mm_sub_pd(z66, z74);
        const __m128d z82 = _mm_mul_pd(_ZW7_c, z72);
        const __m128d z83 = _mm_sub_pd(z81, z82);
        const __m128d z84 = _mm_add_pd(z81, z82);
        _mm_storeu_pd(&zout[(size_t)0*OLs + k], z55);
        _mm_storeu_pd(&zout[(size_t)1*OLs + k], z75);
        _mm_storeu_pd(&zout[(size_t)2*OLs + k], z60);
        _mm_storeu_pd(&zout[(size_t)3*OLs + k], z80);
        _mm_storeu_pd(&zout[(size_t)4*OLs + k], z58);
        _mm_storeu_pd(&zout[(size_t)5*OLs + k], z78);
        _mm_storeu_pd(&zout[(size_t)6*OLs + k], z63);
        _mm_storeu_pd(&zout[(size_t)7*OLs + k], z83);
        _mm_storeu_pd(&zout[(size_t)8*OLs + k], z59);
        _mm_storeu_pd(&zout[(size_t)9*OLs + k], z79);
        _mm_storeu_pd(&zout[(size_t)10*OLs + k], z64);
        _mm_storeu_pd(&zout[(size_t)11*OLs + k], z84);
        }
    }
}
