/**
 * @file fft_radix11_scalar_ct_t1_dit_log3.h
 * @brief DFT-11 SCALAR t1 DIT log3 (in-place, derived twiddles)
 *
 * FFTW-style codelet for recursive CT executor.
 * Generated by gen_radix11.py --variant ct_t1_dit_log3
 */

#ifndef FFT_RADIX11_SCALAR_CT_CT_T1_DIT_LOG3_H
#define FFT_RADIX11_SCALAR_CT_CT_T1_DIT_LOG3_H

#ifndef R11S_CT_LD
#define R11S_CT_LD(p) (*(p))
#define R11S_CT_ST(p,v) (*(p)=(v))
#endif
#define LD R11S_CT_LD
#define ST R11S_CT_ST

static void
radix11_t1_dit_log3_fwd_scalar(
    double * __restrict__ rio_re, double * __restrict__ rio_im,
    const double * __restrict__ W_re, const double * __restrict__ W_im,
    size_t ios, size_t mb, size_t me, size_t ms)
{
    const double KP654860733 = +0.654860733945285100610078643512679263949394226;
    const double KP142314838 = +0.142314838273285143577240319245902355760335922;
    const double KP959492973 = +0.959492973614497368650688713387353345751762390;
    const double KP415415013 = +0.415415013001886435084486492996802553534507751;
    const double KP841253532 = +0.841253532831181205509096798778045922517776489;
    const double KP989821441 = +0.989821441880932684220795181317953392863273621;
    const double KP909631995 = +0.909631995354518330110238366614794358611106873;
    const double KP281732556 = +0.281732556841429671035115234190016053617000580;
    const double KP540640817 = +0.540640817455597555429847034247359260916709900;
    const double KP755749574 = +0.755749574354258268904516171460272744297981262;

    double x0_re,x0_im,x1_re,x1_im,x2_re,x2_im,x3_re,x3_im;
    double x4_re,x4_im,x5_re,x5_im,x6_re,x6_im,x7_re,x7_im;
    double x8_re,x8_im,x9_re,x9_im,x10_re,x10_im;
    double spill_re[10], spill_im[10];
    double T4r,T4i,Tgr,Tgi,Tdr,Tdi,Tar,Tai,T7r,T7i;
    double Tir,Tii,Tlr,Tli,Tkr,Tki,Tjr,Tji,Tmr,Tmi;
    double Thr,Thi,Tur,Tui,Tsr,Tsi,Tqr,Tqi,Tor,Toi;

    for (size_t m = mb; m < me; m++) {
        /* Load base twiddle w1, derive w2..w10 (9 cmuls) */
        const double w1r = W_re[0*me+m], w1i = W_im[0*me+m];
        double w2r, w2i;
        w2r = (w1r)*(w1r)-((w1i)*(w1i));
        w2i = (w1r)*(w1i)+((w1i)*(w1r));
        double w3r, w3i;
        w3r = (w1r)*(w2r)-((w1i)*(w2i));
        w3i = (w1r)*(w2i)+((w1i)*(w2r));
        double w4r, w4i;
        w4r = (w1r)*(w3r)-((w1i)*(w3i));
        w4i = (w1r)*(w3i)+((w1i)*(w3r));
        double w5r, w5i;
        w5r = (w1r)*(w4r)-((w1i)*(w4i));
        w5i = (w1r)*(w4i)+((w1i)*(w4r));
        double w6r, w6i;
        w6r = (w3r)*(w3r)-((w3i)*(w3i));
        w6i = (w3r)*(w3i)+((w3i)*(w3r));
        double w7r, w7i;
        w7r = (w3r)*(w4r)-((w3i)*(w4i));
        w7i = (w3r)*(w4i)+((w3i)*(w4r));
        double w8r, w8i;
        w8r = (w4r)*(w4r)-((w4i)*(w4i));
        w8i = (w4r)*(w4i)+((w4i)*(w4r));
        double w9r, w9i;
        w9r = (w4r)*(w5r)-((w4i)*(w5i));
        w9i = (w4r)*(w5i)+((w4i)*(w5r));
        double w10r, w10i;
        w10r = (w5r)*(w5r)-((w5i)*(w5i));
        w10i = (w5r)*(w5i)+((w5i)*(w5r));

        x0_re = rio_re[m*ms+0*ios]; x0_im = rio_im[m*ms+0*ios];
        x1_re = rio_re[m*ms+1*ios]; x1_im = rio_im[m*ms+1*ios];
        x2_re = rio_re[m*ms+2*ios]; x2_im = rio_im[m*ms+2*ios];
        x3_re = rio_re[m*ms+3*ios]; x3_im = rio_im[m*ms+3*ios];
        x4_re = rio_re[m*ms+4*ios]; x4_im = rio_im[m*ms+4*ios];
        x5_re = rio_re[m*ms+5*ios]; x5_im = rio_im[m*ms+5*ios];
        x6_re = rio_re[m*ms+6*ios]; x6_im = rio_im[m*ms+6*ios];
        x7_re = rio_re[m*ms+7*ios]; x7_im = rio_im[m*ms+7*ios];
        x8_re = rio_re[m*ms+8*ios]; x8_im = rio_im[m*ms+8*ios];
        x9_re = rio_re[m*ms+9*ios]; x9_im = rio_im[m*ms+9*ios];
        x10_re = rio_re[m*ms+10*ios]; x10_im = rio_im[m*ms+10*ios];
        { double tr = x1_re;
          x1_re = (x1_re)*(w1r)-((x1_im)*(w1i));
          x1_im = (tr)*(w1i)+((x1_im)*(w1r)); }
        { double tr = x2_re;
          x2_re = (x2_re)*(w2r)-((x2_im)*(w2i));
          x2_im = (tr)*(w2i)+((x2_im)*(w2r)); }
        { double tr = x3_re;
          x3_re = (x3_re)*(w3r)-((x3_im)*(w3i));
          x3_im = (tr)*(w3i)+((x3_im)*(w3r)); }
        { double tr = x4_re;
          x4_re = (x4_re)*(w4r)-((x4_im)*(w4i));
          x4_im = (tr)*(w4i)+((x4_im)*(w4r)); }
        { double tr = x5_re;
          x5_re = (x5_re)*(w5r)-((x5_im)*(w5i));
          x5_im = (tr)*(w5i)+((x5_im)*(w5r)); }
        { double tr = x6_re;
          x6_re = (x6_re)*(w6r)-((x6_im)*(w6i));
          x6_im = (tr)*(w6i)+((x6_im)*(w6r)); }
        { double tr = x7_re;
          x7_re = (x7_re)*(w7r)-((x7_im)*(w7i));
          x7_im = (tr)*(w7i)+((x7_im)*(w7r)); }
        { double tr = x8_re;
          x8_re = (x8_re)*(w8r)-((x8_im)*(w8i));
          x8_im = (tr)*(w8i)+((x8_im)*(w8r)); }
        { double tr = x9_re;
          x9_re = (x9_re)*(w9r)-((x9_im)*(w9i));
          x9_im = (tr)*(w9i)+((x9_im)*(w9r)); }
        { double tr = x10_re;
          x10_re = (x10_re)*(w10r)-((x10_im)*(w10i));
          x10_im = (tr)*(w10i)+((x10_im)*(w10r)); }

        /* DFT-11 butterfly [fwd] (AVX2/scalar: 3-phase + spill) */
        /* Phase 1 — sums and diffs of conjugate pairs */
        T4r=(x1_re)+(x10_re); T4i=(x1_im)+(x10_im);
        Tir=(x10_re)-(x1_re); Tii=(x10_im)-(x1_im);
        Tgr=(x5_re)+(x6_re); Tgi=(x5_im)+(x6_im);
        Tlr=(x6_re)-(x5_re); Tli=(x6_im)-(x5_im);
        Tdr=(x4_re)+(x7_re); Tdi=(x4_im)+(x7_im);
        Tkr=(x7_re)-(x4_re); Tki=(x7_im)-(x4_im);
        Tar=(x3_re)+(x8_re); Tai=(x3_im)+(x8_im);
        Tjr=(x8_re)-(x3_re); Tji=(x8_im)-(x3_im);
        T7r=(x2_re)+(x9_re); T7i=(x2_im)+(x9_im);
        Tmr=(x9_re)-(x2_re); Tmi=(x9_im)-(x2_im);
        /* Spill diffs Ti,Tj,Tk,Tl,Tm (slots 0-4) */
        spill_re[0]=Tir; spill_im[0]=Tii;
        spill_re[1]=Tjr; spill_im[1]=Tji;
        spill_re[2]=Tkr; spill_im[2]=Tki;
        spill_re[3]=Tlr; spill_im[3]=Tli;
        spill_re[4]=Tmr; spill_im[4]=Tmi;

        /* Phase 2 — 5 R (cosine) terms THEN y0 (compute R before overwriting x0) */
        Thr=(KP841253532)*(Tar)+((KP415415013)*(Tgr)+((((x0_re)-(KP654860733)*(T4r))-(KP142314838)*(T7r))-(KP959492973)*(Tdr)));
        Thi=(KP841253532)*(Tai)+((KP415415013)*(Tgi)+((((x0_im)-(KP654860733)*(T4i))-(KP142314838)*(T7i))-(KP959492973)*(Tdi)));
        Tur=(KP841253532)*(T7r)+((KP415415013)*(Tdr)+((((x0_re)-(KP959492973)*(T4r))-(KP654860733)*(Tar))-(KP142314838)*(Tgr)));
        Tui=(KP841253532)*(T7i)+((KP415415013)*(Tdi)+((((x0_im)-(KP959492973)*(T4i))-(KP654860733)*(Tai))-(KP142314838)*(Tgi)));
        Tsr=(KP415415013)*(Tar)+((KP841253532)*(Tdr)+((((x0_re)-(KP142314838)*(T4r))-(KP959492973)*(T7r))-(KP654860733)*(Tgr)));
        Tsi=(KP415415013)*(Tai)+((KP841253532)*(Tdi)+((((x0_im)-(KP142314838)*(T4i))-(KP959492973)*(T7i))-(KP654860733)*(Tgi)));
        Tqr=(KP841253532)*(T4r)+((KP415415013)*(T7r)+((((x0_re)-(KP142314838)*(Tar))-(KP654860733)*(Tdr))-(KP959492973)*(Tgr)));
        Tqi=(KP841253532)*(T4i)+((KP415415013)*(T7i)+((((x0_im)-(KP142314838)*(Tai))-(KP654860733)*(Tdi))-(KP959492973)*(Tgi)));
        Tor=(KP415415013)*(T4r)+((KP841253532)*(Tgr)+((((x0_re)-(KP654860733)*(T7r))-(KP959492973)*(Tar))-(KP142314838)*(Tdr)));
        Toi=(KP415415013)*(T4i)+((KP841253532)*(Tgi)+((((x0_im)-(KP654860733)*(T7i))-(KP959492973)*(Tai))-(KP142314838)*(Tdi)));
        x0_re=(x0_re)+((T4r)+((T7r)+((Tar)+((Tdr)+(Tgr)))));
        x0_im=(x0_im)+((T4i)+((T7i)+((Tai)+((Tdi)+(Tgi)))));
        /* Spill R terms Th,Tu,Ts,Tq,To (slots 5-9) */
        spill_re[5]=Thr; spill_im[5]=Thi;
        spill_re[6]=Tur; spill_im[6]=Tui;
        spill_re[7]=Tsr; spill_im[7]=Tsi;
        spill_re[8]=Tqr; spill_im[8]=Tqi;
        spill_re[9]=Tor; spill_im[9]=Toi;

        /* Phase 3 — S terms + combine (reload one diff set + R at a time) */

        /* Pair (4,7): reload Th, compute Tn, store out[4] and out[7] */
        Thr=spill_re[5]; Thi=spill_im[5];
        Tir=spill_re[0]; Tii=spill_im[0];
        Tjr=spill_re[1]; Tji=spill_im[1];
        Tkr=spill_re[2]; Tki=spill_im[2];
        Tlr=spill_re[3]; Tli=spill_im[3];
        Tmr=spill_re[4]; Tmi=spill_im[4];
        { double Tnr=-((KP755749574)*(Tii)+((KP540640817)*(Tji)+((((KP281732556)*(Tki))-(KP989821441)*(Tmi))-(KP909631995)*(Tli))));
          double Tni=(KP755749574)*(Tir)+((KP540640817)*(Tjr)+((((KP281732556)*(Tkr))-(KP989821441)*(Tmr))-(KP909631995)*(Tlr)));
          x4_re=(Thr)+(Tnr); x4_im=(Thi)+(Tni);
          x7_re=(Thr)-(Tnr); x7_im=(Thi)-(Tni); }

        /* Pair (5,6): reload Tu, compute Tv, store out[5] and out[6] */
        Tur=spill_re[6]; Tui=spill_im[6];
        { double Tvr=-((KP281732556)*(Tii)+((KP755749574)*(Tji)+((((KP989821441)*(Tli))-(KP540640817)*(Tmi))-(KP909631995)*(Tki))));
          double Tvi=(KP281732556)*(Tir)+((KP755749574)*(Tjr)+((((KP989821441)*(Tlr))-(KP540640817)*(Tmr))-(KP909631995)*(Tkr)));
          x5_re=(Tur)+(Tvr); x5_im=(Tui)+(Tvi);
          x6_re=(Tur)-(Tvr); x6_im=(Tui)-(Tvi); }

        /* Pair (3,8): reload Ts, compute Tt, store out[3] and out[8] */
        Tsr=spill_re[7]; Tsi=spill_im[7];
        { double Ttr=-((KP989821441)*(Tii)+((KP540640817)*(Tki)+((((KP755749574)*(Tli))-(KP281732556)*(Tmi))-(KP909631995)*(Tji))));
          double Tti=(KP989821441)*(Tir)+((KP540640817)*(Tkr)+((((KP755749574)*(Tlr))-(KP281732556)*(Tmr))-(KP909631995)*(Tjr)));
          x3_re=(Tsr)+(Ttr); x3_im=(Tsi)+(Tti);
          x8_re=(Tsr)-(Ttr); x8_im=(Tsi)-(Tti); }

        /* Pair (1,10): reload Tq, compute Tr, store out[1] and out[10] */
        Tqr=spill_re[8]; Tqi=spill_im[8];
        { double Trr=-((KP540640817)*(Tii)+((KP909631995)*(Tmi)+((KP989821441)*(Tji)+((KP755749574)*(Tki)+((KP281732556)*(Tli))))));
          double Tri=(KP540640817)*(Tir)+((KP909631995)*(Tmr)+((KP989821441)*(Tjr)+((KP755749574)*(Tkr)+((KP281732556)*(Tlr)))));
          x1_re=(Tqr)+(Trr); x1_im=(Tqi)+(Tri);
          x10_re=(Tqr)-(Trr); x10_im=(Tqi)-(Tri); }

        /* Pair (2,9): reload To, compute Tp, store out[2] and out[9] */
        Tor=spill_re[9]; Toi=spill_im[9];
        { double Tpr=-((KP909631995)*(Tii)+(((((KP755749574)*(Tmi))-(KP281732556)*(Tji))-(KP989821441)*(Tki))-(KP540640817)*(Tli)));
          double Tpi=(KP909631995)*(Tir)+(((((KP755749574)*(Tmr))-(KP281732556)*(Tjr))-(KP989821441)*(Tkr))-(KP540640817)*(Tlr));
          x2_re=(Tor)+(Tpr); x2_im=(Toi)+(Tpi);
          x9_re=(Tor)-(Tpr); x9_im=(Toi)-(Tpi); }

        rio_re[m*ms+0*ios] = x0_re; rio_im[m*ms+0*ios] = x0_im;
        rio_re[m*ms+1*ios] = x1_re; rio_im[m*ms+1*ios] = x1_im;
        rio_re[m*ms+2*ios] = x2_re; rio_im[m*ms+2*ios] = x2_im;
        rio_re[m*ms+3*ios] = x3_re; rio_im[m*ms+3*ios] = x3_im;
        rio_re[m*ms+4*ios] = x4_re; rio_im[m*ms+4*ios] = x4_im;
        rio_re[m*ms+5*ios] = x5_re; rio_im[m*ms+5*ios] = x5_im;
        rio_re[m*ms+6*ios] = x6_re; rio_im[m*ms+6*ios] = x6_im;
        rio_re[m*ms+7*ios] = x7_re; rio_im[m*ms+7*ios] = x7_im;
        rio_re[m*ms+8*ios] = x8_re; rio_im[m*ms+8*ios] = x8_im;
        rio_re[m*ms+9*ios] = x9_re; rio_im[m*ms+9*ios] = x9_im;
        rio_re[m*ms+10*ios] = x10_re; rio_im[m*ms+10*ios] = x10_im;
    }
}

static void
radix11_t1_dit_log3_bwd_scalar(
    double * __restrict__ rio_re, double * __restrict__ rio_im,
    const double * __restrict__ W_re, const double * __restrict__ W_im,
    size_t ios, size_t mb, size_t me, size_t ms)
{
    const double KP654860733 = +0.654860733945285100610078643512679263949394226;
    const double KP142314838 = +0.142314838273285143577240319245902355760335922;
    const double KP959492973 = +0.959492973614497368650688713387353345751762390;
    const double KP415415013 = +0.415415013001886435084486492996802553534507751;
    const double KP841253532 = +0.841253532831181205509096798778045922517776489;
    const double KP989821441 = +0.989821441880932684220795181317953392863273621;
    const double KP909631995 = +0.909631995354518330110238366614794358611106873;
    const double KP281732556 = +0.281732556841429671035115234190016053617000580;
    const double KP540640817 = +0.540640817455597555429847034247359260916709900;
    const double KP755749574 = +0.755749574354258268904516171460272744297981262;

    double x0_re,x0_im,x1_re,x1_im,x2_re,x2_im,x3_re,x3_im;
    double x4_re,x4_im,x5_re,x5_im,x6_re,x6_im,x7_re,x7_im;
    double x8_re,x8_im,x9_re,x9_im,x10_re,x10_im;
    double spill_re[10], spill_im[10];
    double T4r,T4i,Tgr,Tgi,Tdr,Tdi,Tar,Tai,T7r,T7i;
    double Tir,Tii,Tlr,Tli,Tkr,Tki,Tjr,Tji,Tmr,Tmi;
    double Thr,Thi,Tur,Tui,Tsr,Tsi,Tqr,Tqi,Tor,Toi;

    for (size_t m = mb; m < me; m++) {
        /* Load base twiddle w1, derive w2..w10 (9 cmuls) */
        const double w1r = W_re[0*me+m], w1i = W_im[0*me+m];
        double w2r, w2i;
        w2r = (w1r)*(w1r)-((w1i)*(w1i));
        w2i = (w1r)*(w1i)+((w1i)*(w1r));
        double w3r, w3i;
        w3r = (w1r)*(w2r)-((w1i)*(w2i));
        w3i = (w1r)*(w2i)+((w1i)*(w2r));
        double w4r, w4i;
        w4r = (w1r)*(w3r)-((w1i)*(w3i));
        w4i = (w1r)*(w3i)+((w1i)*(w3r));
        double w5r, w5i;
        w5r = (w1r)*(w4r)-((w1i)*(w4i));
        w5i = (w1r)*(w4i)+((w1i)*(w4r));
        double w6r, w6i;
        w6r = (w3r)*(w3r)-((w3i)*(w3i));
        w6i = (w3r)*(w3i)+((w3i)*(w3r));
        double w7r, w7i;
        w7r = (w3r)*(w4r)-((w3i)*(w4i));
        w7i = (w3r)*(w4i)+((w3i)*(w4r));
        double w8r, w8i;
        w8r = (w4r)*(w4r)-((w4i)*(w4i));
        w8i = (w4r)*(w4i)+((w4i)*(w4r));
        double w9r, w9i;
        w9r = (w4r)*(w5r)-((w4i)*(w5i));
        w9i = (w4r)*(w5i)+((w4i)*(w5r));
        double w10r, w10i;
        w10r = (w5r)*(w5r)-((w5i)*(w5i));
        w10i = (w5r)*(w5i)+((w5i)*(w5r));

        x0_re = rio_re[m*ms+0*ios]; x0_im = rio_im[m*ms+0*ios];
        x1_re = rio_re[m*ms+1*ios]; x1_im = rio_im[m*ms+1*ios];
        x2_re = rio_re[m*ms+2*ios]; x2_im = rio_im[m*ms+2*ios];
        x3_re = rio_re[m*ms+3*ios]; x3_im = rio_im[m*ms+3*ios];
        x4_re = rio_re[m*ms+4*ios]; x4_im = rio_im[m*ms+4*ios];
        x5_re = rio_re[m*ms+5*ios]; x5_im = rio_im[m*ms+5*ios];
        x6_re = rio_re[m*ms+6*ios]; x6_im = rio_im[m*ms+6*ios];
        x7_re = rio_re[m*ms+7*ios]; x7_im = rio_im[m*ms+7*ios];
        x8_re = rio_re[m*ms+8*ios]; x8_im = rio_im[m*ms+8*ios];
        x9_re = rio_re[m*ms+9*ios]; x9_im = rio_im[m*ms+9*ios];
        x10_re = rio_re[m*ms+10*ios]; x10_im = rio_im[m*ms+10*ios];
        { double tr = x1_re;
          x1_re = (x1_re)*(w1r)+((x1_im)*(w1i));
          x1_im = (x1_im)*(w1r)-((tr)*(w1i)); }
        { double tr = x2_re;
          x2_re = (x2_re)*(w2r)+((x2_im)*(w2i));
          x2_im = (x2_im)*(w2r)-((tr)*(w2i)); }
        { double tr = x3_re;
          x3_re = (x3_re)*(w3r)+((x3_im)*(w3i));
          x3_im = (x3_im)*(w3r)-((tr)*(w3i)); }
        { double tr = x4_re;
          x4_re = (x4_re)*(w4r)+((x4_im)*(w4i));
          x4_im = (x4_im)*(w4r)-((tr)*(w4i)); }
        { double tr = x5_re;
          x5_re = (x5_re)*(w5r)+((x5_im)*(w5i));
          x5_im = (x5_im)*(w5r)-((tr)*(w5i)); }
        { double tr = x6_re;
          x6_re = (x6_re)*(w6r)+((x6_im)*(w6i));
          x6_im = (x6_im)*(w6r)-((tr)*(w6i)); }
        { double tr = x7_re;
          x7_re = (x7_re)*(w7r)+((x7_im)*(w7i));
          x7_im = (x7_im)*(w7r)-((tr)*(w7i)); }
        { double tr = x8_re;
          x8_re = (x8_re)*(w8r)+((x8_im)*(w8i));
          x8_im = (x8_im)*(w8r)-((tr)*(w8i)); }
        { double tr = x9_re;
          x9_re = (x9_re)*(w9r)+((x9_im)*(w9i));
          x9_im = (x9_im)*(w9r)-((tr)*(w9i)); }
        { double tr = x10_re;
          x10_re = (x10_re)*(w10r)+((x10_im)*(w10i));
          x10_im = (x10_im)*(w10r)-((tr)*(w10i)); }

        /* DFT-11 butterfly [bwd] (AVX2/scalar: 3-phase + spill) */
        /* Phase 1 — sums and diffs of conjugate pairs */
        T4r=(x1_re)+(x10_re); T4i=(x1_im)+(x10_im);
        Tir=(x10_re)-(x1_re); Tii=(x10_im)-(x1_im);
        Tgr=(x5_re)+(x6_re); Tgi=(x5_im)+(x6_im);
        Tlr=(x6_re)-(x5_re); Tli=(x6_im)-(x5_im);
        Tdr=(x4_re)+(x7_re); Tdi=(x4_im)+(x7_im);
        Tkr=(x7_re)-(x4_re); Tki=(x7_im)-(x4_im);
        Tar=(x3_re)+(x8_re); Tai=(x3_im)+(x8_im);
        Tjr=(x8_re)-(x3_re); Tji=(x8_im)-(x3_im);
        T7r=(x2_re)+(x9_re); T7i=(x2_im)+(x9_im);
        Tmr=(x9_re)-(x2_re); Tmi=(x9_im)-(x2_im);
        /* Spill diffs Ti,Tj,Tk,Tl,Tm (slots 0-4) */
        spill_re[0]=Tir; spill_im[0]=Tii;
        spill_re[1]=Tjr; spill_im[1]=Tji;
        spill_re[2]=Tkr; spill_im[2]=Tki;
        spill_re[3]=Tlr; spill_im[3]=Tli;
        spill_re[4]=Tmr; spill_im[4]=Tmi;

        /* Phase 2 — 5 R (cosine) terms THEN y0 (compute R before overwriting x0) */
        Thr=(KP841253532)*(Tar)+((KP415415013)*(Tgr)+((((x0_re)-(KP654860733)*(T4r))-(KP142314838)*(T7r))-(KP959492973)*(Tdr)));
        Thi=(KP841253532)*(Tai)+((KP415415013)*(Tgi)+((((x0_im)-(KP654860733)*(T4i))-(KP142314838)*(T7i))-(KP959492973)*(Tdi)));
        Tur=(KP841253532)*(T7r)+((KP415415013)*(Tdr)+((((x0_re)-(KP959492973)*(T4r))-(KP654860733)*(Tar))-(KP142314838)*(Tgr)));
        Tui=(KP841253532)*(T7i)+((KP415415013)*(Tdi)+((((x0_im)-(KP959492973)*(T4i))-(KP654860733)*(Tai))-(KP142314838)*(Tgi)));
        Tsr=(KP415415013)*(Tar)+((KP841253532)*(Tdr)+((((x0_re)-(KP142314838)*(T4r))-(KP959492973)*(T7r))-(KP654860733)*(Tgr)));
        Tsi=(KP415415013)*(Tai)+((KP841253532)*(Tdi)+((((x0_im)-(KP142314838)*(T4i))-(KP959492973)*(T7i))-(KP654860733)*(Tgi)));
        Tqr=(KP841253532)*(T4r)+((KP415415013)*(T7r)+((((x0_re)-(KP142314838)*(Tar))-(KP654860733)*(Tdr))-(KP959492973)*(Tgr)));
        Tqi=(KP841253532)*(T4i)+((KP415415013)*(T7i)+((((x0_im)-(KP142314838)*(Tai))-(KP654860733)*(Tdi))-(KP959492973)*(Tgi)));
        Tor=(KP415415013)*(T4r)+((KP841253532)*(Tgr)+((((x0_re)-(KP654860733)*(T7r))-(KP959492973)*(Tar))-(KP142314838)*(Tdr)));
        Toi=(KP415415013)*(T4i)+((KP841253532)*(Tgi)+((((x0_im)-(KP654860733)*(T7i))-(KP959492973)*(Tai))-(KP142314838)*(Tdi)));
        x0_re=(x0_re)+((T4r)+((T7r)+((Tar)+((Tdr)+(Tgr)))));
        x0_im=(x0_im)+((T4i)+((T7i)+((Tai)+((Tdi)+(Tgi)))));
        /* Spill R terms Th,Tu,Ts,Tq,To (slots 5-9) */
        spill_re[5]=Thr; spill_im[5]=Thi;
        spill_re[6]=Tur; spill_im[6]=Tui;
        spill_re[7]=Tsr; spill_im[7]=Tsi;
        spill_re[8]=Tqr; spill_im[8]=Tqi;
        spill_re[9]=Tor; spill_im[9]=Toi;

        /* Phase 3 — S terms + combine (reload one diff set + R at a time) */

        /* Pair (4,7): reload Th, compute Tn, store out[4] and out[7] */
        Thr=spill_re[5]; Thi=spill_im[5];
        Tir=spill_re[0]; Tii=spill_im[0];
        Tjr=spill_re[1]; Tji=spill_im[1];
        Tkr=spill_re[2]; Tki=spill_im[2];
        Tlr=spill_re[3]; Tli=spill_im[3];
        Tmr=spill_re[4]; Tmi=spill_im[4];
        { double Tnr=-((KP755749574)*(Tii)+((KP540640817)*(Tji)+((((KP281732556)*(Tki))-(KP989821441)*(Tmi))-(KP909631995)*(Tli))));
          double Tni=(KP755749574)*(Tir)+((KP540640817)*(Tjr)+((((KP281732556)*(Tkr))-(KP989821441)*(Tmr))-(KP909631995)*(Tlr)));
          x7_re=(Thr)+(Tnr); x7_im=(Thi)+(Tni);
          x4_re=(Thr)-(Tnr); x4_im=(Thi)-(Tni); }

        /* Pair (5,6): reload Tu, compute Tv, store out[5] and out[6] */
        Tur=spill_re[6]; Tui=spill_im[6];
        { double Tvr=-((KP281732556)*(Tii)+((KP755749574)*(Tji)+((((KP989821441)*(Tli))-(KP540640817)*(Tmi))-(KP909631995)*(Tki))));
          double Tvi=(KP281732556)*(Tir)+((KP755749574)*(Tjr)+((((KP989821441)*(Tlr))-(KP540640817)*(Tmr))-(KP909631995)*(Tkr)));
          x6_re=(Tur)+(Tvr); x6_im=(Tui)+(Tvi);
          x5_re=(Tur)-(Tvr); x5_im=(Tui)-(Tvi); }

        /* Pair (3,8): reload Ts, compute Tt, store out[3] and out[8] */
        Tsr=spill_re[7]; Tsi=spill_im[7];
        { double Ttr=-((KP989821441)*(Tii)+((KP540640817)*(Tki)+((((KP755749574)*(Tli))-(KP281732556)*(Tmi))-(KP909631995)*(Tji))));
          double Tti=(KP989821441)*(Tir)+((KP540640817)*(Tkr)+((((KP755749574)*(Tlr))-(KP281732556)*(Tmr))-(KP909631995)*(Tjr)));
          x8_re=(Tsr)+(Ttr); x8_im=(Tsi)+(Tti);
          x3_re=(Tsr)-(Ttr); x3_im=(Tsi)-(Tti); }

        /* Pair (1,10): reload Tq, compute Tr, store out[1] and out[10] */
        Tqr=spill_re[8]; Tqi=spill_im[8];
        { double Trr=-((KP540640817)*(Tii)+((KP909631995)*(Tmi)+((KP989821441)*(Tji)+((KP755749574)*(Tki)+((KP281732556)*(Tli))))));
          double Tri=(KP540640817)*(Tir)+((KP909631995)*(Tmr)+((KP989821441)*(Tjr)+((KP755749574)*(Tkr)+((KP281732556)*(Tlr)))));
          x10_re=(Tqr)+(Trr); x10_im=(Tqi)+(Tri);
          x1_re=(Tqr)-(Trr); x1_im=(Tqi)-(Tri); }

        /* Pair (2,9): reload To, compute Tp, store out[2] and out[9] */
        Tor=spill_re[9]; Toi=spill_im[9];
        { double Tpr=-((KP909631995)*(Tii)+(((((KP755749574)*(Tmi))-(KP281732556)*(Tji))-(KP989821441)*(Tki))-(KP540640817)*(Tli)));
          double Tpi=(KP909631995)*(Tir)+(((((KP755749574)*(Tmr))-(KP281732556)*(Tjr))-(KP989821441)*(Tkr))-(KP540640817)*(Tlr));
          x9_re=(Tor)+(Tpr); x9_im=(Toi)+(Tpi);
          x2_re=(Tor)-(Tpr); x2_im=(Toi)-(Tpi); }

        rio_re[m*ms+0*ios] = x0_re; rio_im[m*ms+0*ios] = x0_im;
        rio_re[m*ms+1*ios] = x1_re; rio_im[m*ms+1*ios] = x1_im;
        rio_re[m*ms+2*ios] = x2_re; rio_im[m*ms+2*ios] = x2_im;
        rio_re[m*ms+3*ios] = x3_re; rio_im[m*ms+3*ios] = x3_im;
        rio_re[m*ms+4*ios] = x4_re; rio_im[m*ms+4*ios] = x4_im;
        rio_re[m*ms+5*ios] = x5_re; rio_im[m*ms+5*ios] = x5_im;
        rio_re[m*ms+6*ios] = x6_re; rio_im[m*ms+6*ios] = x6_im;
        rio_re[m*ms+7*ios] = x7_re; rio_im[m*ms+7*ios] = x7_im;
        rio_re[m*ms+8*ios] = x8_re; rio_im[m*ms+8*ios] = x8_im;
        rio_re[m*ms+9*ios] = x9_re; rio_im[m*ms+9*ios] = x9_im;
        rio_re[m*ms+10*ios] = x10_re; rio_im[m*ms+10*ios] = x10_im;
    }
}


#undef LD
#undef ST

#endif /* FFT_RADIX11_SCALAR_CT_CT_T1_DIT_LOG3_H */
