/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 10 --twiddled --in-place --isa avx2 --bwd --emit-c
 * Env overrides: (none)
 * Family: in-place t1 (twiddled CT)
 * ISA: 256-bit vectors, 16 vector regs (16-reg pressure rules apply)
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: false (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: BLOCKED two-pass CT 5x2; seam through L1 scratch by design (doc 58); threshold n>=16 on <=16-reg ISAs else 25 (section 35)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: no
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

static const long long _vfft_masklo[5][4] = {
    {0,0,0,0},{-1,0,0,0},{-1,-1,0,0},{-1,-1,-1,0},{-1,-1,-1,-1}};

__attribute__((target("avx2,fma")))
void radix10_t1_dit_bwd_avx2(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t ios,
    size_t me)
{
    __m256d spill_re[10];
    __m256d spill_im[10];
    size_t k = 0;
    for (; k + 4 <= me; k += 4) {
        const __m256d t0 = _mm256_set1_pd(0.95105651629514998);
        const __m256d t10 = _mm256_set1_pd(0.32491969623291);
        const __m256d t30 = _mm256_set1_pd(0.61803398874989002);
        const __m256d t32 = _mm256_set1_pd(0.80901699437495);
        const __m256d t39 = _mm256_set1_pd(0.72654252800535002);
        const __m256d t83 = _mm256_set1_pd(0.55901699437495);
        const __m256d t93 = _mm256_set1_pd(0.25);

        {
        const __m256d t85 = _mm256_loadu_pd(&rio_re[5*ios + k]);
        const __m256d t86 = _mm256_loadu_pd(&rio_im[5*ios + k]);
        const __m256d t88 = _mm256_loadu_pd(&rio_re[0*ios + k]);
        const __m256d t92 = _mm256_sub_pd(t88, t85);
            _mm256_storeu_pd(&spill_re[1], t92);
        const __m256d t139 = _mm256_add_pd(t85, t88);
            _mm256_storeu_pd(&spill_re[0], t139);
        const __m256d t89 = _mm256_loadu_pd(&rio_im[0*ios + k]);
        const __m256d t90 = _mm256_sub_pd(t89, t86);
            _mm256_storeu_pd(&spill_im[1], t90);
        const __m256d t138 = _mm256_add_pd(t86, t89);
            _mm256_storeu_pd(&spill_im[0], t138);
        const __m256d t33 = _mm256_loadu_pd(&rio_re[6*ios + k]);
        const __m256d t34 = _mm256_loadu_pd(&rio_im[6*ios + k]);
        const __m256d t36 = _mm256_loadu_pd(&rio_re[1*ios + k]);
        const __m256d t38 = _mm256_sub_pd(t36, t33);
            _mm256_storeu_pd(&spill_re[3], t38);
        const __m256d t126 = _mm256_add_pd(t33, t36);
            _mm256_storeu_pd(&spill_re[2], t126);
        const __m256d t37 = _mm256_loadu_pd(&rio_im[1*ios + k]);
        const __m256d t42 = _mm256_sub_pd(t37, t34);
            _mm256_storeu_pd(&spill_im[3], t42);
        const __m256d t127 = _mm256_add_pd(t34, t37);
            _mm256_storeu_pd(&spill_im[2], t127);
        const __m256d t1 = _mm256_loadu_pd(&rio_re[7*ios + k]);
        const __m256d t3 = _mm256_loadu_pd(&rio_im[7*ios + k]);
        const __m256d t6 = _mm256_loadu_pd(&rio_re[2*ios + k]);
        const __m256d t13 = _mm256_sub_pd(t6, t1);
            _mm256_storeu_pd(&spill_re[5], t13);
        const __m256d t120 = _mm256_add_pd(t1, t6);
            _mm256_storeu_pd(&spill_re[4], t120);
        const __m256d t7 = _mm256_loadu_pd(&rio_im[2*ios + k]);
        const __m256d t9 = _mm256_sub_pd(t7, t3);
            _mm256_storeu_pd(&spill_im[5], t9);
        const __m256d t121 = _mm256_add_pd(t3, t7);
            _mm256_storeu_pd(&spill_im[4], t121);
        const __m256d t15 = _mm256_loadu_pd(&rio_re[8*ios + k]);
        const __m256d t16 = _mm256_loadu_pd(&rio_im[8*ios + k]);
        const __m256d t18 = _mm256_loadu_pd(&rio_re[3*ios + k]);
        const __m256d t25 = _mm256_sub_pd(t18, t15);
            _mm256_storeu_pd(&spill_re[7], t25);
        const __m256d t122 = _mm256_add_pd(t15, t18);
            _mm256_storeu_pd(&spill_re[6], t122);
        const __m256d t19 = _mm256_loadu_pd(&rio_im[3*ios + k]);
        const __m256d t20 = _mm256_sub_pd(t19, t16);
            _mm256_storeu_pd(&spill_im[7], t20);
        const __m256d t123 = _mm256_add_pd(t16, t19);
            _mm256_storeu_pd(&spill_im[6], t123);
        const __m256d t45 = _mm256_loadu_pd(&rio_re[9*ios + k]);
        const __m256d t46 = _mm256_loadu_pd(&rio_im[9*ios + k]);
        const __m256d t48 = _mm256_loadu_pd(&rio_re[4*ios + k]);
        const __m256d t50 = _mm256_sub_pd(t48, t45);
            _mm256_storeu_pd(&spill_re[9], t50);
        const __m256d t128 = _mm256_add_pd(t45, t48);
            _mm256_storeu_pd(&spill_re[8], t128);
        const __m256d t49 = _mm256_loadu_pd(&rio_im[4*ios + k]);
        const __m256d t55 = _mm256_sub_pd(t49, t46);
            _mm256_storeu_pd(&spill_im[9], t55);
        const __m256d t129 = _mm256_add_pd(t46, t49);
            _mm256_storeu_pd(&spill_im[8], t129);
        }
        {
            const __m256d t120 = _mm256_loadu_pd(&spill_re[4]);
            const __m256d t122 = _mm256_loadu_pd(&spill_re[6]);
        const __m256d t134 = _mm256_add_pd(t120, t122);
            const __m256d t126 = _mm256_loadu_pd(&spill_re[2]);
            const __m256d t128 = _mm256_loadu_pd(&spill_re[8]);
        const __m256d t135 = _mm256_add_pd(t126, t128);
            const __m256d t121 = _mm256_loadu_pd(&spill_im[4]);
            const __m256d t123 = _mm256_loadu_pd(&spill_im[6]);
        const __m256d t152 = _mm256_add_pd(t121, t123);
            const __m256d t127 = _mm256_loadu_pd(&spill_im[2]);
            const __m256d t129 = _mm256_loadu_pd(&spill_im[8]);
        const __m256d t153 = _mm256_add_pd(t127, t129);
        const __m256d t140 = _mm256_add_pd(t134, t135);
            const __m256d t139 = _mm256_loadu_pd(&spill_re[0]);
        const __m256d t242 = _mm256_add_pd(t139, t140);
        const __m256d t156 = _mm256_add_pd(t152, t153);
            const __m256d t138 = _mm256_loadu_pd(&spill_im[0]);
        const __m256d t243 = _mm256_add_pd(t138, t156);
        const __m256d t290 = _mm256_fnmadd_pd(t93, t140, t139);
        const __m256d t293 = _mm256_fnmadd_pd(t93, t156, t138);
        const __m256d t124 = _mm256_sub_pd(t121, t123);
        const __m256d t130 = _mm256_sub_pd(t127, t129);
        const __m256d t146 = _mm256_sub_pd(t120, t122);
        const __m256d t148 = _mm256_sub_pd(t126, t128);
        const __m256d t136 = _mm256_sub_pd(t135, t134);
        const __m256d t154 = _mm256_sub_pd(t153, t152);
        const __m256d t288 = _mm256_fmadd_pd(t30, t124, t130);
        const __m256d t295 = _mm256_fmadd_pd(t30, t146, t148);
        const __m256d t313 = _mm256_fnmadd_pd(t30, t130, t124);
        const __m256d t316 = _mm256_fnmadd_pd(t30, t148, t146);
        const __m256d t424 = _mm256_fmadd_pd(t83, t136, t290);
        const __m256d t426 = _mm256_fmadd_pd(t83, t154, t293);
        const __m256d t440 = _mm256_fnmadd_pd(t83, t136, t290);
        const __m256d t442 = _mm256_fnmadd_pd(t83, t154, t293);
        const __m256d t425 = _mm256_fmadd_pd(t0, t288, t424);
        const __m256d t427 = _mm256_fnmadd_pd(t0, t295, t426);
        const __m256d t441 = _mm256_fnmadd_pd(t0, t313, t440);
        const __m256d t443 = _mm256_fmadd_pd(t0, t316, t442);
        const __m256d t450 = _mm256_fmadd_pd(t0, t313, t440);
        const __m256d t451 = _mm256_fnmadd_pd(t0, t316, t442);
        const __m256d t458 = _mm256_fnmadd_pd(t0, t288, t424);
        const __m256d t459 = _mm256_fmadd_pd(t0, t295, t426);
        const __m256d t145 = _mm256_loadu_pd(&tw_re[7*me + k]);
        const __m256d t161 = _mm256_loadu_pd(&tw_im[7*me + k]);
        const __m256d t428 = _mm256_fmadd_pd(t425, t145, _mm256_mul_pd(t427, t161));
        const __m256d t429 = _mm256_fnmadd_pd(t425, t161, _mm256_mul_pd(t427, t145));
        const __m256d t190 = _mm256_loadu_pd(&tw_re[5*me + k]);
        const __m256d t197 = _mm256_loadu_pd(&tw_im[5*me + k]);
        const __m256d t444 = _mm256_fmadd_pd(t441, t190, _mm256_mul_pd(t443, t197));
        const __m256d t445 = _mm256_fnmadd_pd(t441, t197, _mm256_mul_pd(t443, t190));
        const __m256d t211 = _mm256_loadu_pd(&tw_re[3*me + k]);
        const __m256d t213 = _mm256_loadu_pd(&tw_im[3*me + k]);
        const __m256d t452 = _mm256_fmadd_pd(t450, t211, _mm256_mul_pd(t451, t213));
        const __m256d t453 = _mm256_fnmadd_pd(t450, t213, _mm256_mul_pd(t451, t211));
        const __m256d t227 = _mm256_loadu_pd(&tw_re[1*me + k]);
        const __m256d t229 = _mm256_loadu_pd(&tw_im[1*me + k]);
        const __m256d t460 = _mm256_fmadd_pd(t458, t227, _mm256_mul_pd(t459, t229));
        const __m256d t461 = _mm256_fnmadd_pd(t458, t229, _mm256_mul_pd(t459, t227));
            const __m256d t25 = _mm256_loadu_pd(&spill_re[7]);
            const __m256d t20 = _mm256_loadu_pd(&spill_im[7]);
        const __m256d t69 = _mm256_fnmsub_pd(t10, t25, t20);
        _mm256_storeu_pd(&rio_re[8*ios + k], t428);
        _mm256_storeu_pd(&rio_im[8*ios + k], t429);
        _mm256_storeu_pd(&rio_re[6*ios + k], t444);
        _mm256_storeu_pd(&rio_im[6*ios + k], t445);
        _mm256_storeu_pd(&rio_re[4*ios + k], t452);
        _mm256_storeu_pd(&rio_im[4*ios + k], t453);
        _mm256_storeu_pd(&rio_re[2*ios + k], t460);
        _mm256_storeu_pd(&rio_im[2*ios + k], t461);
        _mm256_storeu_pd(&rio_re[0*ios + k], t242);
        _mm256_storeu_pd(&rio_im[0*ios + k], t243);
            const __m256d t9 = _mm256_loadu_pd(&spill_im[5]);
            const __m256d t13 = _mm256_loadu_pd(&spill_re[5]);
        const __m256d t244 = _mm256_fmadd_pd(t9, t10, t13);
        const __m256d t246 = _mm256_fnmadd_pd(t10, t20, t25);
        const __m256d t262 = _mm256_fmsub_pd(t10, t13, t9);
            const __m256d t50 = _mm256_loadu_pd(&spill_re[9]);
            const __m256d t55 = _mm256_loadu_pd(&spill_im[9]);
        const __m256d t250 = _mm256_fnmadd_pd(t39, t50, t55);
            const __m256d t38 = _mm256_loadu_pd(&spill_re[3]);
            const __m256d t42 = _mm256_loadu_pd(&spill_im[3]);
        const __m256d t252 = _mm256_fmadd_pd(t38, t39, t42);
        const __m256d t257 = _mm256_fnmadd_pd(t39, t42, t38);
        const __m256d t259 = _mm256_fmadd_pd(t39, t55, t50);
        const __m256d t349 = _mm256_sub_pd(t257, t259);
        const __m256d t360 = _mm256_sub_pd(t252, t250);
        const __m256d t352 = _mm256_mul_pd(t0, _mm256_add_pd(t69, t262));
        const __m256d t363 = _mm256_mul_pd(t0, _mm256_add_pd(t244, t246));
        const __m256d t408 = _mm256_fmadd_pd(t32, t349, t352);
        const __m256d t415 = _mm256_fmadd_pd(t32, t360, t363);
        const __m256d t343 = _mm256_mul_pd(t0, _mm256_sub_pd(t244, t246));
        const __m256d t346 = _mm256_mul_pd(t32, _mm256_add_pd(t250, t252));
        const __m256d t371 = _mm256_mul_pd(t0, _mm256_sub_pd(t262, t69));
        const __m256d t374 = _mm256_mul_pd(t32, _mm256_add_pd(t257, t259));
        const __m256d t406 = _mm256_fmsub_pd(t32, t349, t352);
        const __m256d t413 = _mm256_fmsub_pd(t32, t360, t363);
            const __m256d t92 = _mm256_loadu_pd(&spill_re[1]);
        const __m256d t466 = _mm256_fnmadd_pd(t93, t408, t92);
            const __m256d t90 = _mm256_loadu_pd(&spill_im[1]);
        const __m256d t469 = _mm256_fnmadd_pd(t93, t415, t90);
        const __m256d t404 = _mm256_fmadd_pd(t30, t343, t346);
        const __m256d t419 = _mm256_fmadd_pd(t30, t371, t374);
        const __m256d t431 = _mm256_fnmadd_pd(t30, t346, t343);
        const __m256d t434 = _mm256_fnmadd_pd(t30, t374, t371);
        const __m256d t467 = _mm256_fmadd_pd(t83, t406, t466);
        const __m256d t470 = _mm256_fmadd_pd(t83, t413, t469);
        const __m256d t474 = _mm256_fnmadd_pd(t83, t406, t466);
        const __m256d t476 = _mm256_fnmadd_pd(t83, t413, t469);
        const __m256d t462 = _mm256_add_pd(t92, t408);
        const __m256d t463 = _mm256_add_pd(t90, t415);
        const __m256d t468 = _mm256_fmadd_pd(t0, t404, t467);
        const __m256d t471 = _mm256_fnmadd_pd(t0, t419, t470);
        const __m256d t475 = _mm256_fnmadd_pd(t0, t431, t474);
        const __m256d t477 = _mm256_fmadd_pd(t0, t434, t476);
        const __m256d t480 = _mm256_fmadd_pd(t0, t431, t474);
        const __m256d t481 = _mm256_fnmadd_pd(t0, t434, t476);
        const __m256d t484 = _mm256_fnmadd_pd(t0, t404, t467);
        const __m256d t485 = _mm256_fmadd_pd(t0, t419, t470);
        const __m256d t99 = _mm256_loadu_pd(&tw_re[8*me + k]);
        const __m256d t115 = _mm256_loadu_pd(&tw_im[8*me + k]);
        const __m256d t472 = _mm256_fmadd_pd(t468, t99, _mm256_mul_pd(t471, t115));
        const __m256d t473 = _mm256_fnmadd_pd(t468, t115, _mm256_mul_pd(t471, t99));
        const __m256d t172 = _mm256_loadu_pd(&tw_re[6*me + k]);
        const __m256d t179 = _mm256_loadu_pd(&tw_im[6*me + k]);
        const __m256d t478 = _mm256_fmadd_pd(t475, t172, _mm256_mul_pd(t477, t179));
        const __m256d t479 = _mm256_fnmadd_pd(t475, t179, _mm256_mul_pd(t477, t172));
        const __m256d t203 = _mm256_loadu_pd(&tw_re[4*me + k]);
        const __m256d t205 = _mm256_loadu_pd(&tw_im[4*me + k]);
        const __m256d t482 = _mm256_fmadd_pd(t480, t203, _mm256_mul_pd(t481, t205));
        const __m256d t483 = _mm256_fnmadd_pd(t480, t205, _mm256_mul_pd(t481, t203));
        const __m256d t219 = _mm256_loadu_pd(&tw_re[2*me + k]);
        const __m256d t221 = _mm256_loadu_pd(&tw_im[2*me + k]);
        const __m256d t486 = _mm256_fmadd_pd(t484, t219, _mm256_mul_pd(t485, t221));
        const __m256d t487 = _mm256_fnmadd_pd(t484, t221, _mm256_mul_pd(t485, t219));
        const __m256d t235 = _mm256_loadu_pd(&tw_re[0*me + k]);
        const __m256d t237 = _mm256_loadu_pd(&tw_im[0*me + k]);
        const __m256d t464 = _mm256_fmadd_pd(t462, t235, _mm256_mul_pd(t463, t237));
        const __m256d t465 = _mm256_fnmadd_pd(t462, t237, _mm256_mul_pd(t463, t235));
        _mm256_storeu_pd(&rio_re[9*ios + k], t472);
        _mm256_storeu_pd(&rio_im[9*ios + k], t473);
        _mm256_storeu_pd(&rio_re[7*ios + k], t478);
        _mm256_storeu_pd(&rio_im[7*ios + k], t479);
        _mm256_storeu_pd(&rio_re[5*ios + k], t482);
        _mm256_storeu_pd(&rio_im[5*ios + k], t483);
        _mm256_storeu_pd(&rio_re[3*ios + k], t486);
        _mm256_storeu_pd(&rio_im[3*ios + k], t487);
        _mm256_storeu_pd(&rio_re[1*ios + k], t464);
        _mm256_storeu_pd(&rio_im[1*ios + k], t465);
        }
    }
    if (k < me) {
        const size_t rem = me - k;
            const __m256i _m = _mm256_loadu_si256((const __m256i *)_vfft_masklo[rem]);
        const __m256d t0 = _mm256_set1_pd(0.95105651629514998);
        const __m256d t10 = _mm256_set1_pd(0.32491969623291);
        const __m256d t30 = _mm256_set1_pd(0.61803398874989002);
        const __m256d t32 = _mm256_set1_pd(0.80901699437495);
        const __m256d t39 = _mm256_set1_pd(0.72654252800535002);
        const __m256d t83 = _mm256_set1_pd(0.55901699437495);
        const __m256d t93 = _mm256_set1_pd(0.25);

        {
        const __m256d t85 = _mm256_maskload_pd(&rio_re[5*ios + k], _m);
        const __m256d t86 = _mm256_maskload_pd(&rio_im[5*ios + k], _m);
        const __m256d t88 = _mm256_maskload_pd(&rio_re[0*ios + k], _m);
        const __m256d t92 = _mm256_sub_pd(t88, t85);
            _mm256_storeu_pd(&spill_re[1], t92);
        const __m256d t139 = _mm256_add_pd(t85, t88);
            _mm256_storeu_pd(&spill_re[0], t139);
        const __m256d t89 = _mm256_maskload_pd(&rio_im[0*ios + k], _m);
        const __m256d t90 = _mm256_sub_pd(t89, t86);
            _mm256_storeu_pd(&spill_im[1], t90);
        const __m256d t138 = _mm256_add_pd(t86, t89);
            _mm256_storeu_pd(&spill_im[0], t138);
        const __m256d t33 = _mm256_maskload_pd(&rio_re[6*ios + k], _m);
        const __m256d t34 = _mm256_maskload_pd(&rio_im[6*ios + k], _m);
        const __m256d t36 = _mm256_maskload_pd(&rio_re[1*ios + k], _m);
        const __m256d t38 = _mm256_sub_pd(t36, t33);
            _mm256_storeu_pd(&spill_re[3], t38);
        const __m256d t126 = _mm256_add_pd(t33, t36);
            _mm256_storeu_pd(&spill_re[2], t126);
        const __m256d t37 = _mm256_maskload_pd(&rio_im[1*ios + k], _m);
        const __m256d t42 = _mm256_sub_pd(t37, t34);
            _mm256_storeu_pd(&spill_im[3], t42);
        const __m256d t127 = _mm256_add_pd(t34, t37);
            _mm256_storeu_pd(&spill_im[2], t127);
        const __m256d t1 = _mm256_maskload_pd(&rio_re[7*ios + k], _m);
        const __m256d t3 = _mm256_maskload_pd(&rio_im[7*ios + k], _m);
        const __m256d t6 = _mm256_maskload_pd(&rio_re[2*ios + k], _m);
        const __m256d t13 = _mm256_sub_pd(t6, t1);
            _mm256_storeu_pd(&spill_re[5], t13);
        const __m256d t120 = _mm256_add_pd(t1, t6);
            _mm256_storeu_pd(&spill_re[4], t120);
        const __m256d t7 = _mm256_maskload_pd(&rio_im[2*ios + k], _m);
        const __m256d t9 = _mm256_sub_pd(t7, t3);
            _mm256_storeu_pd(&spill_im[5], t9);
        const __m256d t121 = _mm256_add_pd(t3, t7);
            _mm256_storeu_pd(&spill_im[4], t121);
        const __m256d t15 = _mm256_maskload_pd(&rio_re[8*ios + k], _m);
        const __m256d t16 = _mm256_maskload_pd(&rio_im[8*ios + k], _m);
        const __m256d t18 = _mm256_maskload_pd(&rio_re[3*ios + k], _m);
        const __m256d t25 = _mm256_sub_pd(t18, t15);
            _mm256_storeu_pd(&spill_re[7], t25);
        const __m256d t122 = _mm256_add_pd(t15, t18);
            _mm256_storeu_pd(&spill_re[6], t122);
        const __m256d t19 = _mm256_maskload_pd(&rio_im[3*ios + k], _m);
        const __m256d t20 = _mm256_sub_pd(t19, t16);
            _mm256_storeu_pd(&spill_im[7], t20);
        const __m256d t123 = _mm256_add_pd(t16, t19);
            _mm256_storeu_pd(&spill_im[6], t123);
        const __m256d t45 = _mm256_maskload_pd(&rio_re[9*ios + k], _m);
        const __m256d t46 = _mm256_maskload_pd(&rio_im[9*ios + k], _m);
        const __m256d t48 = _mm256_maskload_pd(&rio_re[4*ios + k], _m);
        const __m256d t50 = _mm256_sub_pd(t48, t45);
            _mm256_storeu_pd(&spill_re[9], t50);
        const __m256d t128 = _mm256_add_pd(t45, t48);
            _mm256_storeu_pd(&spill_re[8], t128);
        const __m256d t49 = _mm256_maskload_pd(&rio_im[4*ios + k], _m);
        const __m256d t55 = _mm256_sub_pd(t49, t46);
            _mm256_storeu_pd(&spill_im[9], t55);
        const __m256d t129 = _mm256_add_pd(t46, t49);
            _mm256_storeu_pd(&spill_im[8], t129);
        }
        {
            const __m256d t120 = _mm256_loadu_pd(&spill_re[4]);
            const __m256d t122 = _mm256_loadu_pd(&spill_re[6]);
        const __m256d t134 = _mm256_add_pd(t120, t122);
            const __m256d t126 = _mm256_loadu_pd(&spill_re[2]);
            const __m256d t128 = _mm256_loadu_pd(&spill_re[8]);
        const __m256d t135 = _mm256_add_pd(t126, t128);
            const __m256d t121 = _mm256_loadu_pd(&spill_im[4]);
            const __m256d t123 = _mm256_loadu_pd(&spill_im[6]);
        const __m256d t152 = _mm256_add_pd(t121, t123);
            const __m256d t127 = _mm256_loadu_pd(&spill_im[2]);
            const __m256d t129 = _mm256_loadu_pd(&spill_im[8]);
        const __m256d t153 = _mm256_add_pd(t127, t129);
        const __m256d t140 = _mm256_add_pd(t134, t135);
            const __m256d t139 = _mm256_loadu_pd(&spill_re[0]);
        const __m256d t242 = _mm256_add_pd(t139, t140);
        const __m256d t156 = _mm256_add_pd(t152, t153);
            const __m256d t138 = _mm256_loadu_pd(&spill_im[0]);
        const __m256d t243 = _mm256_add_pd(t138, t156);
        const __m256d t290 = _mm256_fnmadd_pd(t93, t140, t139);
        const __m256d t293 = _mm256_fnmadd_pd(t93, t156, t138);
        const __m256d t124 = _mm256_sub_pd(t121, t123);
        const __m256d t130 = _mm256_sub_pd(t127, t129);
        const __m256d t146 = _mm256_sub_pd(t120, t122);
        const __m256d t148 = _mm256_sub_pd(t126, t128);
        const __m256d t136 = _mm256_sub_pd(t135, t134);
        const __m256d t154 = _mm256_sub_pd(t153, t152);
        const __m256d t288 = _mm256_fmadd_pd(t30, t124, t130);
        const __m256d t295 = _mm256_fmadd_pd(t30, t146, t148);
        const __m256d t313 = _mm256_fnmadd_pd(t30, t130, t124);
        const __m256d t316 = _mm256_fnmadd_pd(t30, t148, t146);
        const __m256d t424 = _mm256_fmadd_pd(t83, t136, t290);
        const __m256d t426 = _mm256_fmadd_pd(t83, t154, t293);
        const __m256d t440 = _mm256_fnmadd_pd(t83, t136, t290);
        const __m256d t442 = _mm256_fnmadd_pd(t83, t154, t293);
        const __m256d t425 = _mm256_fmadd_pd(t0, t288, t424);
        const __m256d t427 = _mm256_fnmadd_pd(t0, t295, t426);
        const __m256d t441 = _mm256_fnmadd_pd(t0, t313, t440);
        const __m256d t443 = _mm256_fmadd_pd(t0, t316, t442);
        const __m256d t450 = _mm256_fmadd_pd(t0, t313, t440);
        const __m256d t451 = _mm256_fnmadd_pd(t0, t316, t442);
        const __m256d t458 = _mm256_fnmadd_pd(t0, t288, t424);
        const __m256d t459 = _mm256_fmadd_pd(t0, t295, t426);
        const __m256d t145 = _mm256_maskload_pd(&tw_re[7*me + k], _m);
        const __m256d t161 = _mm256_maskload_pd(&tw_im[7*me + k], _m);
        const __m256d t428 = _mm256_fmadd_pd(t425, t145, _mm256_mul_pd(t427, t161));
        const __m256d t429 = _mm256_fnmadd_pd(t425, t161, _mm256_mul_pd(t427, t145));
        const __m256d t190 = _mm256_maskload_pd(&tw_re[5*me + k], _m);
        const __m256d t197 = _mm256_maskload_pd(&tw_im[5*me + k], _m);
        const __m256d t444 = _mm256_fmadd_pd(t441, t190, _mm256_mul_pd(t443, t197));
        const __m256d t445 = _mm256_fnmadd_pd(t441, t197, _mm256_mul_pd(t443, t190));
        const __m256d t211 = _mm256_maskload_pd(&tw_re[3*me + k], _m);
        const __m256d t213 = _mm256_maskload_pd(&tw_im[3*me + k], _m);
        const __m256d t452 = _mm256_fmadd_pd(t450, t211, _mm256_mul_pd(t451, t213));
        const __m256d t453 = _mm256_fnmadd_pd(t450, t213, _mm256_mul_pd(t451, t211));
        const __m256d t227 = _mm256_maskload_pd(&tw_re[1*me + k], _m);
        const __m256d t229 = _mm256_maskload_pd(&tw_im[1*me + k], _m);
        const __m256d t460 = _mm256_fmadd_pd(t458, t227, _mm256_mul_pd(t459, t229));
        const __m256d t461 = _mm256_fnmadd_pd(t458, t229, _mm256_mul_pd(t459, t227));
            const __m256d t25 = _mm256_loadu_pd(&spill_re[7]);
            const __m256d t20 = _mm256_loadu_pd(&spill_im[7]);
        const __m256d t69 = _mm256_fnmsub_pd(t10, t25, t20);
        _mm256_maskstore_pd(&rio_re[8*ios + k], _m, t428);
        _mm256_maskstore_pd(&rio_im[8*ios + k], _m, t429);
        _mm256_maskstore_pd(&rio_re[6*ios + k], _m, t444);
        _mm256_maskstore_pd(&rio_im[6*ios + k], _m, t445);
        _mm256_maskstore_pd(&rio_re[4*ios + k], _m, t452);
        _mm256_maskstore_pd(&rio_im[4*ios + k], _m, t453);
        _mm256_maskstore_pd(&rio_re[2*ios + k], _m, t460);
        _mm256_maskstore_pd(&rio_im[2*ios + k], _m, t461);
        _mm256_maskstore_pd(&rio_re[0*ios + k], _m, t242);
        _mm256_maskstore_pd(&rio_im[0*ios + k], _m, t243);
            const __m256d t9 = _mm256_loadu_pd(&spill_im[5]);
            const __m256d t13 = _mm256_loadu_pd(&spill_re[5]);
        const __m256d t244 = _mm256_fmadd_pd(t9, t10, t13);
        const __m256d t246 = _mm256_fnmadd_pd(t10, t20, t25);
        const __m256d t262 = _mm256_fmsub_pd(t10, t13, t9);
            const __m256d t50 = _mm256_loadu_pd(&spill_re[9]);
            const __m256d t55 = _mm256_loadu_pd(&spill_im[9]);
        const __m256d t250 = _mm256_fnmadd_pd(t39, t50, t55);
            const __m256d t38 = _mm256_loadu_pd(&spill_re[3]);
            const __m256d t42 = _mm256_loadu_pd(&spill_im[3]);
        const __m256d t252 = _mm256_fmadd_pd(t38, t39, t42);
        const __m256d t257 = _mm256_fnmadd_pd(t39, t42, t38);
        const __m256d t259 = _mm256_fmadd_pd(t39, t55, t50);
        const __m256d t349 = _mm256_sub_pd(t257, t259);
        const __m256d t360 = _mm256_sub_pd(t252, t250);
        const __m256d t352 = _mm256_mul_pd(t0, _mm256_add_pd(t69, t262));
        const __m256d t363 = _mm256_mul_pd(t0, _mm256_add_pd(t244, t246));
        const __m256d t408 = _mm256_fmadd_pd(t32, t349, t352);
        const __m256d t415 = _mm256_fmadd_pd(t32, t360, t363);
        const __m256d t343 = _mm256_mul_pd(t0, _mm256_sub_pd(t244, t246));
        const __m256d t346 = _mm256_mul_pd(t32, _mm256_add_pd(t250, t252));
        const __m256d t371 = _mm256_mul_pd(t0, _mm256_sub_pd(t262, t69));
        const __m256d t374 = _mm256_mul_pd(t32, _mm256_add_pd(t257, t259));
        const __m256d t406 = _mm256_fmsub_pd(t32, t349, t352);
        const __m256d t413 = _mm256_fmsub_pd(t32, t360, t363);
            const __m256d t92 = _mm256_loadu_pd(&spill_re[1]);
        const __m256d t466 = _mm256_fnmadd_pd(t93, t408, t92);
            const __m256d t90 = _mm256_loadu_pd(&spill_im[1]);
        const __m256d t469 = _mm256_fnmadd_pd(t93, t415, t90);
        const __m256d t404 = _mm256_fmadd_pd(t30, t343, t346);
        const __m256d t419 = _mm256_fmadd_pd(t30, t371, t374);
        const __m256d t431 = _mm256_fnmadd_pd(t30, t346, t343);
        const __m256d t434 = _mm256_fnmadd_pd(t30, t374, t371);
        const __m256d t467 = _mm256_fmadd_pd(t83, t406, t466);
        const __m256d t470 = _mm256_fmadd_pd(t83, t413, t469);
        const __m256d t474 = _mm256_fnmadd_pd(t83, t406, t466);
        const __m256d t476 = _mm256_fnmadd_pd(t83, t413, t469);
        const __m256d t462 = _mm256_add_pd(t92, t408);
        const __m256d t463 = _mm256_add_pd(t90, t415);
        const __m256d t468 = _mm256_fmadd_pd(t0, t404, t467);
        const __m256d t471 = _mm256_fnmadd_pd(t0, t419, t470);
        const __m256d t475 = _mm256_fnmadd_pd(t0, t431, t474);
        const __m256d t477 = _mm256_fmadd_pd(t0, t434, t476);
        const __m256d t480 = _mm256_fmadd_pd(t0, t431, t474);
        const __m256d t481 = _mm256_fnmadd_pd(t0, t434, t476);
        const __m256d t484 = _mm256_fnmadd_pd(t0, t404, t467);
        const __m256d t485 = _mm256_fmadd_pd(t0, t419, t470);
        const __m256d t99 = _mm256_maskload_pd(&tw_re[8*me + k], _m);
        const __m256d t115 = _mm256_maskload_pd(&tw_im[8*me + k], _m);
        const __m256d t472 = _mm256_fmadd_pd(t468, t99, _mm256_mul_pd(t471, t115));
        const __m256d t473 = _mm256_fnmadd_pd(t468, t115, _mm256_mul_pd(t471, t99));
        const __m256d t172 = _mm256_maskload_pd(&tw_re[6*me + k], _m);
        const __m256d t179 = _mm256_maskload_pd(&tw_im[6*me + k], _m);
        const __m256d t478 = _mm256_fmadd_pd(t475, t172, _mm256_mul_pd(t477, t179));
        const __m256d t479 = _mm256_fnmadd_pd(t475, t179, _mm256_mul_pd(t477, t172));
        const __m256d t203 = _mm256_maskload_pd(&tw_re[4*me + k], _m);
        const __m256d t205 = _mm256_maskload_pd(&tw_im[4*me + k], _m);
        const __m256d t482 = _mm256_fmadd_pd(t480, t203, _mm256_mul_pd(t481, t205));
        const __m256d t483 = _mm256_fnmadd_pd(t480, t205, _mm256_mul_pd(t481, t203));
        const __m256d t219 = _mm256_maskload_pd(&tw_re[2*me + k], _m);
        const __m256d t221 = _mm256_maskload_pd(&tw_im[2*me + k], _m);
        const __m256d t486 = _mm256_fmadd_pd(t484, t219, _mm256_mul_pd(t485, t221));
        const __m256d t487 = _mm256_fnmadd_pd(t484, t221, _mm256_mul_pd(t485, t219));
        const __m256d t235 = _mm256_maskload_pd(&tw_re[0*me + k], _m);
        const __m256d t237 = _mm256_maskload_pd(&tw_im[0*me + k], _m);
        const __m256d t464 = _mm256_fmadd_pd(t462, t235, _mm256_mul_pd(t463, t237));
        const __m256d t465 = _mm256_fnmadd_pd(t462, t237, _mm256_mul_pd(t463, t235));
        _mm256_maskstore_pd(&rio_re[9*ios + k], _m, t472);
        _mm256_maskstore_pd(&rio_im[9*ios + k], _m, t473);
        _mm256_maskstore_pd(&rio_re[7*ios + k], _m, t478);
        _mm256_maskstore_pd(&rio_im[7*ios + k], _m, t479);
        _mm256_maskstore_pd(&rio_re[5*ios + k], _m, t482);
        _mm256_maskstore_pd(&rio_im[5*ios + k], _m, t483);
        _mm256_maskstore_pd(&rio_re[3*ios + k], _m, t486);
        _mm256_maskstore_pd(&rio_im[3*ios + k], _m, t487);
        _mm256_maskstore_pd(&rio_re[1*ios + k], _m, t464);
        _mm256_maskstore_pd(&rio_im[1*ios + k], _m, t465);
        }
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=134  flops=182  (add=24 sub=20 mul=6 fma=48 cmul=18 neg=0)
 *   essential_io=58 ops (vec_loads=38 + stores=20)  [+0 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=10 slots => +40 mem ops, 20 vectors live across pass boundary
 *   memory_floor=98 mem ops   peak_live(max-per-pass)=15   budget=14 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: SPILLS (peak_live > budget)  [CT: peak_live is max over passes; cross_pass_cut is added explicit spill traffic]
 */
