/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 8 --twiddled --in-place --isa avx2 --log3 --emit-c
 * Env overrides: (none)
 * Family: in-place t1 (twiddled CT)
 * ISA: 256-bit vectors, 16 vector regs (16-reg pressure rules apply)
 * Scheduler: the list scheduler (flag name --su; lazy loads, sink-first, cp_dist, SU tiebreak; section 30)
 * GH pressure mode: false (auto-rule: vec_regs<=16 && n>=32; +4-8% documented)
 * Construction: BLOCKED two-pass CT 2x4; seam through L1 scratch by design (doc 58); threshold n>=16 on <=16-reg ISAs else 25 (section 35)
 * Regalloc+pinning: false (gate: log3+avx512+R<=32 OR avx2 n1 R>=16, sections 32/34/35; kill switch VFFT_NO_REGALLOC)
 * Value fences: false (asm-volatile +v stops gcc rematerialization, doc 28; exempt: n1 avx2 R in {8,16}, measured better unfenced)
 * log3: DIT radix-decomposition ladder variant
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

static const long long _vfft_masklo[5][4] = {
    {0,0,0,0},{-1,0,0,0},{-1,-1,0,0},{-1,-1,-1,0},{-1,-1,-1,-1}};

__attribute__((target("avx2,fma")))
void radix8_t1_dit_log3_fwd_avx2(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t ios,
    size_t me)
{
    __m256d spill_re[8];
    __m256d spill_im[8];
    size_t k = 0;
    for (; k + 4 <= me; k += 4) {
        const __m256d t44 = _mm256_set1_pd(0.70710678118655002);

        {
        const __m256d t1 = _mm256_loadu_pd(&tw_re[3*me + k]);
        const __m256d t2 = _mm256_loadu_pd(&tw_re[1*me + k]);
        const __m256d t4 = _mm256_loadu_pd(&tw_im[1*me + k]);
        const __m256d t8 = _mm256_loadu_pd(&tw_im[3*me + k]);
        const __m256d t52 = _mm256_fnmadd_pd(t8, t4, _mm256_mul_pd(t1, t2));
        const __m256d t53 = _mm256_fmadd_pd(t1, t4, _mm256_mul_pd(t8, t2));
        const __m256d t51 = _mm256_loadu_pd(&rio_re[6*ios + k]);
        const __m256d t54 = _mm256_loadu_pd(&rio_im[6*ios + k]);
        const __m256d t55 = _mm256_fnmadd_pd(t54, t53, _mm256_mul_pd(t51, t52));
        const __m256d t56 = _mm256_fmadd_pd(t51, t53, _mm256_mul_pd(t54, t52));
        const __m256d t58 = _mm256_loadu_pd(&rio_re[2*ios + k]);
        const __m256d t59 = _mm256_loadu_pd(&rio_im[2*ios + k]);
        const __m256d t60 = _mm256_fnmadd_pd(t59, t4, _mm256_mul_pd(t58, t2));
        const __m256d t61 = _mm256_fmadd_pd(t58, t4, _mm256_mul_pd(t59, t2));
        const __m256d t62 = _mm256_sub_pd(t61, t56);
        const __m256d t64 = _mm256_sub_pd(t60, t55);
        const __m256d t91 = _mm256_add_pd(t56, t61);
        const __m256d t92 = _mm256_add_pd(t55, t60);
        const __m256d t67 = _mm256_loadu_pd(&rio_re[4*ios + k]);
        const __m256d t68 = _mm256_loadu_pd(&rio_im[4*ios + k]);
        const __m256d t69 = _mm256_fnmadd_pd(t68, t8, _mm256_mul_pd(t67, t1));
        const __m256d t70 = _mm256_fmadd_pd(t67, t8, _mm256_mul_pd(t68, t1));
        const __m256d t72 = _mm256_loadu_pd(&rio_re[0*ios + k]);
        const __m256d t76 = _mm256_sub_pd(t72, t69);
        const __m256d t78 = _mm256_sub_pd(t76, t62);
            _mm256_storeu_pd(&spill_re[3], t78);
        const __m256d t111 = _mm256_add_pd(t62, t76);
            _mm256_storeu_pd(&spill_re[1], t111);
        const __m256d t95 = _mm256_add_pd(t69, t72);
        const __m256d t98 = _mm256_sub_pd(t95, t92);
            _mm256_storeu_pd(&spill_re[2], t98);
        const __m256d t119 = _mm256_add_pd(t92, t95);
            _mm256_storeu_pd(&spill_re[0], t119);
        const __m256d t73 = _mm256_loadu_pd(&rio_im[0*ios + k]);
        const __m256d t74 = _mm256_sub_pd(t73, t70);
        const __m256d t77 = _mm256_add_pd(t64, t74);
            _mm256_storeu_pd(&spill_im[3], t77);
        const __m256d t110 = _mm256_sub_pd(t74, t64);
            _mm256_storeu_pd(&spill_im[1], t110);
        const __m256d t94 = _mm256_add_pd(t70, t73);
        const __m256d t96 = _mm256_sub_pd(t94, t91);
            _mm256_storeu_pd(&spill_im[2], t96);
        const __m256d t118 = _mm256_add_pd(t91, t94);
            _mm256_storeu_pd(&spill_im[0], t118);
        const __m256d t0 = _mm256_loadu_pd(&rio_re[7*ios + k]);
        const __m256d t3 = _mm256_loadu_pd(&tw_re[0*me + k]);
        const __m256d t5 = _mm256_loadu_pd(&tw_im[0*me + k]);
        const __m256d t6 = _mm256_fnmadd_pd(t4, t5, _mm256_mul_pd(t2, t3));
        const __m256d t7 = _mm256_fmadd_pd(t2, t5, _mm256_mul_pd(t4, t3));
        const __m256d t28 = _mm256_fnmadd_pd(t8, t5, _mm256_mul_pd(t1, t3));
        const __m256d t29 = _mm256_fmadd_pd(t1, t5, _mm256_mul_pd(t8, t3));
        const __m256d t9 = _mm256_fnmadd_pd(t8, t7, _mm256_mul_pd(t1, t6));
        const __m256d t10 = _mm256_fmadd_pd(t1, t7, _mm256_mul_pd(t8, t6));
        const __m256d t11 = _mm256_loadu_pd(&rio_im[7*ios + k]);
        const __m256d t12 = _mm256_fnmadd_pd(t11, t10, _mm256_mul_pd(t0, t9));
        const __m256d t13 = _mm256_fmadd_pd(t0, t10, _mm256_mul_pd(t11, t9));
        const __m256d t17 = _mm256_loadu_pd(&rio_re[3*ios + k]);
        const __m256d t18 = _mm256_loadu_pd(&rio_im[3*ios + k]);
        const __m256d t19 = _mm256_fnmadd_pd(t18, t7, _mm256_mul_pd(t17, t6));
        const __m256d t20 = _mm256_fmadd_pd(t17, t7, _mm256_mul_pd(t18, t6));
        const __m256d t22 = _mm256_sub_pd(t20, t13);
        const __m256d t24 = _mm256_sub_pd(t19, t12);
        const __m256d t81 = _mm256_add_pd(t13, t20);
        const __m256d t82 = _mm256_add_pd(t12, t19);
        const __m256d t27 = _mm256_loadu_pd(&rio_re[5*ios + k]);
        const __m256d t30 = _mm256_loadu_pd(&rio_im[5*ios + k]);
        const __m256d t31 = _mm256_fnmadd_pd(t30, t29, _mm256_mul_pd(t27, t28));
        const __m256d t32 = _mm256_fmadd_pd(t27, t29, _mm256_mul_pd(t30, t28));
        const __m256d t34 = _mm256_loadu_pd(&rio_re[1*ios + k]);
        const __m256d t35 = _mm256_loadu_pd(&rio_im[1*ios + k]);
        const __m256d t36 = _mm256_fnmadd_pd(t35, t5, _mm256_mul_pd(t34, t3));
        const __m256d t37 = _mm256_fmadd_pd(t34, t5, _mm256_mul_pd(t35, t3));
        const __m256d t38 = _mm256_sub_pd(t37, t32);
        const __m256d t41 = _mm256_add_pd(t24, t38);
            _mm256_storeu_pd(&spill_im[7], t41);
        const __m256d t101 = _mm256_sub_pd(t38, t24);
            _mm256_storeu_pd(&spill_im[5], t101);
        const __m256d t40 = _mm256_sub_pd(t36, t31);
        const __m256d t42 = _mm256_sub_pd(t40, t22);
            _mm256_storeu_pd(&spill_re[7], t42);
        const __m256d t103 = _mm256_add_pd(t22, t40);
            _mm256_storeu_pd(&spill_re[5], t103);
        const __m256d t84 = _mm256_add_pd(t32, t37);
        const __m256d t86 = _mm256_sub_pd(t84, t81);
            _mm256_storeu_pd(&spill_im[6], t86);
        const __m256d t115 = _mm256_add_pd(t81, t84);
            _mm256_storeu_pd(&spill_im[4], t115);
        const __m256d t85 = _mm256_add_pd(t31, t36);
        const __m256d t88 = _mm256_sub_pd(t85, t82);
            _mm256_storeu_pd(&spill_re[6], t88);
        const __m256d t116 = _mm256_add_pd(t82, t85);
            _mm256_storeu_pd(&spill_re[4], t116);
        }
        {
            const __m256d t119 = _mm256_loadu_pd(&spill_re[0]);
            const __m256d t116 = _mm256_loadu_pd(&spill_re[4]);
        const __m256d t120 = _mm256_sub_pd(t119, t116);
            const __m256d t118 = _mm256_loadu_pd(&spill_im[0]);
            const __m256d t115 = _mm256_loadu_pd(&spill_im[4]);
        const __m256d t122 = _mm256_sub_pd(t118, t115);
        const __m256d t129 = _mm256_add_pd(t116, t119);
        const __m256d t130 = _mm256_add_pd(t115, t118);
            const __m256d t101 = _mm256_loadu_pd(&spill_im[5]);
            const __m256d t103 = _mm256_loadu_pd(&spill_re[5]);
        const __m256d t104 = _mm256_add_pd(t101, t103);
        _mm256_storeu_pd(&rio_re[4*ios + k], t120);
        _mm256_storeu_pd(&rio_im[4*ios + k], t122);
        _mm256_storeu_pd(&rio_re[0*ios + k], t129);
        _mm256_storeu_pd(&rio_im[0*ios + k], t130);
            const __m256d t111 = _mm256_loadu_pd(&spill_re[1]);
        const __m256d t133 = _mm256_fnmadd_pd(t44, t104, t111);
        const __m256d t137 = _mm256_fmadd_pd(t44, t104, t111);
        const __m256d t107 = _mm256_sub_pd(t101, t103);
            const __m256d t110 = _mm256_loadu_pd(&spill_im[1]);
        const __m256d t134 = _mm256_fnmadd_pd(t44, t107, t110);
        const __m256d t138 = _mm256_fmadd_pd(t44, t107, t110);
            const __m256d t98 = _mm256_loadu_pd(&spill_re[2]);
            const __m256d t86 = _mm256_loadu_pd(&spill_im[6]);
        const __m256d t99 = _mm256_sub_pd(t98, t86);
        _mm256_storeu_pd(&rio_re[5*ios + k], t133);
        _mm256_storeu_pd(&rio_im[5*ios + k], t134);
        _mm256_storeu_pd(&rio_re[1*ios + k], t137);
        _mm256_storeu_pd(&rio_im[1*ios + k], t138);
            const __m256d t88 = _mm256_loadu_pd(&spill_re[6]);
            const __m256d t96 = _mm256_loadu_pd(&spill_im[2]);
        const __m256d t100 = _mm256_add_pd(t88, t96);
        const __m256d t125 = _mm256_add_pd(t86, t98);
        const __m256d t126 = _mm256_sub_pd(t96, t88);
            const __m256d t42 = _mm256_loadu_pd(&spill_re[7]);
            const __m256d t41 = _mm256_loadu_pd(&spill_im[7]);
        const __m256d t43 = _mm256_sub_pd(t42, t41);
        _mm256_storeu_pd(&rio_re[6*ios + k], t99);
        _mm256_storeu_pd(&rio_im[6*ios + k], t100);
        _mm256_storeu_pd(&rio_re[2*ios + k], t125);
        _mm256_storeu_pd(&rio_im[2*ios + k], t126);
            const __m256d t78 = _mm256_loadu_pd(&spill_re[3]);
        const __m256d t131 = _mm256_fmadd_pd(t43, t44, t78);
        const __m256d t135 = _mm256_fnmadd_pd(t43, t44, t78);
        const __m256d t48 = _mm256_add_pd(t41, t42);
            const __m256d t77 = _mm256_loadu_pd(&spill_im[3]);
        const __m256d t132 = _mm256_fmadd_pd(t44, t48, t77);
        const __m256d t136 = _mm256_fnmadd_pd(t44, t48, t77);
        _mm256_storeu_pd(&rio_re[7*ios + k], t131);
        _mm256_storeu_pd(&rio_im[7*ios + k], t132);
        _mm256_storeu_pd(&rio_re[3*ios + k], t135);
        _mm256_storeu_pd(&rio_im[3*ios + k], t136);
        }
    }
    if (k < me) {
        const size_t rem = me - k;
            const __m256i _m = _mm256_loadu_si256((const __m256i *)_vfft_masklo[rem]);
        const __m256d t44 = _mm256_set1_pd(0.70710678118655002);

        {
        const __m256d t1 = _mm256_maskload_pd(&tw_re[3*me + k], _m);
        const __m256d t2 = _mm256_maskload_pd(&tw_re[1*me + k], _m);
        const __m256d t4 = _mm256_maskload_pd(&tw_im[1*me + k], _m);
        const __m256d t8 = _mm256_maskload_pd(&tw_im[3*me + k], _m);
        const __m256d t52 = _mm256_fnmadd_pd(t8, t4, _mm256_mul_pd(t1, t2));
        const __m256d t53 = _mm256_fmadd_pd(t1, t4, _mm256_mul_pd(t8, t2));
        const __m256d t51 = _mm256_maskload_pd(&rio_re[6*ios + k], _m);
        const __m256d t54 = _mm256_maskload_pd(&rio_im[6*ios + k], _m);
        const __m256d t55 = _mm256_fnmadd_pd(t54, t53, _mm256_mul_pd(t51, t52));
        const __m256d t56 = _mm256_fmadd_pd(t51, t53, _mm256_mul_pd(t54, t52));
        const __m256d t58 = _mm256_maskload_pd(&rio_re[2*ios + k], _m);
        const __m256d t59 = _mm256_maskload_pd(&rio_im[2*ios + k], _m);
        const __m256d t60 = _mm256_fnmadd_pd(t59, t4, _mm256_mul_pd(t58, t2));
        const __m256d t61 = _mm256_fmadd_pd(t58, t4, _mm256_mul_pd(t59, t2));
        const __m256d t62 = _mm256_sub_pd(t61, t56);
        const __m256d t64 = _mm256_sub_pd(t60, t55);
        const __m256d t91 = _mm256_add_pd(t56, t61);
        const __m256d t92 = _mm256_add_pd(t55, t60);
        const __m256d t67 = _mm256_maskload_pd(&rio_re[4*ios + k], _m);
        const __m256d t68 = _mm256_maskload_pd(&rio_im[4*ios + k], _m);
        const __m256d t69 = _mm256_fnmadd_pd(t68, t8, _mm256_mul_pd(t67, t1));
        const __m256d t70 = _mm256_fmadd_pd(t67, t8, _mm256_mul_pd(t68, t1));
        const __m256d t72 = _mm256_maskload_pd(&rio_re[0*ios + k], _m);
        const __m256d t76 = _mm256_sub_pd(t72, t69);
        const __m256d t78 = _mm256_sub_pd(t76, t62);
            _mm256_storeu_pd(&spill_re[3], t78);
        const __m256d t111 = _mm256_add_pd(t62, t76);
            _mm256_storeu_pd(&spill_re[1], t111);
        const __m256d t95 = _mm256_add_pd(t69, t72);
        const __m256d t98 = _mm256_sub_pd(t95, t92);
            _mm256_storeu_pd(&spill_re[2], t98);
        const __m256d t119 = _mm256_add_pd(t92, t95);
            _mm256_storeu_pd(&spill_re[0], t119);
        const __m256d t73 = _mm256_maskload_pd(&rio_im[0*ios + k], _m);
        const __m256d t74 = _mm256_sub_pd(t73, t70);
        const __m256d t77 = _mm256_add_pd(t64, t74);
            _mm256_storeu_pd(&spill_im[3], t77);
        const __m256d t110 = _mm256_sub_pd(t74, t64);
            _mm256_storeu_pd(&spill_im[1], t110);
        const __m256d t94 = _mm256_add_pd(t70, t73);
        const __m256d t96 = _mm256_sub_pd(t94, t91);
            _mm256_storeu_pd(&spill_im[2], t96);
        const __m256d t118 = _mm256_add_pd(t91, t94);
            _mm256_storeu_pd(&spill_im[0], t118);
        const __m256d t0 = _mm256_maskload_pd(&rio_re[7*ios + k], _m);
        const __m256d t3 = _mm256_maskload_pd(&tw_re[0*me + k], _m);
        const __m256d t5 = _mm256_maskload_pd(&tw_im[0*me + k], _m);
        const __m256d t6 = _mm256_fnmadd_pd(t4, t5, _mm256_mul_pd(t2, t3));
        const __m256d t7 = _mm256_fmadd_pd(t2, t5, _mm256_mul_pd(t4, t3));
        const __m256d t28 = _mm256_fnmadd_pd(t8, t5, _mm256_mul_pd(t1, t3));
        const __m256d t29 = _mm256_fmadd_pd(t1, t5, _mm256_mul_pd(t8, t3));
        const __m256d t9 = _mm256_fnmadd_pd(t8, t7, _mm256_mul_pd(t1, t6));
        const __m256d t10 = _mm256_fmadd_pd(t1, t7, _mm256_mul_pd(t8, t6));
        const __m256d t11 = _mm256_maskload_pd(&rio_im[7*ios + k], _m);
        const __m256d t12 = _mm256_fnmadd_pd(t11, t10, _mm256_mul_pd(t0, t9));
        const __m256d t13 = _mm256_fmadd_pd(t0, t10, _mm256_mul_pd(t11, t9));
        const __m256d t17 = _mm256_maskload_pd(&rio_re[3*ios + k], _m);
        const __m256d t18 = _mm256_maskload_pd(&rio_im[3*ios + k], _m);
        const __m256d t19 = _mm256_fnmadd_pd(t18, t7, _mm256_mul_pd(t17, t6));
        const __m256d t20 = _mm256_fmadd_pd(t17, t7, _mm256_mul_pd(t18, t6));
        const __m256d t22 = _mm256_sub_pd(t20, t13);
        const __m256d t24 = _mm256_sub_pd(t19, t12);
        const __m256d t81 = _mm256_add_pd(t13, t20);
        const __m256d t82 = _mm256_add_pd(t12, t19);
        const __m256d t27 = _mm256_maskload_pd(&rio_re[5*ios + k], _m);
        const __m256d t30 = _mm256_maskload_pd(&rio_im[5*ios + k], _m);
        const __m256d t31 = _mm256_fnmadd_pd(t30, t29, _mm256_mul_pd(t27, t28));
        const __m256d t32 = _mm256_fmadd_pd(t27, t29, _mm256_mul_pd(t30, t28));
        const __m256d t34 = _mm256_maskload_pd(&rio_re[1*ios + k], _m);
        const __m256d t35 = _mm256_maskload_pd(&rio_im[1*ios + k], _m);
        const __m256d t36 = _mm256_fnmadd_pd(t35, t5, _mm256_mul_pd(t34, t3));
        const __m256d t37 = _mm256_fmadd_pd(t34, t5, _mm256_mul_pd(t35, t3));
        const __m256d t38 = _mm256_sub_pd(t37, t32);
        const __m256d t41 = _mm256_add_pd(t24, t38);
            _mm256_storeu_pd(&spill_im[7], t41);
        const __m256d t101 = _mm256_sub_pd(t38, t24);
            _mm256_storeu_pd(&spill_im[5], t101);
        const __m256d t40 = _mm256_sub_pd(t36, t31);
        const __m256d t42 = _mm256_sub_pd(t40, t22);
            _mm256_storeu_pd(&spill_re[7], t42);
        const __m256d t103 = _mm256_add_pd(t22, t40);
            _mm256_storeu_pd(&spill_re[5], t103);
        const __m256d t84 = _mm256_add_pd(t32, t37);
        const __m256d t86 = _mm256_sub_pd(t84, t81);
            _mm256_storeu_pd(&spill_im[6], t86);
        const __m256d t115 = _mm256_add_pd(t81, t84);
            _mm256_storeu_pd(&spill_im[4], t115);
        const __m256d t85 = _mm256_add_pd(t31, t36);
        const __m256d t88 = _mm256_sub_pd(t85, t82);
            _mm256_storeu_pd(&spill_re[6], t88);
        const __m256d t116 = _mm256_add_pd(t82, t85);
            _mm256_storeu_pd(&spill_re[4], t116);
        }
        {
            const __m256d t119 = _mm256_loadu_pd(&spill_re[0]);
            const __m256d t116 = _mm256_loadu_pd(&spill_re[4]);
        const __m256d t120 = _mm256_sub_pd(t119, t116);
            const __m256d t118 = _mm256_loadu_pd(&spill_im[0]);
            const __m256d t115 = _mm256_loadu_pd(&spill_im[4]);
        const __m256d t122 = _mm256_sub_pd(t118, t115);
        const __m256d t129 = _mm256_add_pd(t116, t119);
        const __m256d t130 = _mm256_add_pd(t115, t118);
            const __m256d t101 = _mm256_loadu_pd(&spill_im[5]);
            const __m256d t103 = _mm256_loadu_pd(&spill_re[5]);
        const __m256d t104 = _mm256_add_pd(t101, t103);
        _mm256_maskstore_pd(&rio_re[4*ios + k], _m, t120);
        _mm256_maskstore_pd(&rio_im[4*ios + k], _m, t122);
        _mm256_maskstore_pd(&rio_re[0*ios + k], _m, t129);
        _mm256_maskstore_pd(&rio_im[0*ios + k], _m, t130);
            const __m256d t111 = _mm256_loadu_pd(&spill_re[1]);
        const __m256d t133 = _mm256_fnmadd_pd(t44, t104, t111);
        const __m256d t137 = _mm256_fmadd_pd(t44, t104, t111);
        const __m256d t107 = _mm256_sub_pd(t101, t103);
            const __m256d t110 = _mm256_loadu_pd(&spill_im[1]);
        const __m256d t134 = _mm256_fnmadd_pd(t44, t107, t110);
        const __m256d t138 = _mm256_fmadd_pd(t44, t107, t110);
            const __m256d t98 = _mm256_loadu_pd(&spill_re[2]);
            const __m256d t86 = _mm256_loadu_pd(&spill_im[6]);
        const __m256d t99 = _mm256_sub_pd(t98, t86);
        _mm256_maskstore_pd(&rio_re[5*ios + k], _m, t133);
        _mm256_maskstore_pd(&rio_im[5*ios + k], _m, t134);
        _mm256_maskstore_pd(&rio_re[1*ios + k], _m, t137);
        _mm256_maskstore_pd(&rio_im[1*ios + k], _m, t138);
            const __m256d t88 = _mm256_loadu_pd(&spill_re[6]);
            const __m256d t96 = _mm256_loadu_pd(&spill_im[2]);
        const __m256d t100 = _mm256_add_pd(t88, t96);
        const __m256d t125 = _mm256_add_pd(t86, t98);
        const __m256d t126 = _mm256_sub_pd(t96, t88);
            const __m256d t42 = _mm256_loadu_pd(&spill_re[7]);
            const __m256d t41 = _mm256_loadu_pd(&spill_im[7]);
        const __m256d t43 = _mm256_sub_pd(t42, t41);
        _mm256_maskstore_pd(&rio_re[6*ios + k], _m, t99);
        _mm256_maskstore_pd(&rio_im[6*ios + k], _m, t100);
        _mm256_maskstore_pd(&rio_re[2*ios + k], _m, t125);
        _mm256_maskstore_pd(&rio_im[2*ios + k], _m, t126);
            const __m256d t78 = _mm256_loadu_pd(&spill_re[3]);
        const __m256d t131 = _mm256_fmadd_pd(t43, t44, t78);
        const __m256d t135 = _mm256_fnmadd_pd(t43, t44, t78);
        const __m256d t48 = _mm256_add_pd(t41, t42);
            const __m256d t77 = _mm256_loadu_pd(&spill_im[3]);
        const __m256d t132 = _mm256_fmadd_pd(t44, t48, t77);
        const __m256d t136 = _mm256_fnmadd_pd(t44, t48, t77);
        _mm256_maskstore_pd(&rio_re[7*ios + k], _m, t131);
        _mm256_maskstore_pd(&rio_im[7*ios + k], _m, t132);
        _mm256_maskstore_pd(&rio_re[3*ios + k], _m, t135);
        _mm256_maskstore_pd(&rio_im[3*ios + k], _m, t136);
        }
    }
}
/* codelet-metrics [intrinsic, gen-time]:
 *   fp_instr=96  flops=104  (add=22 sub=22 mul=0 fma=8 cmul=22 neg=0)
 *   essential_io=38 ops (vec_loads=22 + stores=16)  [+0 hoisted scalar-twiddle loads, not counted]
 *   cross_pass_cut=8 slots => +32 mem ops, 16 vectors live across pass boundary
 *   memory_floor=70 mem ops   peak_live(max-per-pass)=13   budget=14 regs
 *   ROOFLINE: compute-capable at floor (memory_floor <= fp_instr)
 *   PRESSURE: fits (peak_live <= budget)  [CT: peak_live is max over passes; cross_pass_cut is added explicit spill traffic]
 */
