/* Auto-generated by vfft_v2 codelet generator. */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix4_t1s_dit_bwd_avx2(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t ios,
    size_t me)
{
    for (size_t k = 0; k < me; k += 4) {
        __m256d regalloc_spill[1];
        register __m256d t0 asm("ymm0") = _mm256_loadu_pd(&rio_re[3*ios + k]); asm volatile ("" : "+v"(t0));
        register __m256d t1 asm("ymm1") = _mm256_set1_pd(tw_re[2]); asm volatile ("" : "+v"(t1));
        register __m256d t2 asm("ymm2") = _mm256_loadu_pd(&rio_im[3*ios + k]); asm volatile ("" : "+v"(t2));
        register __m256d t3 asm("ymm3") = _mm256_set1_pd(tw_im[2]); asm volatile ("" : "+v"(t3));
        register __m256d t5 asm("ymm4") = _mm256_fmadd_pd(t0, t1, _mm256_mul_pd(t2, t3)); asm volatile ("" : "+v"(t5));
        register __m256d t7 asm("ymm5") = _mm256_fnmadd_pd(t0, t3, _mm256_mul_pd(t2, t1)); asm volatile ("" : "+v"(t7));
        register __m256d t11 asm("ymm0") = _mm256_loadu_pd(&rio_re[1*ios + k]); asm volatile ("" : "+v"(t11));
        register __m256d t12 asm("ymm1") = _mm256_set1_pd(tw_re[0]); asm volatile ("" : "+v"(t12));
        register __m256d t13 asm("ymm2") = _mm256_loadu_pd(&rio_im[1*ios + k]); asm volatile ("" : "+v"(t13));
        register __m256d t14 asm("ymm3") = _mm256_set1_pd(tw_im[0]); asm volatile ("" : "+v"(t14));
        register __m256d t16 asm("ymm6") = _mm256_fmadd_pd(t11, t12, _mm256_mul_pd(t13, t14)); asm volatile ("" : "+v"(t16));
        register __m256d t18 asm("ymm7") = _mm256_fnmadd_pd(t11, t14, _mm256_mul_pd(t13, t12)); asm volatile ("" : "+v"(t18));
        register __m256d t20 asm("ymm0") = _mm256_sub_pd(t16, t5); asm volatile ("" : "+v"(t20));
        register __m256d t22 asm("ymm1") = _mm256_sub_pd(t18, t7); asm volatile ("" : "+v"(t22));
        register __m256d t24 asm("ymm2") = _mm256_loadu_pd(&rio_re[2*ios + k]); asm volatile ("" : "+v"(t24));
        register __m256d t25 asm("ymm3") = _mm256_set1_pd(tw_re[1]); asm volatile ("" : "+v"(t25));
        register __m256d t26 asm("ymm8") = _mm256_loadu_pd(&rio_im[2*ios + k]); asm volatile ("" : "+v"(t26));
        register __m256d t27 asm("ymm9") = _mm256_set1_pd(tw_im[1]); asm volatile ("" : "+v"(t27));
        register __m256d t29 asm("ymm10") = _mm256_fmadd_pd(t24, t25, _mm256_mul_pd(t26, t27)); asm volatile ("" : "+v"(t29));
        register __m256d t30 asm("ymm11") = _mm256_fnmadd_pd(t24, t27, _mm256_mul_pd(t26, t25)); asm volatile ("" : "+v"(t30));
        register __m256d t33 asm("ymm2") = _mm256_loadu_pd(&rio_re[0*ios + k]); asm volatile ("" : "+v"(t33));
        register __m256d t34 asm("ymm3") = _mm256_loadu_pd(&rio_im[0*ios + k]); asm volatile ("" : "+v"(t34));
        register __m256d t35 asm("ymm8") = _mm256_sub_pd(t33, t29); asm volatile ("" : "+v"(t35));
        register __m256d t37 asm("ymm9") = _mm256_sub_pd(t34, t30); asm volatile ("" : "+v"(t37));
        register __m256d t38 asm("ymm12") = _mm256_add_pd(t22, t35); asm volatile ("" : "+v"(t38));
        register __m256d t40 asm("ymm13") = _mm256_sub_pd(t37, t20); asm volatile ("" : "+v"(t40));
        _mm256_storeu_pd(&regalloc_spill[0], t40);
        register __m256d t41 asm("ymm13") = _mm256_add_pd(t5, t16); asm volatile ("" : "+v"(t41));
        register __m256d t42 asm("ymm4") = _mm256_add_pd(t7, t18); asm volatile ("" : "+v"(t42));
        register __m256d t44 asm("ymm5") = _mm256_add_pd(t29, t33); asm volatile ("" : "+v"(t44));
        register __m256d t45 asm("ymm2") = _mm256_add_pd(t30, t34); asm volatile ("" : "+v"(t45));
        register __m256d t46 asm("ymm3") = _mm256_sub_pd(t44, t41); asm volatile ("" : "+v"(t46));
        register __m256d t48 asm("ymm6") = _mm256_sub_pd(t45, t42); asm volatile ("" : "+v"(t48));
        register __m256d t49 asm("ymm7") = _mm256_sub_pd(t35, t22); asm volatile ("" : "+v"(t49));
        register __m256d t50 asm("ymm1") = _mm256_add_pd(t20, t37); asm volatile ("" : "+v"(t50));
        register __m256d t51 asm("ymm0") = _mm256_add_pd(t41, t44); asm volatile ("" : "+v"(t51));
        register __m256d t52 asm("ymm5") = _mm256_add_pd(t42, t45); asm volatile ("" : "+v"(t52));
        register __m256d t40_r0 asm("ymm8") = _mm256_loadu_pd(&regalloc_spill[0]); asm volatile ("" : "+v"(t40_r0));

        _mm256_storeu_pd(&rio_re[3*ios + k], t38);
        _mm256_storeu_pd(&rio_im[3*ios + k], t40_r0);
        _mm256_storeu_pd(&rio_re[2*ios + k], t46);
        _mm256_storeu_pd(&rio_im[2*ios + k], t48);
        _mm256_storeu_pd(&rio_re[1*ios + k], t49);
        _mm256_storeu_pd(&rio_im[1*ios + k], t50);
        _mm256_storeu_pd(&rio_re[0*ios + k], t51);
        _mm256_storeu_pd(&rio_im[0*ios + k], t52);
    }
}
