/* Auto-generated by vfft_v2 codelet generator. */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix8_t1_dit_fwd_avx2_gen_inplace_su_spill(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t ios,
    size_t me)
{
    __m256d spill_re[8];
    __m256d spill_im[8];
    for (size_t k = 0; k < me; k += 4) {
        const __m256d t38 = _mm256_set1_pd(0.70710678118655002);

        {
        const __m256d t48 = _mm256_loadu_pd(&rio_re[6*ios + k]);
        const __m256d t49 = _mm256_loadu_pd(&tw_re[5*me + k]);
        const __m256d t50 = _mm256_loadu_pd(&rio_im[6*ios + k]);
        const __m256d t51 = _mm256_loadu_pd(&tw_im[5*me + k]);
        const __m256d t52 = _mm256_fnmadd_pd(t50, t51, _mm256_mul_pd(t48, t49));
        const __m256d t53 = _mm256_fmadd_pd(t48, t51, _mm256_mul_pd(t50, t49));
        const __m256d t55 = _mm256_loadu_pd(&rio_re[2*ios + k]);
        const __m256d t56 = _mm256_loadu_pd(&tw_re[1*me + k]);
        const __m256d t57 = _mm256_loadu_pd(&rio_im[2*ios + k]);
        const __m256d t58 = _mm256_loadu_pd(&tw_im[1*me + k]);
        const __m256d t59 = _mm256_fnmadd_pd(t57, t58, _mm256_mul_pd(t55, t56));
        const __m256d t60 = _mm256_fmadd_pd(t55, t58, _mm256_mul_pd(t57, t56));
        const __m256d t61 = _mm256_sub_pd(t59, t52);
        const __m256d t63 = _mm256_sub_pd(t60, t53);
        const __m256d t93 = _mm256_add_pd(t52, t59);
        const __m256d t94 = _mm256_add_pd(t53, t60);
        const __m256d t66 = _mm256_loadu_pd(&rio_re[4*ios + k]);
        const __m256d t67 = _mm256_loadu_pd(&tw_re[3*me + k]);
        const __m256d t68 = _mm256_loadu_pd(&rio_im[4*ios + k]);
        const __m256d t69 = _mm256_loadu_pd(&tw_im[3*me + k]);
        const __m256d t70 = _mm256_fnmadd_pd(t68, t69, _mm256_mul_pd(t66, t67));
        const __m256d t71 = _mm256_fmadd_pd(t66, t69, _mm256_mul_pd(t68, t67));
        const __m256d t73 = _mm256_loadu_pd(&rio_re[0*ios + k]);
        const __m256d t75 = _mm256_sub_pd(t73, t70);
        const __m256d t78 = _mm256_sub_pd(t75, t63);
            _mm256_storeu_pd(&spill_re[3], t78);
        const __m256d t112 = _mm256_add_pd(t63, t75);
            _mm256_storeu_pd(&spill_re[1], t112);
        const __m256d t96 = _mm256_add_pd(t70, t73);
        const __m256d t98 = _mm256_sub_pd(t96, t93);
            _mm256_storeu_pd(&spill_re[2], t98);
        const __m256d t120 = _mm256_add_pd(t93, t96);
            _mm256_storeu_pd(&spill_re[0], t120);
        const __m256d t74 = _mm256_loadu_pd(&rio_im[0*ios + k]);
        const __m256d t77 = _mm256_sub_pd(t74, t71);
        const __m256d t79 = _mm256_add_pd(t61, t77);
            _mm256_storeu_pd(&spill_im[3], t79);
        const __m256d t113 = _mm256_sub_pd(t77, t61);
            _mm256_storeu_pd(&spill_im[1], t113);
        const __m256d t97 = _mm256_add_pd(t71, t74);
        const __m256d t100 = _mm256_sub_pd(t97, t94);
            _mm256_storeu_pd(&spill_im[2], t100);
        const __m256d t121 = _mm256_add_pd(t94, t97);
            _mm256_storeu_pd(&spill_im[0], t121);
        const __m256d t0 = _mm256_loadu_pd(&rio_re[7*ios + k]);
        const __m256d t1 = _mm256_loadu_pd(&tw_re[6*me + k]);
        const __m256d t2 = _mm256_loadu_pd(&rio_im[7*ios + k]);
        const __m256d t3 = _mm256_loadu_pd(&tw_im[6*me + k]);
        const __m256d t4 = _mm256_fnmadd_pd(t2, t3, _mm256_mul_pd(t0, t1));
        const __m256d t5 = _mm256_fmadd_pd(t0, t3, _mm256_mul_pd(t2, t1));
        const __m256d t9 = _mm256_loadu_pd(&rio_re[3*ios + k]);
        const __m256d t10 = _mm256_loadu_pd(&tw_re[2*me + k]);
        const __m256d t11 = _mm256_loadu_pd(&rio_im[3*ios + k]);
        const __m256d t12 = _mm256_loadu_pd(&tw_im[2*me + k]);
        const __m256d t13 = _mm256_fnmadd_pd(t11, t12, _mm256_mul_pd(t9, t10));
        const __m256d t14 = _mm256_fmadd_pd(t9, t12, _mm256_mul_pd(t11, t10));
        const __m256d t16 = _mm256_sub_pd(t13, t4);
        const __m256d t18 = _mm256_sub_pd(t14, t5);
        const __m256d t83 = _mm256_add_pd(t4, t13);
        const __m256d t84 = _mm256_add_pd(t5, t14);
        const __m256d t21 = _mm256_loadu_pd(&rio_re[5*ios + k]);
        const __m256d t22 = _mm256_loadu_pd(&tw_re[4*me + k]);
        const __m256d t23 = _mm256_loadu_pd(&rio_im[5*ios + k]);
        const __m256d t24 = _mm256_loadu_pd(&tw_im[4*me + k]);
        const __m256d t25 = _mm256_fnmadd_pd(t23, t24, _mm256_mul_pd(t21, t22));
        const __m256d t26 = _mm256_fmadd_pd(t21, t24, _mm256_mul_pd(t23, t22));
        const __m256d t28 = _mm256_loadu_pd(&rio_re[1*ios + k]);
        const __m256d t29 = _mm256_loadu_pd(&tw_re[0*me + k]);
        const __m256d t30 = _mm256_loadu_pd(&rio_im[1*ios + k]);
        const __m256d t31 = _mm256_loadu_pd(&tw_im[0*me + k]);
        const __m256d t32 = _mm256_fnmadd_pd(t30, t31, _mm256_mul_pd(t28, t29));
        const __m256d t33 = _mm256_fmadd_pd(t28, t31, _mm256_mul_pd(t30, t29));
        const __m256d t34 = _mm256_sub_pd(t32, t25);
        const __m256d t37 = _mm256_sub_pd(t34, t18);
            _mm256_storeu_pd(&spill_re[7], t37);
        const __m256d t103 = _mm256_add_pd(t18, t34);
            _mm256_storeu_pd(&spill_re[5], t103);
        const __m256d t36 = _mm256_sub_pd(t33, t26);
        const __m256d t40 = _mm256_add_pd(t16, t36);
            _mm256_storeu_pd(&spill_im[7], t40);
        const __m256d t104 = _mm256_sub_pd(t36, t16);
            _mm256_storeu_pd(&spill_im[5], t104);
        const __m256d t86 = _mm256_add_pd(t25, t32);
        const __m256d t88 = _mm256_sub_pd(t86, t83);
            _mm256_storeu_pd(&spill_re[6], t88);
        const __m256d t117 = _mm256_add_pd(t83, t86);
            _mm256_storeu_pd(&spill_re[4], t117);
        const __m256d t87 = _mm256_add_pd(t26, t33);
        const __m256d t90 = _mm256_sub_pd(t87, t84);
            _mm256_storeu_pd(&spill_im[6], t90);
        const __m256d t118 = _mm256_add_pd(t84, t87);
            _mm256_storeu_pd(&spill_im[4], t118);
        }
        {
            const __m256d t120 = _mm256_loadu_pd(&spill_re[0]);
            const __m256d t117 = _mm256_loadu_pd(&spill_re[4]);
        const __m256d t122 = _mm256_sub_pd(t120, t117);
            const __m256d t121 = _mm256_loadu_pd(&spill_im[0]);
            const __m256d t118 = _mm256_loadu_pd(&spill_im[4]);
        const __m256d t124 = _mm256_sub_pd(t121, t118);
        const __m256d t131 = _mm256_add_pd(t117, t120);
        const __m256d t132 = _mm256_add_pd(t118, t121);
            const __m256d t104 = _mm256_loadu_pd(&spill_im[5]);
        const __m256d t105 = _mm256_mul_pd(t38, t104);
        _mm256_storeu_pd(&rio_re[4*ios + k], t122);
        _mm256_storeu_pd(&rio_im[4*ios + k], t124);
        _mm256_storeu_pd(&rio_re[0*ios + k], t131);
        _mm256_storeu_pd(&rio_im[0*ios + k], t132);
            const __m256d t103 = _mm256_loadu_pd(&spill_re[5]);
        const __m256d t107 = _mm256_mul_pd(t38, t103);
        const __m256d t108 = _mm256_add_pd(t105, t107);
            const __m256d t112 = _mm256_loadu_pd(&spill_re[1]);
        const __m256d t114 = _mm256_sub_pd(t112, t108);
        const __m256d t129 = _mm256_add_pd(t108, t112);
        const __m256d t110 = _mm256_sub_pd(t105, t107);
            const __m256d t113 = _mm256_loadu_pd(&spill_im[1]);
        const __m256d t116 = _mm256_sub_pd(t113, t110);
        const __m256d t130 = _mm256_add_pd(t110, t113);
            const __m256d t98 = _mm256_loadu_pd(&spill_re[2]);
            const __m256d t90 = _mm256_loadu_pd(&spill_im[6]);
        const __m256d t101 = _mm256_sub_pd(t98, t90);
        _mm256_storeu_pd(&rio_re[5*ios + k], t114);
        _mm256_storeu_pd(&rio_im[5*ios + k], t116);
        _mm256_storeu_pd(&rio_re[1*ios + k], t129);
        _mm256_storeu_pd(&rio_im[1*ios + k], t130);
            const __m256d t88 = _mm256_loadu_pd(&spill_re[6]);
            const __m256d t100 = _mm256_loadu_pd(&spill_im[2]);
        const __m256d t102 = _mm256_add_pd(t88, t100);
        const __m256d t127 = _mm256_add_pd(t90, t98);
        const __m256d t128 = _mm256_sub_pd(t100, t88);
            const __m256d t40 = _mm256_loadu_pd(&spill_im[7]);
        const __m256d t41 = _mm256_mul_pd(t38, t40);
        _mm256_storeu_pd(&rio_re[6*ios + k], t101);
        _mm256_storeu_pd(&rio_im[6*ios + k], t102);
        _mm256_storeu_pd(&rio_re[2*ios + k], t127);
        _mm256_storeu_pd(&rio_im[2*ios + k], t128);
            const __m256d t37 = _mm256_loadu_pd(&spill_re[7]);
        const __m256d t45 = _mm256_sub_pd(t41, _mm256_mul_pd(t37, t38));
            const __m256d t78 = _mm256_loadu_pd(&spill_re[3]);
        const __m256d t80 = _mm256_sub_pd(t78, t45);
        const __m256d t125 = _mm256_add_pd(t45, t78);
        const __m256d t46 = _mm256_fnmsub_pd(t37, t38, t41);
            const __m256d t79 = _mm256_loadu_pd(&spill_im[3]);
        const __m256d t82 = _mm256_sub_pd(t79, t46);
        const __m256d t126 = _mm256_add_pd(t46, t79);
        _mm256_storeu_pd(&rio_re[7*ios + k], t80);
        _mm256_storeu_pd(&rio_im[7*ios + k], t82);
        _mm256_storeu_pd(&rio_re[3*ios + k], t125);
        _mm256_storeu_pd(&rio_im[3*ios + k], t126);
        }
    }
}
