/* Auto-generated by vfft_v2 codelet generator. */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix7_t1_dif_log3_bwd_avx2_gen_inplace_su(
    double       * __restrict__ rio_re,
    double       * __restrict__ rio_im,
    const double * __restrict__ tw_re,
    const double * __restrict__ tw_im,
    size_t ios,
    size_t me)
{
    for (size_t k = 0; k < me; k += 4) {
        __m256d regalloc_spill[19];
        register __m256d t26 asm("ymm0") = _mm256_set1_pd(0.43388373911756001); asm volatile ("" : "+v"(t26));
        register __m256d t29 asm("ymm1") = _mm256_set1_pd(0.97492791218181996); asm volatile ("" : "+v"(t29));
        register __m256d t38 asm("ymm2") = _mm256_set1_pd(0.90096886790242003); asm volatile ("" : "+v"(t38));
        register __m256d t40 asm("ymm3") = _mm256_set1_pd(0.22252093395631001); asm volatile ("" : "+v"(t40));
        register __m256d t42 asm("ymm4") = _mm256_set1_pd(0.62348980185873004); asm volatile ("" : "+v"(t42));
        register __m256d t32 asm("ymm5") = _mm256_set1_pd(0.78183148246803003); asm volatile ("" : "+v"(t32));
        register __m256d t0 asm("ymm6") = _mm256_loadu_pd(&rio_re[4*ios + k]); asm volatile ("" : "+v"(t0));
        register __m256d t1 asm("ymm7") = _mm256_loadu_pd(&rio_re[3*ios + k]); asm volatile ("" : "+v"(t1));
        register __m256d t2 asm("ymm8") = _mm256_add_pd(t0, t1); asm volatile ("" : "+v"(t2));
        register __m256d t49 asm("ymm9") = _mm256_sub_pd(t1, t0); asm volatile ("" : "+v"(t49));
        register __m256d t3 asm("ymm6") = _mm256_loadu_pd(&rio_re[5*ios + k]); asm volatile ("" : "+v"(t3));
        register __m256d t4 asm("ymm7") = _mm256_loadu_pd(&rio_re[2*ios + k]); asm volatile ("" : "+v"(t4));
        register __m256d t51 asm("ymm10") = _mm256_sub_pd(t4, t3); asm volatile ("" : "+v"(t51));
        register __m256d t5 asm("ymm11") = _mm256_add_pd(t3, t4); asm volatile ("" : "+v"(t5));
        register __m256d t6 asm("ymm6") = _mm256_loadu_pd(&rio_re[6*ios + k]); asm volatile ("" : "+v"(t6));
        register __m256d t7 asm("ymm7") = _mm256_loadu_pd(&rio_re[1*ios + k]); asm volatile ("" : "+v"(t7));
        register __m256d t8 asm("ymm12") = _mm256_add_pd(t6, t7); asm volatile ("" : "+v"(t8));
        register __m256d t53 asm("ymm13") = _mm256_sub_pd(t7, t6); asm volatile ("" : "+v"(t53));
        register __m256d t193 asm("ymm6") = _mm256_fnmadd_pd(t26, t49, _mm256_fnmsub_pd(t32, t53, _mm256_mul_pd(t29, t51))); asm volatile ("" : "+v"(t193));
        register __m256d t207 asm("ymm7") = _mm256_fmadd_pd(t32, t49, _mm256_fmsub_pd(t26, t51, _mm256_mul_pd(t29, t53))); asm volatile ("" : "+v"(t207));
        _mm256_storeu_pd(&regalloc_spill[0], t207);
        register __m256d t221 asm("ymm7") = _mm256_fnmadd_pd(t29, t49, _mm256_fmsub_pd(t32, t51, _mm256_mul_pd(t26, t53))); asm volatile ("" : "+v"(t221));
        register __m256d t9 asm("ymm9") = _mm256_loadu_pd(&rio_re[0*ios + k]); asm volatile ("" : "+v"(t9));
        register __m256d t188 asm("ymm10") = _mm256_fnmadd_pd(t2, t38, _mm256_fnmadd_pd(t5, t40, _mm256_fmadd_pd(t8, t42, t9))); asm volatile ("" : "+v"(t188));
        register __m256d t201 asm("ymm13") = _mm256_fmadd_pd(t2, t42, _mm256_fnmadd_pd(t5, t38, _mm256_fnmadd_pd(t8, t40, t9))); asm volatile ("" : "+v"(t201));
        _mm256_storeu_pd(&regalloc_spill[1], t221);
        register __m256d t215 asm("ymm7") = _mm256_fnmadd_pd(t2, t40, _mm256_fmadd_pd(t5, t42, _mm256_fnmadd_pd(t8, t38, t9))); asm volatile ("" : "+v"(t215));
        _mm256_storeu_pd(&regalloc_spill[2], t193);
        register __m256d t12 asm("ymm6") = _mm256_add_pd(t2, _mm256_add_pd(t5, _mm256_add_pd(t8, t9))); asm volatile ("" : "+v"(t12));
        register __m256d t13 asm("ymm8") = _mm256_loadu_pd(&rio_im[4*ios + k]); asm volatile ("" : "+v"(t13));
        register __m256d t14 asm("ymm9") = _mm256_loadu_pd(&rio_im[3*ios + k]); asm volatile ("" : "+v"(t14));
        register __m256d t15 asm("ymm11") = _mm256_add_pd(t13, t14); asm volatile ("" : "+v"(t15));
        register __m256d t27 asm("ymm12") = _mm256_sub_pd(t14, t13); asm volatile ("" : "+v"(t27));
        register __m256d t16 asm("ymm8") = _mm256_loadu_pd(&rio_im[5*ios + k]); asm volatile ("" : "+v"(t16));
        register __m256d t17 asm("ymm9") = _mm256_loadu_pd(&rio_im[2*ios + k]); asm volatile ("" : "+v"(t17));
        _mm256_storeu_pd(&regalloc_spill[3], t12);
        register __m256d t30 asm("ymm6") = _mm256_sub_pd(t17, t16); asm volatile ("" : "+v"(t30));
        _mm256_storeu_pd(&regalloc_spill[4], t15);
        register __m256d t18 asm("ymm11") = _mm256_add_pd(t16, t17); asm volatile ("" : "+v"(t18));
        register __m256d t19 asm("ymm8") = _mm256_loadu_pd(&rio_im[6*ios + k]); asm volatile ("" : "+v"(t19));
        register __m256d t20 asm("ymm9") = _mm256_loadu_pd(&rio_im[1*ios + k]); asm volatile ("" : "+v"(t20));
        _mm256_storeu_pd(&regalloc_spill[5], t18);
        register __m256d t21 asm("ymm11") = _mm256_add_pd(t19, t20); asm volatile ("" : "+v"(t21));
        _mm256_storeu_pd(&regalloc_spill[6], t38);
        register __m256d t33 asm("ymm2") = _mm256_sub_pd(t20, t19); asm volatile ("" : "+v"(t33));
        register __m256d t185 asm("ymm8") = _mm256_fnmadd_pd(t26, t27, _mm256_fnmsub_pd(t32, t33, _mm256_mul_pd(t29, t30))); asm volatile ("" : "+v"(t185));
        register __m256d t198 asm("ymm9") = _mm256_fmadd_pd(t27, t32, _mm256_fmsub_pd(t26, t30, _mm256_mul_pd(t29, t33))); asm volatile ("" : "+v"(t198));
        _mm256_storeu_pd(&regalloc_spill[7], t40);
        register __m256d t212 asm("ymm3") = _mm256_fnmadd_pd(t27, t29, _mm256_fmsub_pd(t30, t32, _mm256_mul_pd(t26, t33))); asm volatile ("" : "+v"(t212));
        register __m256d t189 asm("ymm0") = _mm256_add_pd(t185, t188); asm volatile ("" : "+v"(t189));
        register __m256d t202 asm("ymm1") = _mm256_add_pd(t198, t201); asm volatile ("" : "+v"(t202));
        register __m256d t216 asm("ymm2") = _mm256_add_pd(t212, t215); asm volatile ("" : "+v"(t216));
        register __m256d t225 asm("ymm5") = _mm256_sub_pd(t215, t212); asm volatile ("" : "+v"(t225));
        register __m256d t229 asm("ymm3") = _mm256_sub_pd(t201, t198); asm volatile ("" : "+v"(t229));
        register __m256d t233 asm("ymm6") = _mm256_sub_pd(t188, t185); asm volatile ("" : "+v"(t233));
        register __m256d t22 asm("ymm7") = _mm256_loadu_pd(&rio_im[0*ios + k]); asm volatile ("" : "+v"(t22));
        register __m256d t40_r0 asm("ymm8") = _mm256_loadu_pd(&regalloc_spill[7]); asm volatile ("" : "+v"(t40_r0));
        register __m256d t38_r0 asm("ymm9") = _mm256_loadu_pd(&regalloc_spill[6]); asm volatile ("" : "+v"(t38_r0));
        register __m256d t18_r0 asm("ymm10") = _mm256_loadu_pd(&regalloc_spill[5]); asm volatile ("" : "+v"(t18_r0));
        register __m256d t15_r0 asm("ymm12") = _mm256_loadu_pd(&regalloc_spill[4]); asm volatile ("" : "+v"(t15_r0));
        register __m256d t192 asm("ymm13") = _mm256_fnmadd_pd(t15_r0, t38_r0, _mm256_fnmadd_pd(t18_r0, t40_r0, _mm256_fmadd_pd(t21, t42, t22))); asm volatile ("" : "+v"(t192));
        _mm256_storeu_pd(&regalloc_spill[8], t233);
        register __m256d t205 asm("ymm6") = _mm256_fmadd_pd(t15_r0, t42, _mm256_fnmadd_pd(t18_r0, t38_r0, _mm256_fnmadd_pd(t21, t40_r0, t22))); asm volatile ("" : "+v"(t205));
        _mm256_storeu_pd(&regalloc_spill[9], t229);
        register __m256d t219 asm("ymm3") = _mm256_fnmadd_pd(t15_r0, t40_r0, _mm256_fmadd_pd(t18_r0, t42, _mm256_fnmadd_pd(t21, t38_r0, t22))); asm volatile ("" : "+v"(t219));
        register __m256d t25 asm("ymm4") = _mm256_add_pd(t15_r0, _mm256_add_pd(t18_r0, _mm256_add_pd(t21, t22))); asm volatile ("" : "+v"(t25));
        register __m256d t193_r0 asm("ymm7") = _mm256_loadu_pd(&regalloc_spill[2]); asm volatile ("" : "+v"(t193_r0));
        register __m256d t194 asm("ymm8") = _mm256_sub_pd(t192, t193_r0); asm volatile ("" : "+v"(t194));
        register __m256d t207_r0 asm("ymm9") = _mm256_loadu_pd(&regalloc_spill[0]); asm volatile ("" : "+v"(t207_r0));
        register __m256d t208 asm("ymm10") = _mm256_sub_pd(t205, t207_r0); asm volatile ("" : "+v"(t208));
        register __m256d t221_r0 asm("ymm11") = _mm256_loadu_pd(&regalloc_spill[1]); asm volatile ("" : "+v"(t221_r0));
        register __m256d t222 asm("ymm12") = _mm256_sub_pd(t219, t221_r0); asm volatile ("" : "+v"(t222));
        _mm256_storeu_pd(&regalloc_spill[10], t25);
        register __m256d t226 asm("ymm4") = _mm256_add_pd(t219, t221_r0); asm volatile ("" : "+v"(t226));
        register __m256d t230 asm("ymm3") = _mm256_add_pd(t205, t207_r0); asm volatile ("" : "+v"(t230));
        register __m256d t234 asm("ymm6") = _mm256_add_pd(t192, t193_r0); asm volatile ("" : "+v"(t234));
        register __m256d t48 asm("ymm7") = _mm256_loadu_pd(&tw_re[0*me + k]); asm volatile ("" : "+v"(t48));
        register __m256d t65 asm("ymm9") = _mm256_loadu_pd(&tw_im[0*me + k]); asm volatile ("" : "+v"(t65));
        register __m256d t195 asm("ymm11") = _mm256_fmadd_pd(t189, t48, _mm256_mul_pd(t194, t65)); asm volatile ("" : "+v"(t195));
        register __m256d t196 asm("ymm13") = _mm256_fnmadd_pd(t189, t65, _mm256_mul_pd(t194, t48)); asm volatile ("" : "+v"(t196));
        register __m256d t83 asm("ymm0") = _mm256_loadu_pd(&tw_re[1*me + k]); asm volatile ("" : "+v"(t83));
        register __m256d t97 asm("ymm8") = _mm256_loadu_pd(&tw_im[1*me + k]); asm volatile ("" : "+v"(t97));
        _mm256_storeu_pd(&regalloc_spill[11], t195);
        register __m256d t209 asm("ymm11") = _mm256_fmadd_pd(t202, t83, _mm256_mul_pd(t208, t97)); asm volatile ("" : "+v"(t209));
        _mm256_storeu_pd(&regalloc_spill[12], t196);
        register __m256d t210 asm("ymm13") = _mm256_fnmadd_pd(t202, t97, _mm256_mul_pd(t208, t83)); asm volatile ("" : "+v"(t210));
        register __m256d t115 asm("ymm1") = _mm256_fnmadd_pd(t97, t65, _mm256_mul_pd(t83, t48)); asm volatile ("" : "+v"(t115));
        register __m256d t116 asm("ymm10") = _mm256_fmadd_pd(t83, t65, _mm256_mul_pd(t97, t48)); asm volatile ("" : "+v"(t116));
        _mm256_storeu_pd(&regalloc_spill[13], t209);
        register __m256d t223 asm("ymm11") = _mm256_fmadd_pd(t216, t115, _mm256_mul_pd(t222, t116)); asm volatile ("" : "+v"(t223));
        _mm256_storeu_pd(&regalloc_spill[14], t223);
        register __m256d t224 asm("ymm11") = _mm256_fnmadd_pd(t216, t116, _mm256_mul_pd(t222, t115)); asm volatile ("" : "+v"(t224));
        register __m256d t135 asm("ymm1") = _mm256_loadu_pd(&tw_re[3*me + k]); asm volatile ("" : "+v"(t135));
        register __m256d t137 asm("ymm2") = _mm256_loadu_pd(&tw_im[3*me + k]); asm volatile ("" : "+v"(t137));
        register __m256d t227 asm("ymm10") = _mm256_fmadd_pd(t225, t135, _mm256_mul_pd(t226, t137)); asm volatile ("" : "+v"(t227));
        register __m256d t228 asm("ymm12") = _mm256_fnmadd_pd(t225, t137, _mm256_mul_pd(t226, t135)); asm volatile ("" : "+v"(t228));
        register __m256d t143 asm("ymm4") = _mm256_fnmadd_pd(t137, t65, _mm256_mul_pd(t135, t48)); asm volatile ("" : "+v"(t143));
        register __m256d t144 asm("ymm5") = _mm256_fmadd_pd(t135, t65, _mm256_mul_pd(t137, t48)); asm volatile ("" : "+v"(t144));
        register __m256d t229_r0 asm("ymm7") = _mm256_loadu_pd(&regalloc_spill[9]); asm volatile ("" : "+v"(t229_r0));
        register __m256d t231 asm("ymm9") = _mm256_fmadd_pd(t229_r0, t143, _mm256_mul_pd(t230, t144)); asm volatile ("" : "+v"(t231));
        _mm256_storeu_pd(&regalloc_spill[15], t231);
        register __m256d t232 asm("ymm9") = _mm256_fnmadd_pd(t229_r0, t144, _mm256_mul_pd(t230, t143)); asm volatile ("" : "+v"(t232));
        register __m256d t151 asm("ymm3") = _mm256_fnmadd_pd(t137, t97, _mm256_mul_pd(t135, t83)); asm volatile ("" : "+v"(t151));
        register __m256d t152 asm("ymm4") = _mm256_fmadd_pd(t135, t97, _mm256_mul_pd(t137, t83)); asm volatile ("" : "+v"(t152));
        register __m256d t233_r0 asm("ymm0") = _mm256_loadu_pd(&regalloc_spill[8]); asm volatile ("" : "+v"(t233_r0));
        register __m256d t235 asm("ymm1") = _mm256_fmadd_pd(t233_r0, t151, _mm256_mul_pd(t234, t152)); asm volatile ("" : "+v"(t235));
        register __m256d t236 asm("ymm2") = _mm256_fnmadd_pd(t233_r0, t152, _mm256_mul_pd(t234, t151)); asm volatile ("" : "+v"(t236));
        _mm256_storeu_pd(&regalloc_spill[18], t234);
        _mm256_storeu_pd(&regalloc_spill[17], t151);
        _mm256_storeu_pd(&regalloc_spill[16], t152);
        register __m256d t231_r0 asm("ymm6") = _mm256_loadu_pd(&regalloc_spill[15]); asm volatile ("" : "+v"(t231_r0));
        register __m256d t195_r0 asm("ymm0") = _mm256_loadu_pd(&regalloc_spill[11]); asm volatile ("" : "+v"(t195_r0));
        register __m256d t223_r0 asm("ymm3") = _mm256_loadu_pd(&regalloc_spill[14]); asm volatile ("" : "+v"(t223_r0));
        register __m256d t196_r0 asm("ymm4") = _mm256_loadu_pd(&regalloc_spill[12]); asm volatile ("" : "+v"(t196_r0));
        register __m256d t209_r0 asm("ymm8") = _mm256_loadu_pd(&regalloc_spill[13]); asm volatile ("" : "+v"(t209_r0));
        register __m256d t12_r0 asm("ymm7") = _mm256_loadu_pd(&regalloc_spill[3]); asm volatile ("" : "+v"(t12_r0));
        register __m256d t25_r0 asm("ymm5") = _mm256_loadu_pd(&regalloc_spill[10]); asm volatile ("" : "+v"(t25_r0));

        _mm256_storeu_pd(&rio_re[0*ios + k], t12_r0);
        _mm256_storeu_pd(&rio_im[0*ios + k], t25_r0);
        _mm256_storeu_pd(&rio_re[1*ios + k], t195_r0);
        _mm256_storeu_pd(&rio_im[1*ios + k], t196_r0);
        _mm256_storeu_pd(&rio_re[2*ios + k], t209_r0);
        _mm256_storeu_pd(&rio_im[2*ios + k], t210);
        _mm256_storeu_pd(&rio_re[3*ios + k], t223_r0);
        _mm256_storeu_pd(&rio_im[3*ios + k], t224);
        _mm256_storeu_pd(&rio_re[4*ios + k], t227);
        _mm256_storeu_pd(&rio_im[4*ios + k], t228);
        _mm256_storeu_pd(&rio_re[5*ios + k], t231_r0);
        _mm256_storeu_pd(&rio_im[5*ios + k], t232);
        _mm256_storeu_pd(&rio_re[6*ios + k], t235);
        _mm256_storeu_pd(&rio_im[6*ios + k], t236);
    }
}
